#ifndef _BOARDS_H_
#define _BOARDS_H_

const char *boards[] = {
    "unknown",        // 0
    "basic",          // 1
    "core2",          // 2
    "stickc",         // 3
    "stickc-plus",    // 4
    "stickc-plus2",   // 5
    "coreink",        // 6
    "paper",          // 7
    "tough",          // 8
    "station",        // 9
    "cores3",         // 10
    "atoms3",         // 11
    "dial",           // 12
    "dinmeter",       // 13
    "cardputer",      // 14
    "airq",           // 15
    "vameter",        // 16
    "cores3se",       // 17
    "atoms3r",        // 18
    "papers3",        // 19
    "unknown",        // 20
    "stamplc",        // 21
    "tab5",           // 22
    "arduino-nesso-n1", // 23
    "cardputer-adv",  // 24
    "unknown",        // 25
    "unknown",        // 26
    "unknown",        // 27
    "unknown",        // 28
    "unknown",        // 29
    "unknown",        // 30
    "unknown",        // 31
    "unknown",        // 32
    "unknown",        // 33
    "unknown",        // 34
    "unknown",        // 35
    "unknown",        // 36
    "unknown",        // 37
    "unknown",        // 38
    "unknown",        // 39
    "unknown",        // 40
    "unknown",        // 41
    "unknown",        // 42
    "unknown",        // 43
    "unknown",        // 44
    "unknown",        // 45
    "unknown",        // 46
    "unknown",        // 47
    "unknown",        // 48
    "unknown",        // 49
    "unknown",        // 50
    "unknown",        // 51
    "unknown",        // 52
    "unknown",        // 53
    "unknown",        // 54
    "unknown",        // 55
    "unknown",        // 56
    "unknown",        // 57
    "unknown",        // 58
    "unknown",        // 59
    "unknown",        // 60
    "unknown",        // 61
    "unknown",        // 62
    "unknown",        // 63
    "unknown",        // 64
    "unknown",        // 65
    "unknown",        // 66
    "unknown",        // 67
    "unknown",        // 68
    "unknown",        // 69
    "unknown",        // 70
    "unknown",        // 71
    "unknown",        // 72
    "unknown",        // 73
    "unknown",        // 74
    "unknown",        // 75
    "unknown",        // 76
    "unknown",        // 77
    "unknown",        // 78
    "unknown",        // 79
    "unknown",        // 80
    "unknown",        // 81
    "unknown",        // 82
    "unknown",        // 83
    "unknown",        // 84
    "unknown",        // 85
    "unknown",        // 86
    "unknown",        // 87
    "unknown",        // 88
    "unknown",        // 89
    "unknown",        // 90
    "unknown",        // 91
    "unknown",        // 92
    "unknown",        // 93
    "unknown",        // 94
    "unknown",        // 95
    "unknown",        // 96
    "unknown",        // 97
    "unknown",        // 98
    "unknown",        // 99
    "unknown",        // 100
    "unknown",        // 101
    "unknown",        // 102
    "unknown",        // 103
    "unknown",        // 104
    "unknown",        // 105
    "unknown",        // 106
    "unknown",        // 107
    "unknown",        // 108
    "unknown",        // 109
    "unknown",        // 110
    "unknown",        // 111
    "unknown",        // 112
    "unknown",        // 113
    "unknown",        // 114
    "unknown",        // 115
    "unknown",        // 116
    "unknown",        // 117
    "unknown",        // 118
    "unknown",        // 119
    "unknown",        // 120
    "unknown",        // 121
    "unknown",        // 122
    "unknown",        // 123
    "unknown",        // 124
    "unknown",        // 125
    "unknown",        // 126
    "unknown",        // 127

    /// non display boards
    "atom",           // 128
    "atom-psram",     // 129
    "atomu",          // 130
    "m5camera",       // 131
    "timercam",       // 132
    "stamppico",      // 133
    "stampc3",        // 134
    "stampc3u",       // 135
    "stamps3",        // 136
    "atoms3-lite",    // 137
    "atoms3u",        // 138
    "capsule",        // 139
    "nanoc6",         // 140
    "atom-matrix",    // 141
    "atom-echo",      // 142
    "atoms3r-ext",    // 143
    "atoms3r-cam",    // 144
    "unknown",        // 145
    "unknown",        // 146
    "unknown",        // 147
    "unknown",        // 148
    "unknown",        // 149
    "unknown",        // 150
    "unknown",        // 151
    "unknown",        // 152
    "unknown",        // 153
    "unknown",        // 154
    "unknown",        // 155
    "unknown",        // 156
    "unknown",        // 157
    "unknown",        // 158
    "unknown",        // 159
    "unknown",        // 160
    "unknown",        // 161
    "unknown",        // 162
    "unknown",        // 163
    "unknown",        // 164
    "unknown",        // 165
    "unknown",        // 166
    "unknown",        // 167
    "unknown",        // 168
    "unknown",        // 169
    "unknown",        // 170
    "unknown",        // 171
    "unknown",        // 172
    "unknown",        // 173
    "unknown",        // 174
    "unknown",        // 175
    "unknown",        // 176
    "unknown",        // 177
    "unknown",        // 178
    "unknown",        // 179
    "unknown",        // 180
    "unknown",        // 181
    "unknown",        // 182
    "unknown",        // 183
    "unknown",        // 184
    "unknown",        // 185
    "unknown",        // 186
    "unknown",        // 187
    "unknown",        // 188
    "unknown",        // 189
    "unknown",        // 190
    "unknown",        // 191

    /// external displays
    "atom-display",   // 192
    "unit-lcd",       // 193
    "unit-oled",      // 194
    "unit-minioled",  // 195
    "unit-glass",     // 196
    "unit-glass2",    // 197
    "unit-rca",       // 198
    "module-display", // 198
    "module-rca",     // 200
};

#endif
