"""
This type stub file was generated by pyright.
"""

from machine import I2C
from .pahub import PAHUBUnit

"""
This type stub file was generated by pyright.
"""
class DAC2Unit:
    """! DAC2 is a Digital to Analog Converter, GP8413 15bit DAC.

    @en DAC2 is a Digital to Analog Converter, includes GP8413 15bit DAC. The GP8413, through the I2C interface, linearly converts to two channels of analog voltage output, 0-5V and 0-10V.
    @cn DAC2 是一个数字模拟转换器，包含GP8413 15位DAC。GP8413通过I2C接口线性转换为两个通道的模拟电压输出，0-5V和0-10V。

    @attr RANGE_5V output from 0 to 5V
    @attr RANGE_10V output from 0 to 10V
    @color #0FE6D7
    @link https://docs.m5stack.com/en/unit/dac
    @image https://static-cdn.m5stack.com/resource/docs/products/unit/dac/dac_01.webp
    """
    RANGE_5V = ...
    RANGE_10V = ...
    CHANNEL_0 = ...
    CHANNEL_1 = ...
    CHANNEL_BOTH = ...
    def __init__(self, i2c: I2C | PAHUBUnit, address: int | list | tuple = ...) -> None:
        """! Initialize the DAC.

        @param port I2C port to use.
        @param addr I2C address of the sensor.
        """
        ...
    
    def set_dacoutput_voltage_range(self, _range: int = ...):
        """!

        @en Set the DAC %1 output voltage range to %2.
        @cn 设置DAC %1 输出电压范围为 %2。

        @param range The DAC range to set.
        """
        ...
    
    def set_voltage(self, voltage: float, channel: int = ...):
        """!
        @en Set %1 channel %3 to %2 V.
        @cn 设置DAC %1 通道 %3 的输出电压为 %1 V。

        @param voltage The DAC voltage to set, from 0.0 to range.
        @param channel [field_dropdown] The DAC channel to set.
               @options {
                        [Channel 0, CHANNEL_0]
                    [Channel 1, CHANNEL_1]
                    [Both Channel, CHANNEL_BOTH]
                           }
        """
        ...
    
    def set_voltage_both(self, voltage0: float, voltage1: float):
        """!
        @en Set the DAC %1 channel 0 %2 V, channel 1 %3 V.
        @cn 设置 %1 通道0的电压为 %2 V，通道1的电压为 %3 V。

        @param voltage0 The DAC voltage of channel 0 to set.
        @param voltage1 The DAC voltage of channel 1 to set.
        """
        ...
    


