"""
This type stub file was generated by pyright.
"""

import sys
from driver.asr650x import LoRaWAN_470
from typing import Literal

"""
This type stub file was generated by pyright.
"""
if sys.platform != "esp32":
    ...
class LoRaWANUnit(LoRaWAN_470):
    def __init__(self, id: Literal[0, 1, 2] = ..., port: list | tuple = ...) -> None:
        ...
    
    def deinit(self):
        ...
    


