"""
This type stub file was generated by pyright.
"""

import sys
from typing import Literal

"""
This type stub file was generated by pyright.
"""
if sys.platform != "esp32":
    ...
class PIRUnit:
    IRQ_NEGATIVE = ...
    IRQ_ACTIVE = ...
    def __init__(self, port: tuple) -> None:
        ...
    
    def get_status(self) -> bool:
        ...
    
    def set_callback(self, handler, trigger: Literal[0, 1]) -> None:
        ...
    
    def disable_irq(self) -> None:
        ...
    
    def enable_irq(self) -> None:
        ...
    


