"""
This type stub file was generated by pyright.
"""

"""
This type stub file was generated by pyright.
"""
class RS485Unit:
    def __new__(cls, id, **kwargs):
        ...
    
    def __getattr__(self, name):
        ...
    
    def __setattr__(self, name, value):
        ...
    
    def init(self, tx_pin=..., rx_pin=..., baudrate=..., data_bits=..., stop_bits=..., parity=..., **kwargs):
        ...
    


