"""
This type stub file was generated by pyright.
"""

from machine import I2C
from .pahub import PAHUBUnit
from driver.mlx90640 import MLX90640

"""
This type stub file was generated by pyright.
"""
THERMAL_ADDR = ...
class THERMALUnit(MLX90640):
    def __init__(self, i2c: I2C | PAHUBUnit, address: int | list | tuple = ...) -> None:
        ...
    
    @property
    def get_max_temperature(self):
        ...
    
    @property
    def get_min_temperature(self):
        ...
    
    @property
    def get_midpoint_temperature(self):
        ...
    
    def get_pixel_temperature(self, x, y):
        ...
    
    def get_temperature_buffer(self):
        ...
    
    def set_refresh_rate(self, rate):
        """
        REFRESH_0_5_HZ = 0b000  # 0.5Hz
        REFRESH_1_HZ = 0b001  # 1Hz
        REFRESH_2_HZ = 0b010  # 2Hz
        REFRESH_4_HZ = 0b011  # 4Hz
        REFRESH_8_HZ = 0b100  # 8Hz
        REFRESH_16_HZ = 0b101  # 16Hz
        REFRESH_32_HZ = 0b110  # 32Hz
        REFRESH_64_HZ = 0b111  # 64Hz
        """
        ...
    
    @property
    def get_refresh_rate(self):
        ...
    
    def update_temperature_buffer(self):
        ...
    


class ThermalUnit(THERMALUnit):
    def __init__(self, i2c: I2C | PAHUBUnit, address: int | list | tuple = ...) -> None:
        ...
    


