repos:
  - repo: local
    hooks:
      - id: codeformat
        name: MicroPython codeformat.py for changed C files
        entry: tools/codeformat.py -v -c -f
        language: python
      - id: verifygitlog
        name: MicroPython git commit message format checker
        entry: tools/verifygitlog.py --check-file --ignore-rebase
        language: python
        verbose: true
        stages: [commit-msg]
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.1.3
    hooks:
      - id: ruff
      - id: ruff-format
