"""
This type stub file was generated by pyright.
"""

import sys
from driver.fpc1020a.fpc1020a import FPC1020A
from typing import Literal

if sys.platform != "esp32":
    ...
class FingerHat(FPC1020A):
    def __init__(self, id: Literal[0, 1, 2] = ..., port: list | tuple = ...) -> None:
        ...
    


