"""
This type stub file was generated by pyright.
"""

class JoyCHat:
    def __init__(self, i2c, address: int | list | tuple = ...) -> None:
        ...
    
    def get_x_raw(self, channel: int = ...): # -> int:
        ...
    
    def get_y_raw(self, channel: int = ...): # -> int:
        ...
    
    def get_x(self, channel: int = ...): # -> int:
        ...
    
    def get_y(self, channel: int = ...): # -> int:
        ...
    
    def swap_x(self, swap: bool = ...): # -> None:
        ...
    
    def swap_y(self, swap: bool = ...): # -> None:
        ...
    
    def get_button_status(self, channel: int = ...): # -> bool:
        ...
    
    def fill_color(self, rgb: int = ...) -> None:
        ...
    


