"""
This type stub file was generated by pyright.
"""

class JoystickHat:
    def __init__(self, i2c, address: int | list | tuple = ...) -> None:
        ...
    
    def get_x_raw(self): # -> int:
        ...
    
    def get_y_raw(self): # -> int:
        ...
    
    def get_x(self): # -> Any:
        ...
    
    def get_y(self): # -> Any:
        ...
    
    def swap_x(self, swap: bool = ...): # -> None:
        ...
    
    def swap_y(self, swap: bool = ...): # -> None:
        ...
    
    def get_button_status(self): # -> bool:
        ...
    


