"""
This type stub file was generated by pyright.
"""

from machine import I2C

class YUNHat:
    def __init__(self, i2c: I2C, address: int | list | tuple = ...) -> None:
        ...
    
    def set_all_rgb_led(self, rgb): # -> None:
        ...
    
    def set_rgb_led(self, pos, rgb): # -> None:
        ...
    
    @property
    def get_light_brightness(self): # -> Any:
        ...
    
    @property
    def get_bmp280_temperature(self): # -> float:
        ...
    
    @property
    def get_sht20_temperature(self): # -> float:
        ...
    
    @property
    def get_pressure(self): # -> float:
        ...
    
    @property
    def get_humidity(self): # -> float:
        ...
    


