"""
This type stub file was generated by pyright.
"""

class AttitudeEstimator:
    def __init__(self) -> None:
        ...
    
    def calibrate_gyro(self, read_gyro_func, sample_count=..., delay=...): # -> None:
        ...
    
    def update_attitude(self, gx, gy, gz, ax, ay, az, dt): # -> None:
        """
        Update attitude angles (fusing accelerometer and gyroscope data)

        :param gx: Gyroscope X-axis angular velocity (°/s)
        :param gy: Gyroscope Y-axis angular velocity (°/s)
        :param gz: Gyroscope Z-axis angular velocity (°/s)
        :param ax: Accelerometer X-axis acceleration (m/s²)
        :param ay: Accelerometer Y-axis acceleration (m/s²)
        :param az: Accelerometer Z-axis acceleration (m/s²)
        :param dt: Sampling time interval (seconds)
        """
        ...
    
    def get_angles(self): # -> tuple[float | Any, float | Any, float | Any]:
        ...
    


