"""
This type stub file was generated by pyright.
"""

class PIDController:
    def __init__(self, kp, ki, kd, setpoint, direction) -> None:
        ...
    
    def compute(self, input_value): # -> int:
        ...
    
    def set_output_limits(self, min_out, max_out): # -> None:
        ...
    
    def set_integral_limits(self, min_out, max_out): # -> None:
        ...
    
    def set_direction(self, direction): # -> None:
        ...
    
    def set_params(self, kp, ki, kd): # -> None:
        ...
    
    def set_setpoint(self, setpoint): # -> None:
        ...
    


