# SPDX-FileCopyrightText: 2024 M5Stack Technology CO LTD
#
# SPDX-License-Identifier: MIT

set(IDF_TARGET esp32c5)

# stampc5 https://github.com/m5stack/m5stack-board-id/blob/main/board.csv
set(BOARD_ID 153)
set(MICROPY_PY_LVGL 0)

# Font Support
set(FONT_MONTSERRAT_12 1)
set(FONT_MONTSERRAT_14 1)
set(FONT_MONTSERRAT_16 1)
set(FONT_MONTSERRAT_18 1)
set(FONT_MONTSERRAT_20 0)
set(FONT_MONTSERRAT_22 0)
set(FONT_MONTSERRAT_24 1)
set(FONT_MONTSERRAT_30 0)
set(FONT_MONTSERRAT_36 0)
set(FONT_MONTSERRAT_40 1)
set(FONT_MONTSERRAT_44 1)
set(FONT_MONTSERRAT_48 1)
set(FONT_ALIBABAPUHUITI_CN24 0)
set(FONT_ALIBABASANS_JA24 0)
set(FONT_ALIBABASANS_KR24 0)

set(SDKCONFIG_DEFAULTS
    boards/sdkconfig.base
    ${SDKCONFIG_IDF_VERSION_SPECIFIC}
    boards/sdkconfig.flash_4mb_stampc5
    boards/sdkconfig.c5
    boards/sdkconfig.ble
    boards/sdkconfig.freertos
    boards/M5STACK_StampC5/sdkconfig.board
)

# If not enable LVGL, ignore this...
set(LV_CFLAGS
    -DLV_COLOR_DEPTH=16
    -DLV_COLOR_16_SWAP=0
    -DLV_FONT_MONTSERRAT_12=${FONT_MONTSERRAT_12}
    -DLV_FONT_MONTSERRAT_14=${FONT_MONTSERRAT_14}
    -DLV_FONT_MONTSERRAT_16=${FONT_MONTSERRAT_16}
    -DLV_FONT_MONTSERRAT_18=${FONT_MONTSERRAT_18}
    -DLV_FONT_MONTSERRAT_20=${FONT_MONTSERRAT_20}
    -DLV_FONT_MONTSERRAT_22=${FONT_MONTSERRAT_22}
    -DLV_FONT_MONTSERRAT_24=${FONT_MONTSERRAT_24}
    -DLV_FONT_MONTSERRAT_30=${FONT_MONTSERRAT_30}
    -DLV_FONT_MONTSERRAT_36=${FONT_MONTSERRAT_36}
    -DLV_FONT_MONTSERRAT_40=${FONT_MONTSERRAT_40}
    -DLV_FONT_MONTSERRAT_44=${FONT_MONTSERRAT_44}
    -DLV_FONT_MONTSERRAT_48=${FONT_MONTSERRAT_48}
    -DUSR_FONT_ALIBABAPUHUITI_CN24=${FONT_ALIBABAPUHUITI_CN24}
    -DUSR_FONT_ALIBABASANS_JA24=${FONT_ALIBABASANS_JA24}
    -DUSR_FONT_ALIBABASANS_KR24=${FONT_ALIBABASANS_KR24}
)

if(NOT MICROPY_FROZEN_MANIFEST)
    set(MICROPY_FROZEN_MANIFEST ${CMAKE_SOURCE_DIR}/boards/manifest.py)
endif()

set(TINY_FLAG 1)
