package(
    "hardware",
    (
        "__init__.py",
        "keyboard/__init__.py",
        "keyboard/asciimap.py",
        "button.py",
        "ir.py",
        "rfid.py",
        "rgb.py",
        "rotary.py",
        "sdcard.py",
    ),
    base_path="..",
    opt=0,
)
