"""
This type stub file was generated by pyright.
"""

def converter(data, type): # -> bytes | bytearray | str | None:
    ...

def extract_text(text, beg, end) -> str | bytes | bytearray:
    ...

def extract_int(text, start_str, end_str) -> int | None:
    ...

def extract_list(text, start_str, end_str) -> list:
    ...

def measure_time(func): # -> Callable[..., Any]:
    ...

