"""
This type stub file was generated by pyright.
"""

from machine import I2C

ADDRESS = ...
MODE_CONTIN = ...
MODE_SINGLE = ...
SPS_240 = ...
SPS_60 = ...
SPS_30 = ...
SPS_15 = ...
SPS_MASK = ...
GAIN_ONE = ...
GAIN_TWO = ...
GAIN_FOUR = ...
GAIN_EIGHT = ...
GAIN_MASK = ...
NO_EFFECT = ...
START = ...
class ADS1110:
    """
    note:
        en: EXT.IO2 is an IO extended unit, based on STM32F030 main controller, using I2C communication interface and providing 8 IO expansion. Each IO supports independent configuration of digital I/O, ADC, SERVO control, RGB LED control modes. Supports configuration of device I2C address, which means that users can mount multiple EXT.IO2 UNITs on the same I2C BUS to extend more IO resources. Suitable for multiple digital/analog signal acquisition, with lighting/servo control applications.

    details:
        link: https://docs.m5stack.com/en/unit/extio2
        image: https://static-cdn.m5stack.com/resource/docs/products/unit/extio2/extio2_01.webp
        category: Unit

    example:
        - ../../../examples/unit/extio2/extio2_core2_example.py

    m5f2:
        - unit/extio2/extio2_core2_example.m5f2
    """
    def __init__(self, i2c: I2C, address: int = ...) -> None:
        """
        note:
            en: Initialize the ADS1110 with the given I2C interface and address.

        params:
            i2c:
                note: The I2C interface used for communication.
            address:
                note: The I2C address of the ADS1110. Default is ADDRESS.
        """
        ...
    
    def set_gain(self, gain): # -> None:
        """
        note:
            en: Set the gain configuration for the ADC.

        params:
            gain:
                note: The gain value to configure.
        """
        ...
    
    def set_sample_rate(self, rate): # -> None:
        """
        note:
            en: Configure the ADC's sampling rate.

        params:
            rate:
                note: The sample rate to set.
        """
        ...
    
    def set_mode(self, mode): # -> None:
        """
        note:
            en: Set the ADC's operating mode.

        params:
            mode:
                note: The mode to configure, e.g., continuous or single conversion.
        """
        ...
    
    def start_single_conversion(self): # -> None:
        """
        note:
            en: Trigger a single conversion on the ADC.
        """
        ...
    
    def set_config(self): # -> None:
        """
        note:
            en: Update the ADC configuration register with the current settings.

        params:
            note:

        """
        ...
    
    def get_adc_raw_value(self): # -> Any:
        """
        note:
            en: Read the raw ADC value.

        params:
            note:

        returns:
            note: The raw ADC value as an integer.
        """
        ...
    


