"""
This type stub file was generated by pyright.
"""

"""
This type stub file was generated by pyright.
"""
AT_RESPONED_OK = ...
AT_RESPONED_ERROR = ...
AT_RECV_OK = ...
class LoRaWAN_Asr650x:
    """Create an LoRaWAN object.

    :param machine.UART uart: The UART object.
    :param bool debug: Whether to enable debug mode.

    MicroPython Code Block:

        .. code-block:: python

            from driver.asr650x import LoRaWAN_Asr650x

            lora = LoRaWAN_Asr650x(uart)
    """
    def __init__(self, uart, debug=...) -> None:
        ...
    
    def get_product_serial_number(self):
        """
        AT+CGSN?
        """
        ...
    
    def reset_module_to_default(self):
        """
        Reset module to default config.
        Parameter:
            None
        Return:
            True
            False
        """
        ...
    
    def get_device_address(self):
        ...
    
    def get_DevAddr(self):
        """
        Get Device address.
        Parameter:
            None
        Return:
            DevAddr: xxxxxxxx  4 bytes
        """
        ...
    
    def set_device_address(self, devaddr):
        ...
    
    def set_DevAddr(self, devaddr):
        """
        Set Device address.
        Parameter:
            devaddr: xx:xx:xx:xx  4 bytes
        Return:
            True
            False
        """
        ...
    
    def get_device_eui(self):
        ...
    
    def get_DevEui(self):
        """
        Get Device EUI.
        Parameter:
            None
        Return:
            DevEui: xxxxxxxxxxxxxxxx 8 byte
        """
        ...
    
    def set_device_eui(self, deveui):
        ...
    
    def set_DevEui(self, deveui):
        """
        Set Device EUI.
        Parameter:
            deveui: xxxxxxxxxxxxxxxx 8 bytes
        Return:
            True
            False
        """
        ...
    
    def get_app_eui(self):
        ...
    
    def get_AppEui(self):
        """
        Get Application EUI.
        Parameter:
            None
        Return:
            AppEui: xxxxxxxxxxxxxxxx 8 bytes
        """
        ...
    
    def set_app_eui(self, appeui):
        ...
    
    def set_AppEui(self, appeui):
        """
        Set Application EUI.
        Parameter:
            appeui: xxxxxxxxxxxxxxxx 8 bytes
        Return:
            True
            False
        """
        ...
    
    def get_appkey(self):
        ...
    
    def get_AppKey(self):
        """
        get App Key.
        Parameter:
            None
        Return:
            key: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx 16 bytes
            False
        """
        ...
    
    def set_appkey(self, key):
        ...
    
    def set_AppKey(self, key):
        """
        Set App Key.
        Parameter:
            None
        Return:
            key: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx 16 bytes
            False
        """
        ...
    
    def get_app_session_key(self):
        ...
    
    def get_APPSKEY(self):
        """
        Set App Session Key.
        Parameter:
            AppSKEY: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx 16 bytes
        Return:
            True
            False
        """
        ...
    
    def set_app_session_key(self, AppSKEY):
        ...
    
    def set_APPSKEY(self, AppSKEY):
        """
        Set App Session Key.
        Parameter:
            AppSKEY: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx 16 bytes
        Return:
            True
            False
        """
        ...
    
    def get_nwk_session_key(self):
        ...
    
    def get_NWKSKEY(self):
        """
        Get Network Session Key.
        Parameter:
            None
        Return:
            NWKSKEY: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx 16 bytes
            False
        """
        ...
    
    def set_nwk_session_key(self, NWKSKEY):
        ...
    
    def set_NWKSKEY(self, NWKSKEY):
        """
        Set Network Session Key.
        Parameter:
            NWKSKEY: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx 16 bytes
        Return:
            True
            False
        """
        ...
    
    def get_join_mode(self):
        """
        Set LoRaWAN Mode.
        Parameter:
            None
        Return:
            True
            False
        """
        ...
    
    def set_join_mode(self, mode):
        """Set the LoRaWAN join mode.

        :param int mode: The LoRaWAN join mode.

        UiFlow2 Code Block:

            |set_join_mode.png|

        MicroPython Code Block:

            .. code-block:: python

                lora.set_join_mode(0)
        """
        ...
    
    def get_frequency_band_mask(self):
        """
        Get frequency band mask.
        Parameter:
            None
        Return:
            mask
        """
        ...
    
    def set_frequency_band_mask(self, mask):
        """Set the frequency band mask.

        :param str mask: The frequency band mask.

        MicroPython Code Block:

            .. code-block:: python

                lora.set_frequency_band_mask("0001")
        """
        ...
    
    def get_uplink_downlink_mode(self):
        """
        Get uplink and downlink mode.
        Parameter:
            None
        Return:
            mode:
                1 Same frequency mode
                2 Inter-frequency mode
        """
        ...
    
    def set_uplink_downlink_mode(self, mode):
        """Set the uplink and downlink frequency.

        :param int mode: The uplink and downlink frequency.

        MicroPython Code Block:

            .. code-block:: python

                lora.set_uplink_downlink_mode(1)
        """
        ...
    
    def get_work_mode(self):
        """
        Get model work mode.
        Parameter:
            None
        Return:
            mode
            False
        """
        ...
    
    def set_work_mode(self, mode):
        """
        Get model work mode.
        Parameter:
            mode
                only support 2
        Return:
            True
            False
        """
        ...
    
    def get_class_mode(self):
        """
        Get class mode.
        Parameter:
            None
        Return:
            class mode:
                0 classA
                1 classB
                2 classB
            False
        """
        ...
    
    def set_class_mode(self, class_mode, branch=..., para1=..., para2=..., para3=..., para4=...):
        """Set the class mode, if the class mode is 0, the branch, para1, para2, para3, para4 will be ignored.

        :param int class_mode: The class mode.
        :param int branch: The branch selection.
        :param int para1: Set the beacon frequency, unit is Hz.
        :param int para2: Set the beacon data rate.
        :param int para3: Set ping frequency, unit is Hz.
        :param int para4: Set ping data rate.

        MicroPython Code Block:

            .. code-block:: python

                lora.set_class_mode(0, 0, 0, 0, 0, 0)
        """
        ...
    
    def get_status(self):
        """
        Get status.
        Parameter:
            None
        Return:
            status:
                0
                1
                2
                3
                4
                5
                6
                7
                8
            False
        """
        ...
    
    def join(self, para1, para2=..., para3=..., para4=...):
        """Join the LoRaWAN network.

        :param int para1: 0 stop join, 1 start join.
        :param int para2: 0 close auto join, 1 open auto join.
        :param int para3: join interval, unit is second(7~255).
        :param int para4: join retry times(1~256).

        UiFlow2 Code Block:

            |join.png|

            |join_stop.png|

        MicroPython Code Block:

            .. code-block:: python

                lora.join(1, 1, 8, 1)

                lora.join(0)

        """
        ...
    
    def send_data(self, payload, confirm=..., nbtrials=...):
        """Send data payload to LoRaWAN gateway.

        :param str payload: The data to send.
        :param int confirm: The confirm mode.
        :param int nbtrials: The number of trials.

        UiFlow2 Code Block:

            |send_data.png|

        MicroPython Code Block:

            .. code-block:: python

                lora.send_data("Hello, World!", 1, 1)
        """
        ...
    
    def receive_data(self):
        """
        Receive downlink data if have.
        Parameter:
            None
        Return:
            data
            False
        """
        ...
    
    def set_uplink_confirm_mode(self, mode):
        """
        Set uplink confirmed mode, setting before send data.
        Parameter:
            mode:
                0 unconfirmed mode
                1 confirmed
        Return:
            True
            False
        """
        ...
    
    def set_uplink_app_port(self, port):
        """Set the uplink app port.

        :param int port: The uplink app port.

        UiFlow2 Code Block:

            |set_uplink_app_port.png|

        MicroPython Code Block:

            .. code-block:: python

                lora.set_uplink_app_port(1)
        """
        ...
    
    def set_datarate(self, rate):
        """
        Set datarate.
        Parameter:
            rate:
                0 SF12 BW125
                1 SF11 BW125
                2 SF10 BW125
                3 SF9  BW125
                4 SF8  BW125
                5 SF7  BW125
        Return:
            True
            False
        """
        ...
    
    def set_report_mode(self, mode, interval=...):
        """
        Set report mode and report interval.
        Parameter:
            mode:
                0
                1
            interval:  s
        Return:
            True
            False
        """
        ...
    
    def set_tx_power(self, power):
        """
        Set tx power dBm.
        Parameter:
            power:
                0 17dBm
                1 15dBm
                2 13dBm
                3 11dBm
                4 9dBm
                5 7dBm
                6 5dBm
                7 3dBm
        Return:
            True
            False
        """
        ...
    
    def enable_adaptive_datarate(self, status):
        """
        Set adaptive datarate status.
        Parameter:
            status:
                0 disable
                1 enable
        Return:
            True
            False
        """
        ...
    
    def set_rx_window_param(self, rx1_offset, rx2_dr, rx2_freq):
        """Set the receive window parameter.

        :param int rx1_offset: The RX1 offset.
        :param int rx2_dr: The RX2 data rate.
        :param int rx2_freq: The RX2 frequency.

        MicroPython Code Block:

            .. code-block:: python

                lora.set_rx_window_param(0, 0, 868100000)
        """
        ...
    
    def set_rx1_delay_time(self, delay):
        """
        Set receive window param.
        Parameter:
            delay
        Return:
            True
            False
        """
        ...
    


class LoRaWAN_470(LoRaWAN_Asr650x):
    """Create an LoRaWAN object.

    :param int tx: The UART TX pin number.
    :param int rx: The UART RX pin number.
    :param bool debug: Whether to enable debug mode.

    MicroPython Code Block:

        .. code-block:: python

            from driver.asr650x import LoRaWAN_470

            lora = LoRaWAN_470(tx=17, rx=16)
    """
    def __init__(self, uart, debug=...) -> None:
        ...
    
    def config_abp(self, devaddr, appskey, nwkskey):
        """Config the ABP join mode information.

        :param str devaddr: The device address.
        :param str appskey: The application session key.
        :param str nwkskey: The network session key.

        UiFlow2 Code Block:

            |config_abp.png|

        MicroPython Code Block:

            .. code-block:: python

                lora.config_abp("0037CAE1FC3542B9", "70B3D57ED003B699", "67FA4ED1075A20573BCDD7594C458698")
        """
        ...
    
    def config_ABP(self, devaddr, appskey, nwkskey):
        """
        Config the ABP join mode information.
        Parameter:
        Return:
            None
        """
        ...
    
    def get_abp_config(self):
        """Get the ABP join mode information.

        :returns: The ABP join mode information(devaddr, appskey, newskey).
        :rtype: tuple

        UiFlow2 Code Block:

            |get_abp_config.png|

        MicroPython Code Block:

            .. code-block:: python

                lora.get_abp_config()
        """
        ...
    
    def get_ABP_config(self):
        """
        Get the ABP join mode information.
        Parameter:
            self
        Return:
            (devaddr, appskey, newskey)
        """
        ...
    
    def config_otaa(self, deveui, appeui, appkey):
        """Config the OTAA join mode information.

        :param str deveui: The device EUI.
        :param str appeui: The application EUI.
        :param str appkey: The application key.

        UiFlow2 Code Block:

            |config_otaa.png|

        MicroPython Code Block:

            .. code-block:: python

                lora.config_otaa("0037CAE1FC3542B9", "70B3D57ED003B699", "67FA4ED1075A20573BCDD7594C458698")
        """
        ...
    
    def config_OTAA(self, deveui, appeui, appkey):
        """
        Config the OTAA join mode information.
        Parameter:

        Return:
            True
            False
        """
        ...
    
    def get_otaa_config(self):
        """Get the OTAA join mode information.

        :returns: The OTAA join mode information(deveui, appeui, appkey).
        :rtype: tuple

        UiFlow2 Code Block:

            |get_otaa_config.png|

        MicroPython Code Block:

            .. code-block:: python

                lora.get_otaa_config()
        """
        ...
    
    def get_OTAA_config(self):
        """
        Get the OTAA join mode information.
        Parameter:
        Return:
            (deveui, appeui, appkey)
        """
        ...
    
    def check_join_status(self):
        """Check the LoRaWAN network join status.

        :returns: The LoRaWAN network join status.
        :rtype: bool

        UiFlow2 Code Block:

            |check_join_status.png|

        MicroPython Code Block:

            .. code-block:: python

                lora.check_join_status()
        """
        ...
    
    def check_uplink_status(self):
        """Check the data uplink status.

        :returns: The data uplink status.
        :rtype: bool

        UiFlow2 Code Block:

            |check_uplink_status.png|

        MicroPython Code Block:

            .. code-block:: python

                lora.check_uplink_status()
        """
        ...
    
    def check_downlink_data(self, timeout=...):
        """Check downlink data, if have downlink data, return the message.

        :param int timeout: The timeout time.
        :returns: False if no downlink data, otherwise return the downlink data.
        :rtype: bool | str

        UiFlow2 Code Block:

            |check_downlink_data.png|

        MicroPython Code Block:

            .. code-block:: python

                lora.check_downlink_data()
        """
        ...
    


class LoRaWAN_915(LoRaWAN_470):
    def __init__(self, uart, debug=...) -> None:
        """
        Parameter:

        Return:
            True
            False
        """
        ...
    


class LoRaWAN_868(LoRaWAN_470):
    def __init__(self, uart, debug=...) -> None:
        """
        Parameter:

        Return:
            True
            False
        """
        ...
    


