"""
This type stub file was generated by pyright.
"""

import sys
from typing import Literal

if sys.platform != "esp32":
    ...
timTh = ...
class ATGM336H:
    """
    Create an ATGM336H object.

    :param int id: The UART ID for communication with the GPS module. It can be 1, or 2.
    :param int tx: The TX pin is the pin that sends data to the GPS module.
    :param int rx: The RX pin is the pin that receives data from the GPS module.
    :param int pps: The PPS pin is the pin that receives the PPS signal from the GPS module.
    :param bool verbose: Whether to print verbose output.

    MicroPython Code Block:

        .. code-block:: python

            from driver.atgm336h import ATGM336H

            gps_0 = ATGM336H(id=2, tx=5, rx=6)
    """
    def __init__(self, id: Literal[0, 1, 2], tx: int, rx: int, pps=..., rst=..., verbose=...) -> None:
        ...
    
    def set_work_mode(self, mode: int): # -> None:
        """
        Set the working mode of the GPS module.

        :param int mode: The mode to set, defined by the GPS module.

        UiFlow2 Code Block:

            |set_work_mode.png|

        MicroPython Code Block:

            .. code-block:: python

                gps_0.set_work_mode(7)
        """
        ...
    
    def get_work_mode(self): # -> int:
        """
        Get the current working mode of the GPS module.

        :returns: The current working mode of the GPS module.
        :rtype: int

        UiFlow2 Code Block:

            |get_work_mode.png|

        MicroPython Code Block:

            .. code-block:: python

                gps_0.get_work_mode()
        """
        ...
    
    def get_antenna_state(self) -> str:
        """
        Get the state of the antenna.

        :returns: The antenna state.
        :rtype: str

        MicroPython Code Block:

            .. code-block:: python

                gps_0.get_antenna_state()
        """
        ...
    
    def get_gps_time(self): # -> list[str] | list[Any]:
        """
        Get the current GPS time.

        :returns: The GPS time as a list of strings [hour, minute, second].
        :rtype: list[str]

        UiFlow2 Code Block:

            |get_gps_time.png|

        MicroPython Code Block:

            .. code-block:: python

                gps_0.get_gps_time()
        """
        ...
    
    def get_gps_date(self): # -> list[str] | list[int]:
        """
        Get the current GPS date.

        :returns: The GPS date as a list of strings [day, month, year].
        :rtype: list[str]

        UiFlow2 Code Block:

            |get_gps_date.png|

        MicroPython Code Block:

            .. code-block:: python

                gps_0.get_gps_date()
        """
        ...
    
    def get_gps_date_time(self): # -> list[str] | list[int]:
        """
        Get the current GPS date and time combined.

        :returns: The GPS date and time as a list of strings [year, month, day, hour, minute, second].
        :rtype: list[str]

        UiFlow2 Code Block:

            |get_gps_date_time.png|

        MicroPython Code Block:

            .. code-block:: python

                gps_0.get_gps_date_time()
        """
        ...
    
    def get_timestamp(self) -> int | float:
        """
        Get the timestamp of the current GPS time.

        :returns: The timestamp representing the current GPS time.
        :rtype: int | float

        UiFlow2 Code Block:

            |get_timestamp.png|

        MicroPython Code Block:

            .. code-block:: python

                gps_0.get_timestamp()
        """
        ...
    
    def get_latitude(self): # -> str | float:
        """
        Get the current latitude.

        :returns: The current latitude in string format.
        :rtype: str

        UiFlow2 Code Block:

            |get_latitude.png|

        MicroPython Code Block:

            .. code-block:: python

                gps_0.get_latitude()
        """
        ...
    
    def get_longitude(self): # -> str | float:
        """
        Get the current longitude.

        :returns: The current longitude in string format.
        :rtype: str

        UiFlow2 Code Block:

            |get_longitude.png|

        MicroPython Code Block:

            .. code-block:: python

                gps_0.get_longitude()
        """
        ...
    
    def get_altitude(self): # -> str:
        """
        Get the current altitude.

        :returns: The current altitude in string format.
        :rtype: str

        UiFlow2 Code Block:

            |get_altitude.png|

        MicroPython Code Block:

            .. code-block:: python

                gps_0.get_altitude()
        """
        ...
    
    def get_satellite_num(self): # -> str:
        """
        Get the number of satellites used for positioning.

        :returns: The number of satellites.
        :rtype: str

        UiFlow2 Code Block:

            |get_satellite_num.png|

        MicroPython Code Block:

            .. code-block:: python

                gps_0.get_satellite_num()
        """
        ...
    
    def get_pos_quality(self): # -> str:
        """
        Get the quality of the GPS position.

        :returns: The position quality indicator.
        :rtype: str

        UiFlow2 Code Block:

            |get_pos_quality.png|

        MicroPython Code Block:

            .. code-block:: python

                gps_0.get_pos_quality()
        """
        ...
    
    def get_corse_over_ground(self) -> str:
        ...
    
    def get_course_over_ground(self) -> str:
        """
        Get the course over ground (COG).

        :returns: The course over ground in degrees.
        :rtype: str

        UiFlow2 Code Block:

            |get_course_over_ground.png|

        MicroPython Code Block:

            .. code-block:: python

                gps_0.get_course_over_ground()
        """
        ...
    
    def get_speed_over_ground(self) -> str:
        """
        Get the speed over ground (SOG).

        :returns: The speed over ground in knots.
        :rtype: str

        UiFlow2 Code Block:

            |get_speed_over_ground.png|

        MicroPython Code Block:

            .. code-block:: python

                gps_0.get_speed_over_ground()
        """
        ...
    
    def set_time_zone(self, value): # -> None:
        """
        Set the time zone offset for the GPS time.

        :param int value: The time zone offset value to set.

        UiFlow2 Code Block:

            |set_time_zone.png|

        MicroPython Code Block:

            .. code-block:: python

                gps_0.set_time_zone(1)
        """
        ...
    
    def get_time_zone(self): # -> int:
        """
        Get the current time zone offset.

        :returns: The current time zone offset.
        :rtype: int

        UiFlow2 Code Block:

            |get_time_zone.png|

        MicroPython Code Block:

            .. code-block:: python

                gps_0.get_time_zone()
        """
        ...
    
    def deinit(self): # -> None:
        """
        Deinitialize the GPS unit, stopping any running tasks and releasing resources.

        UiFlow2 Code Block:

            |deinit.png|

        MicroPython Code Block:

            .. code-block:: python

                gps_0.deinit()
        """
        ...
    


