"""
This type stub file was generated by pyright.
"""

"""
I2C-based driver for the DHT12 temperature and humidity sensor.
"""
_DHT12_I2C_DEFAULT_ADDR = ...
_DHT12_I2C_DATA_LEN = ...
class DHT12:
    def __init__(self, i2c, addr=...) -> None:
        ...
    
    def measure(self): # -> tuple[Any, Any]:
        """
        Returns the temperature (in °C) and humidity (in %)  as a 2-tuple in the
        form of:

        (temperature, humidity)
        """
        ...
    


