"""
This type stub file was generated by pyright.
"""

import sys
from typing import Literal

if sys.platform != "esp32":
    ...
class DMX512:
    """! DMX512 communication unit.
    @en DMX Unit is a communication unit specifically designed for DMX-512 data transmission scenarios. It integrates the CA-IS3092W isolated half-duplex RS-485 transceiver, providing up to 5kVrms electrical isolation protection.
    @cn DMX Unit 是一款专为 DMX-512 数据传输场景设计的通信单元。

    @color #0FEA97
    @link https://docs.m5stack.com/en/unit/UNIT-DMX
    @image https://static-cdn.m5stack.com/resource/docs/products/unit/DMX/heart_01.webp
    @category unit
    """
    DMX_MASTER = ...
    DMX_SLAVE = ...
    def __init__(self, id: Literal[0, 1, 2] = ..., port: list | tuple = ..., mode: int = ..., en: int = ...) -> None:
        """! Initializes the DMX512 unit with a specified UART ID and port pins.

        @param id UART device ID.
        @param port UART TX and RX pins.
        @param mode Operating mode (1 for Master, 2 for Slave).
        """
        ...
    
    def dmx_init(self, mode=...) -> None:
        """! Initializes the DMX512 communication with the specified UART pins and mode.

        @param mode Operating mode (1 for Master, 2 for Slave).
        """
        ...
    
    def write_data(self, channel, data) -> None:
        """! Updates the data for a specified DMX channel. Data is sent on the next update cycle.

        @param channel DMX channel number (1-512).
        @param data Data value to be sent (0-255).
        @raises ValueError if the channel number is out of range.
        """
        ...
    
    def read_data(self, channel) -> int:
        """! Reads data from a specified DMX channel in Slave mode.

        @param channel DMX channel number (1-512).
        @return Data value received from the DMX channel.
        @raises ValueError if the channel number is out of range.
        """
        ...
    
    def clear_buffer(self) -> None:
        """! Clears the DMX buffer and resets the data."""
        ...
    
    def deinit(self) -> None:
        """! Deinitializes the DMX512 unit and stops any ongoing operations."""
        ...
    
    def receive_none_block(self) -> None:
        """! Starts non-blocking data reception for the specified channels with associated callbacks."""
        ...
    
    def stop_receive(self) -> None:
        """! Stops the non-blocking data reception task."""
        ...
    
    def attach_channel(self, channel, callback) -> None:
        """! Attaches a callback function to a specified DMX channel.

        @param channel DMX channel number (1-512) to attach the callback to.
        @param callback The function to be called when data changes on the specified channel.
        """
        ...
    
    def detach_channel(self, channel): # -> None:
        """! Detaches the callback function from a specified DMX channel.

        @param channel DMX channel number (1-512) to detach the callback from.
        """
        ...
    


