"""
This type stub file was generated by pyright.
"""

class Haptic:
    """A simple haptic feedback motor driver module.
    Control the motor through pwm and timer to simulate the effect of haptic feedback.

    :param Pin pin: pin is the entity on which the PWM is output, which is usually a machine.Pin object
    :param int freq: Frequency of PWM output
    """
    _timer = ...
    def __init__(self, pin, freq: int = ...) -> None:
        ...
    
    def once(self, freq=..., duty=..., duration: int = ...) -> None:
        """Play the haptic effect once on the motor.
        :param int duration: The duration of the haptic effect, in milliseconds.
        """
        ...
    
    def set_freq(self, freq): # -> None:
        ...
    
    def set_duty(self, duty): # -> None:
        ...
    
    def turn_off(self): # -> None:
        ...
    
    def deinit(self) -> None:
        """Disabled Haptic Driver."""
        ...
    


