"""
This type stub file was generated by pyright.
"""

from machine import I2C

_MCP4725_DEFAULT_ADDRESS = ...
_MCP4725_WRITE_FAST_MODE = ...
_MCP4725_WRITE_DAC_EEPROM = ...
class MCP4725:
    """
    MCP4725 12-bit digital to analog converter.  This class has a similar
    interface as the CircuitPython AnalogOut class and can be used in place
    of that module.

    :param machine.I2C i2c: The I2C bus.
    :param int address: The address of the device if set differently from the default.
    """
    _BUFFER = ...
    def __init__(self, i2c: I2C, address: int = ..., vdd: float = ..., vout: float = ...) -> None:
        ...
    
    def get_value(self) -> int:
        """
        The DAC value as a 16-bit unsigned value compatible with the
        :py:class:`~analogio.AnalogOut` class.

        Note that the MCP4725 is still just a 12-bit device so quantization will occur.  If you'd
        like to instead deal with the raw 12-bit value use the ``raw_value`` property, or the
        ``normalized_value`` property to deal with a 0...1 float value.
        """
        ...
    
    def set_value(self, val: int) -> None:
        ...
    
    def get_voltage(self) -> float:
        ...
    
    def set_voltage(self, val: float) -> None:
        ...
    
    def get_raw_value(self) -> int:
        """The DAC value as a 12-bit unsigned value.  This is the the true resolution of the DAC
        and will never peform scaling or run into quantization error.
        """
        ...
    
    def set_raw_value(self, val: int) -> None:
        ...
    
    def get_normalized_value(self) -> float:
        """The DAC value as a floating point number in the range 0.0 to 1.0."""
        ...
    
    def set_normalized_value(self, val: float) -> None:
        ...
    
    def save_to_eeprom(self) -> None:
        """Store the current DAC value in EEPROM."""
        ...
    


