"""
This type stub file was generated by pyright.
"""

class PCA9685:
    def __init__(self, i2c, address=...) -> None:
        ...
    
    def reset(self): # -> None:
        """
        note:
            en: Reset the Servo Driver.
            cn: 重置舵机驱动器。
        """
        ...
    
    def freq(self, freq=...): # -> int | None:
        """
        note:
            en: Set the PWM frequency.
            cn: 设置PWM频率。

        params:
            freq:
              note: The PWM frequency in Hz.
        """
        ...
    
    def pwm(self, index, on=..., off=...): # -> None:
        """
        note:
            en: Set the PWM value.
            cn: 设置PWM值。

        params:
            index:
              note: The channel index.
            on:
              note: The ON time.
            off:
              note: The OFF time.

        """
        ...
    
    def duty(self, index, value=..., invert=...): # -> None:
        """
        note:
            en: Set the PWM duty cycle.
            cn: 设置PWM占空比。

        params:
            index:
              note: The channel index.
            value:
              note: The PWM value.
            invert:
              note: Invert the PWM value.
        """
        ...
    


class Servos:
    def __init__(self, i2c, address=..., freq=..., min_us=..., max_us=..., degrees=...) -> None:
        """
        note:
            en: Create a Servo instance.
            cn: 创建一个舵机实例。

        params:
            i2c:
              note: The I2C bus.
            address:
              note: The I2C address.
            freq:
              note: The PWM frequency in Hz.
            min_us:
              note: The minimum pulse width in microseconds.
            max_us:
              note: The maximum pulse width in microseconds.
            degrees:
              note: The maximum angle in degrees.

        """
        ...
    
    def position(self, index, degrees=..., radians=..., us=..., duty=...): # -> None:
        """
        note:
            en: Set the servo position.
            cn: 设置舵机位置。

        params:
            index:
              note: The channel index.
            degrees:
              note: The angle in degrees.
            radians:
              note: The angle in radians.
            us:
              note: The pulse width in microseconds.
            duty:
              note: The duty cycle in percent.
        """
        ...
    
    def release(self, index): # -> None:
        """
        note:
            en: Release the servo.
            cn: 释放舵机。

        params:
            index:
              note: The channel index.
        """
        ...
    


