"""
This type stub file was generated by pyright.
"""

from machine import I2C
from typing_extensions import Literal

_REGISTER_INPUT = ...
_REGISTER_OUTPUT = ...
_REGISTER_POLARITY_INVERSION = ...
_REGISTER_CONFIG = ...
_PCA9554_DEFAULT_ADDRESS = ...
class Pin:
    IN = ...
    OUT = ...
    def __init__(self, port, id, mode: int = ..., value=...) -> None:
        """! Initialize the Pin object with specified parameters.

        @param port: The port object controlling the pin.
        @param id: The pin identifier (e.g., GPIO number).
        @param mode: The mode of the pin, either `Pin.IN` (default) or `Pin.OUT`.
        @param value: Optional initial value for the pin, 0 or 1.
        """
        ...
    
    def init(self, mode: int = ..., value=...): # -> None:
        """! Reinitialize the pin with a new mode or value.

        @param mode: New mode for the pin, `Pin.IN` or `Pin.OUT`.
        @param value: New value for the pin, 0 or 1.
        """
        ...
    
    def value(self, *args): # -> None:
        """! Get or set the digital value of the pin.

        If no arguments are passed, the method returns the current value of the pin.
        If one argument is passed, it sets the pin to the specified value.

        @param args: Optional argument to set the pin value.
        @return: The current pin value when called without arguments; None when setting a value.
        """
        ...
    
    def __call__(self, *args): # -> None:
        """! Shortcut to get or set the pin value.

        This method allows `Pin()` to behave like `Pin.value()`.

        @param args: Optional argument to set the pin value.
        @return: The current pin value when called without arguments; None when setting a value.
        """
        ...
    
    def on(self): # -> None:
        """! Set the pin to a high state (1)."""
        ...
    
    def off(self): # -> None:
        """! Set the pin to a low state (0)."""
        ...
    


class PCA9554:
    """! EXT.IO is a GPIO Expander. With simple I2C commands it's possible to extend the GPIO pins for up to 8 extra GPIOs.
    The EXT.IO Integrates the PCA9554PW chipset. This 8-bit I/O expander for the two-line bi-directional-bus (I2C) is designed for 2.3-V to 5.5-V VCC with Open-Drain Active-Low Interrupt Output operation.

    @en Unit EXT.IO 英文介绍
    @cn Unit EXT.IO 中文介绍

    @color #0FE6D7
    @link https://docs.m5stack.com/en/unit/extio
    @image https://static-cdn.m5stack.com/resource/docs/products/unit/extio/extio_01.webp
    @category unit

    @example

    """
    IN = ...
    OUT = ...
    def __init__(self, i2c: I2C, address: int = ...) -> None:
        """! Initialize the PCA9554 device.

        @param i2c: An instance of the I2C bus to communicate with the device.
        @param address: The I2C address of the PCA9554 device (default is _PCA9554_DEFAULT_ADDRESS).
        """
        ...
    
    def set_port_mode(self, mode: Literal[0, 1]) -> None:
        """! Set the mode of the entire port.

        @param mode: The mode to set, either PCA9554.IN (input, 0x00) or PCA9554.OUT (output, 0x01).
        """
        ...
    
    def set_pin_mode(self, id: int, mode: Literal[0, 1]) -> None:
        """! Set the mode of a specific pin.

        @param id: The pin number (0-7).
        @param mode: The mode to set, either PCA9554.IN (input, 0x00) or PCA9554.OUT (output, 0x01).
        """
        ...
    
    def digit_write_port(self, value: int) -> None:
        """! Set a value to the entire port.

        @param value: An 8-bit value to set to the port.
        """
        ...
    
    def digit_write(self, id: int, value: int) -> None:
        """! Set a value to a specific pin.

        @param id: The pin number (0-7).
        @param value: The value to set, either 0 (low) or 1 (high).
        """
        ...
    
    def digit_read_port(self) -> int:
        """! Read the value from the entire port.

        @return: An 8-bit value representing the state of the port.
        """
        ...
    
    def digit_read(self, id: int) -> int:
        """! Read the value from a specific pin.

        @param id: The pin number (0-7).
        @return: The value of the pin, either 0 (low) or 1 (high).
        """
        ...
    
    def pin(self, id: int, mode: int = ..., value=...) -> Pin:
        """! Provide a MicroPython-style interface for handling GPIO pins.

        @param id: The GPIO pin number to configure and control.
        @param mode: The pin mode, either `IN` (input) or `OUT` (output). Defaults to `IN`.
        @param value: The initial value to set for the pin if in `OUT` mode. Use `None` for no initial value.
        @return: A `Pin` object for further pin operations such as reading or writing values.
        """
        ...
    


