"""
This type stub file was generated by pyright.
"""

import sys
from typing import List, Literal, Tuple

if sys.platform != "esp32":
    ...
MIDI_CMD_NOTE_OFF = ...
MIDI_CMD_NOTE_ON = ...
MIDI_CMD_POLYPHONIC_AFTERTOUCH = ...
MIDI_CMD_CONTROL_CHANGE = ...
MIDI_CMD_PROGRAM_CHANGE = ...
MIDI_CMD_CHANNEL_AFTERTOUCH = ...
MIDI_CMD_PITCH_BEND = ...
MIDI_CMD_SYSTEM_EXCLUSIVE = ...
MIDI_CMD_TIME_CODE = ...
MIDI_CMD_SONG_POSITION = ...
MIDI_CMD_SONG_SELECT = ...
MIDI_CMD_TUNE_REQUEST = ...
MIDI_CMD_END_OF_SYSEX = ...
MIDI_CMD_TIMING_CLOCK = ...
MIDI_CMD_START = ...
MIDI_CMD_CONTINUE = ...
MIDI_CMD_STOP = ...
MIDI_CMD_ACTIVE_SENSING = ...
MIDI_CMD_SYSTEM_RESET = ...
DRUM_SET = ...
class SAM2695:
    """! UNIT MIDI is a Slide Potentiometer with color indicator.


    @en UNIT MIDI 英文介绍

    @color #0FE6D7
    @link https://docs.m5stack.com/en/unit/midi
    @image https://static-cdn.m5stack.com/resource/docs/products/unit/midi/midi_01.webp
    @category unit

    @example

    """
    def __init__(self, id: Literal[0, 1, 2] = ..., port: List[int] | Tuple[int, int] = ...) -> None:
        """! Initializes the MIDI unit with a specified UART ID and port pins.
        The UART interface is used to transmit MIDI messages.

        @param id UART device ID.
        @param port UART TX and RX pins.
        """
        ...
    
    def set_note_on(self, channel, pitch, velocity) -> None:
        """! Sends a MIDI Note On message to the specified channel.

        @param channel MIDI channel (0-15).
        @param pitch Note pitch (0-127).
        @param velocity Note velocity (0-127).
        """
        ...
    
    def set_note_off(self, channel, pitch) -> None:
        """! Sends a MIDI Note Off message to the specified channel.

        @param channel MIDI channel (0-15).
        @param pitch Note pitch (0-127).
        """
        ...
    
    def set_instrument(self, bank, channel, value) -> None:
        """! Changes the program (instrument) on the specified channel.

        @param bank Bank selector (MSB) for the program change.
        @param channel MIDI channel (0-15).
        @param value Program number (0-127).
        """
        ...
    
    def set_drums_instrument(self, drum_pitch, velocity) -> None:
        """! Sets a drum instrument and plays a note on MIDI channel 10.

        @param drum_pitch Drum pitch number.
        @param velocity Note velocity (0-127).
        """
        ...
    
    def set_pitch_bend(self, channel, value) -> None:
        """! Sends a MIDI Pitch Bend message to the specified channel.

        @param channel MIDI channel (0-15).
        @param value Pitch bend value (0-16383).
        """
        ...
    
    def set_pitch_bend_range(self, channel, value) -> None:
        """! Sets the pitch bend range on the specified channel.

        @param channel MIDI channel (0-15).
        @param value Pitch bend range in semitones.
        """
        ...
    
    def midi_reset(self) -> None:
        """! Sends a MIDI System Exclusive Reset command."""
        ...
    
    def set_channel_volume(self, channel, level) -> None:
        """! Sets the channel volume for the specified channel.

        @param channel MIDI channel (0-15).
        @param level Volume level (0-127).
        """
        ...
    
    def set_all_notes_off(self, channel) -> None:
        """! Sends a MIDI Control Change message to turn off all notes on the specified channel.

        @param channel MIDI channel (0-15).
        """
        ...
    
    def set_master_volume(self, level) -> None:
        """! Sets the master volume using a standard System Exclusive message.

        @param level Volume level (0-127).
        """
        ...
    
    def set_reverb(self, channel, program, level, delayfeedback) -> None:
        """! Configures reverb effect on the specified channel.

        @param channel MIDI channel (0-15).
        @param program Reverb program number (0-7).
        @param level Reverb level (0-127).
        @param delayfeedback Delay feedback amount (0-127).
        """
        ...
    
    def set_chorus(self, channel, program, level, feedback, chorusdelay) -> None:
        """! Configures chorus effect on the specified channel.

        @param channel MIDI channel (0-15).
        @param program Chorus program number (0-7).
        @param level Chorus level (0-127).
        @param feedback Chorus feedback amount (0-127).
        @param chorusdelay Chorus delay amount (0-127).
        """
        ...
    
    def set_pan(self, channel, value) -> None:
        """! Sets the pan position for the specified channel.

        @param channel MIDI channel (0-15).
        @param value Pan position (0-127).
        """
        ...
    
    def set_equalizer(self, channel, lowband, medlowband, medhighband, highband, lowfreq, medlowfreq, medhighfreq, highfreq) -> None:
        """! Sets the equalizer levels and frequencies for the specified channel.

        @param channel MIDI channel (0-15).
        @param lowband Low band level (-12dB to +12dB).
        @param medlowband Mid-low band level (-12dB to +12dB).
        @param medhighband Mid-high band level (-12dB to +12dB).
        @param highband High band level (-12dB to +12dB).
        @param lowfreq Low band frequency (Hz).
        @param medlowfreq Mid-low band frequency (Hz).
        @param medhighfreq Mid-high band frequency (Hz).
        @param highfreq High band frequency (Hz).
        """
        ...
    
    def set_tuning(self, channel, fine, coarse) -> None:
        """! Sets the tuning for the specified channel.

        @param channel MIDI channel (0-15).
        @param fine Fine tuning value (cents).
        @param coarse Coarse tuning value (semitones).
        """
        ...
    
    def set_vibrate(self, channel, rate, depth, delay) -> None:
        """! Sets the vibrato effect parameters on the specified channel.


        @param channel The MIDI channel to apply the vibrato effect to (0-15).
        @param rate The vibrato rate (0-127).
        @param depth The vibrato depth (0-127).
        @param delay The vibrato delay (0-127).
        """
        ...
    
    def set_tvf(self, channel, cutoff, resonance) -> None:
        """! Sets the parameters for a TVF (Tone-Voltage Filter) on the specified channel.


        @param channel The MIDI channel to apply the filter to (0-15).
        @param cutoff The filter cutoff frequency (0-127).
        @param resonance The filter resonance (0-127).
        """
        ...
    
    def set_envelope(self, channel, attack, decay, release) -> None:
        """! Sets the ADSR (Attack, Decay, Sustain, Release) envelope parameters on the specified channel.

        @param channel The MIDI channel to apply the envelope to (0-15).
        @param attack The attack time (0-127).
        @param decay The decay time (0-127).
        @param release The release time (0-127).
        """
        ...
    
    def set_scale_tuning(self, channel, v1, v2, v3, v4, v5, v6, v7, v8, v9, v10, v11, v12) -> None:
        """! Sets scale tuning for the specified channel.

        @param channel The MIDI channel to apply the scale tuning to (0-15).
        @param v1~v12 Tuning values for each note in the scale (0-127).
        """
        ...
    
    def set_mod_wheel(self, channel, pitch, tvtcutoff, amplitude, rate, pitchdepth, tvfdepth, tvadepth) -> None:
        """! Sets modulation wheel parameters that affect various effects on the specified channel.

        @param channel The MIDI channel to apply the modulation to (0-15).
        @param pitch Pitch modulation depth.
        @param tvtcutoff Cutoff frequency modulation depth.
        @param amplitude Amplitude modulation depth.
        @param rate Modulation rate.
        @param pitchdepth Depth of pitch modulation.
        @param tvfdepth Depth of TVF modulation.
        @param tvadepth Depth of TVA (Tone-Voltage Amplifier) modulation.
        """
        ...
    
    def set_all_drums(self) -> None:
        """! Sends a System Exclusive message to set all drums on channel 10 to default values."""
        ...
    
    def cmd_write(self, cmd) -> None:
        """! Writes a MIDI command to the UART interface.

        @param cmd List of MIDI command bytes.
        """
        ...
    
    def map(self, x, in_min, in_max, out_min, out_max) -> int:
        """! Maps a value from one range to another.

        @param x Value to map.
        @param in_min Minimum value of the input range.
        @param in_max Maximum value of the input range.
        @param out_min Minimum value of the output range.
        @param out_max Maximum value of the output range.
        @return Mapped value.
        """
        ...
    


