"""
This type stub file was generated by pyright.
"""

from machine import I2C

class SEN55:
    SEN55_I2C_ADDR = ...
    _SEN55_START_MEASUREMENT = ...
    _SEN55_START_MEASUREMENT_RHT_GAS_ONLY = ...
    _SEN55_STOP_MEASUREMENT = ...
    _SEN55_READ_DATA_READY_FLAG = ...
    _SEN55_READ_MEASURED_VALUES = ...
    _SEN55_TEMP_COMPENSATION_PARAMS = ...
    _SEN55_WARM_START_PARAMS = ...
    _SEN55_VOC_ALGORITHM_TUNING_PARAMS = ...
    _SEN55_NOX_ALGORITHM_TUNING_PARAMS = ...
    _SEN55_RHT_ACCELERATION_MODE = ...
    _SEN55_VOC_ALGORITHM_STATE = ...
    _SEN55_START_FAN_CLEANING = ...
    _SEN55_AUTO_CLEANING_INTERVAL = ...
    _SEN55_READ_PRODUCT_NAME = ...
    _SEN55_READ_SERIAL_NUMBER = ...
    _SEN55_READ_FIRMWARE_VERSION = ...
    _SEN55_READ_DEVICE_STATUS = ...
    _SEN55_CLEAR_DEVICE_STATUS = ...
    _SEN55_RESET = ...
    def __init__(self, i2c: I2C, address: int = ...) -> None:
        """
        note:
            en: Initialize the SEN55 sensor with I2C communication, setting the power control and ensuring the sensor is connected.

        params:
            i2c:
                note: The I2C object used for communication with the sensor.
            address:
                note: The I2C address of the sensor, default is 0x69.
        """
        ...
    
    def set_power_state(self, state: bool) -> None:
        """
        note:
            en: Set the power state of the SEN55 sensor.

        params:
            state:
                note: The desired power state, True to power on, False to power off.
        """
        ...
    
    def get_power_state(self) -> bool:
        """
        note:
            en: Get the current power state of the SEN55 sensor.

        params:
            note:

        returns:
            note: Returns True if the sensor is powered on, False if powered off.
        """
        ...
    
    def available(self) -> None:
        """
        note:
            en: Check if the SEN55 sensor is connected via I2C.

        params:
            note:

        raises:
            Exception: If the sensor is not found on the I2C bus.
        """
        ...
    
    def set_work_mode(self, mode: int) -> None:
        """
        note:
            en: Set the measurement mode of the SEN55 sensor.

        params:
            mode:
                note: 1 to start measurement, 0 to stop measurement.
        """
        ...
    
    def get_sensor_data(self) -> None:
        """
        note:
            en: Get the sensor data including PM1.0, PM2.5, PM4.0, PM10.0, CO2, temperature, humidity, VOC, and NOx.

        params:
            note:

        details:
            en: This method sends a command to the sensor, waits for a response, and unpacks the measured values into their respective attributes.
        """
        ...
    
    def get_data_ready_flag(self) -> bool:
        """
        note:
            en: Check if the sensor data is ready to be read.

        params:
            note:

        returns:
            note: Returns True if the data is ready, False otherwise.
        """
        ...
    
    def set_temp_cmp_params(self, temp_offset: int, temp_offset_slope: int, time_constant: int) -> None:
        """
        note:
            en: Set the temperature compensation parameters for the sensor.

        params:
            temp_offset:
                note: The temperature offset in the sensor's compensation algorithm.
            temp_offset_slope:
                note: The temperature offset slope in the sensor's compensation algorithm.
            time_constant:
                note: The time constant for the temperature compensation.
        """
        ...
    
    def get_temp_cmp_params(self) -> tuple:
        """
        note:
            en: Get the current temperature compensation parameters.

        params:
            note:

        returns:
            note: A tuple containing the temperature offset, offset slope, and time constant.
        """
        ...
    
    def set_warm_start_param(self, mode: bool) -> None:
        """
        note:
            en: Set the warm start parameter for the sensor.

        params:
            mode:
                note: True to enable warm start, False to disable it.
        """
        ...
    
    def get_warm_start_param(self) -> bool:
        """
        note:
            en: Get the current warm start parameter.

        params:
            note:

        returns:
            note: True if warm start is enabled, False if disabled.
        """
        ...
    
    def set_voc_algo_tuning_params(self, voc_index_offset: int = ..., voc_offset_hours: int = ..., voc_gain_houes: int = ..., gate_max_duration_min: int = ..., std_initial: int = ..., gain_factor: int = ...) -> None:
        """
        note:
            en: Set the VOC algorithm tuning parameters, including index offset, time offsets, and gain factors.

        params:
            voc_index_offset:
                note: The VOC index offset, default is 100.
            voc_offset_hours:
                note: The VOC offset in hours, default is 12 hours.
            voc_gain_houes:
                note: The VOC gain in hours, default is 12 hours.
            gate_max_duration_min:
                note: Maximum gate duration in minutes, default is 180 minutes.
            std_initial:
                note: The initial standard deviation, default is 50.
            gain_factor:
                note: The gain factor for VOC, default is 230.
        """
        ...
    
    def get_voc_algo_tuning_params(self) -> tuple:
        """
        note:
            en: Get the current VOC algorithm tuning parameters.

        params:
            note:

        return:
            note: A tuple of VOC tuning parameters: index offset, offset hours, gain hours, max gate duration, initial standard deviation, and gain factor.
        """
        ...
    
    def set_nox_algo_tuning_params(self, nox_index_offset: int = ..., nox_offset_hours: int = ..., nox_gain_houes: int = ..., gate_max_duration_min: int = ..., gain_factor: int = ...) -> None:
        """
        note:
            en: Set the NOx algorithm tuning parameters, including index offset, time offsets, and gain factors. The standard deviation estimate is fixed at 50 for NOx.

        params:
            nox_index_offset:
                note: The offset value for the NOx index.
            nox_offset_hours:
                note: The time offset in hours for the NOx algorithm.
            nox_gain_houes:
                note: The gain factor in hours for the NOx algorithm.
            gate_max_duration_min:
                note: The maximum gate duration in minutes.
            gain_factor:
                note: The gain factor for the NOx algorithm.
        """
        ...
    
    def get_nox_algo_tuning_params(self) -> tuple:
        """
        note:
            en: Get the current NOx algorithm tuning parameters.

        params:
            note:

        return:
            note: A tuple of NOx tuning parameters: index offset, offset hours, gain hours, max gate duration, and gain factor.
        """
        ...
    
    def set_rht_acceleration_mode(self, mode: int) -> None:
        """
        note:
            en: Set the RHT acceleration mode, which affects how quickly the device accelerates during measurement.

        params:
            mode:
                note: The acceleration mode to set: 0 for low, 1 for high, or 2 for medium.
        """
        ...
    
    def get_rht_acceleration_mode(self) -> int:
        """
        note:
            en: Get the current RHT acceleration mode. This parameter can be changed in any state of the device, but it is applied only the next time starting a measurement. The parameter needs to be set before a new measurement is started.

        params:
            note:

        return:
            note: The current acceleration mode: 0 for low, 1 for high, or 2 for medium.
        """
        ...
    
    def get_voc_algo_state(self) -> bytes:
        """
        note:
            en: Get the current VOC algorithm state.

        params:
            note:

        return:
            note: The VOC algorithm state in bytes.
        """
        ...
    
    def set_voc_algo_state(self, state: bytes) -> None:
        """
        note:
            en: Set the VOC algorithm state.

        params:
            state:
                note: The VOC algorithm state to set, represented as bytes.
        """
        ...
    
    def set_start_fan_cleaning(self) -> None:
        """
        note:
            en: Start the fan cleaning process to remove contaminants from the sensor.

        params:
            note:
        """
        ...
    
    def get_auto_cleaning_interval(self) -> tuple:
        """
        note:
            en: Get the current auto cleaning interval.

        params:
            note:

        return:
            note: A tuple of the cleaning interval parameters.
        """
        ...
    
    def set_auto_cleaning_interval(self, interval: tuple) -> None:
        """
        note:
            en: Set the auto cleaning interval.

        params:
            interval:
                note: A tuple representing the new auto cleaning interval.
        """
        ...
    
    def get_device_status(self) -> bytes:
        """
        note:
            en: Get the current device status.

        params:
            note:

        return:
            note: The device status in bytes.
        """
        ...
    
    def clear_device_status(self) -> None:
        """
        note:
            en: Clear the device status, resetting any error flags or states.

        params:
            note:
        """
        ...
    
    def get_serial_number(self) -> str:
        """
        note:
            en: Get the unique serial number of the sensor.

        params:
            note:

        return:
            note: The serial number of the sensor as a string.
        """
        ...
    
    def get_product_name(self) -> str:
        """
        note:
            en: Get the product name of the sensor.

        params:
            note:

        return:
            note: The product name of the sensor as a string.
        """
        ...
    
    def send_cmd(self, cmd: int, value=..., is_bytes: bool = ...) -> None:
        """
        note:
            en: Send a command to the sensor.

        params:
            cmd:
                note: The command to send, represented as a 2-byte value.
            value:
                note: Optional value to include with the command.
            is_bytes:
                note: A flag to indicate if the value is in bytes format.
        """
        ...
    
    def read_response(self, nbytes: int) -> bytes:
        """
        note:
            en: Read the response from the sensor.

        params:
            nbytes:
                note: The number of bytes to read from the sensor.

        return:
            note: The response data as bytes.
        """
        ...
    
    def check_crc(self, buf: bytes) -> bytes:
        """
        note:
            en: Check the CRC of the sensor data to ensure its validity.

        params:
            buf:
                note: The buffer containing sensor data.

        return:
            note: The valid data after CRC check.
        """
        ...
    
    def crc8(self, buffer: bytes) -> int:
        """
        note:
            en: Calculate the CRC-8 checksum for the given buffer.

        params:
            buffer:
                note: The buffer to calculate the checksum for.

        return:
            note: The 8-bit CRC checksum.
        """
        ...
    
    def get_pm1_0(self) -> float:
        """
        note:
            en: Get the PM1.0 concentration value in micrograms per cubic meter (µg/m³).

        params:
            note:

        returns:
            float: PM1.0 concentration in µg/m³.
        """
        ...
    
    def get_pm2_5(self) -> float:
        """
        note:
            en: Get the PM2.5 concentration value in micrograms per cubic meter (µg/m³).

        params:
            note:

        returns:
            float: PM2.5 concentration in µg/m³.
        """
        ...
    
    def get_pm4_0(self) -> float:
        """
        note:
            en: Get the PM4.0 concentration value in micrograms per cubic meter (µg/m³).

        params:
            note:

        returns:
            float: PM4.0 concentration in µg/m³.
        """
        ...
    
    def get_pm10_0(self) -> float:
        """
        note:
            en: Get the PM10.0 concentration value in micrograms per cubic meter (µg/m³).

        params:
            note:

        returns:
            float: PM10.0 concentration in µg/m³.
        """
        ...
    
    def get_humidity(self) -> float:
        """
        note:
            en: Get the humidity value in percentage (%).

        params:
            note:

        returns:
            float: Humidity in percentage.
        """
        ...
    
    def get_temperature(self) -> float:
        """
        note:
            en: Get the temperature value in degrees Celsius (°C).

        params:
            note:

        returns:
            float: Temperature in °C.
        """
        ...
    
    def get_voc(self) -> float:
        """
        note:
            en: Get the Volatile Organic Compound (VOC) concentration value in parts per billion (ppb).

        params:
            note:

        returns:
            float: VOC concentration in ppb.
        """
        ...
    
    def get_nox(self) -> float:
        """
        note:
            en: Get the Nitrogen Oxide (NOx) concentration value in parts per billion (ppb).

        params:
            note:

        returns:
            float: NOx concentration in ppb.
        """
        ...
    


