"""
This type stub file was generated by pyright.
"""

"""
I2C-based driver for the SGP30 Sensirion air[VoC] quality sensor.
"""
SGP30_DEFAULT_I2C_ADDR = ...
SGP30_WORD_LEN = ...
SGP30_CRC8_POLYNOMIAL = ...
SGP30_CRC8_INIT = ...
SGP30_CRC8_FINAL_XOR = ...
SGP30_MEASURE_TEST_PASS = ...
SGP30_CMD_IAQ_INIT_HEX = ...
SGP30_CMD_IAQ_INIT_WORDS = ...
SGP30_CMD_IAQ_INIT_MAX_MS = ...
SGP30_CMD_MEASURE_IAQ_HEX = ...
SGP30_CMD_MEASURE_IAQ_WORDS = ...
SGP30_CMD_MEASURE_IAQ_MS = ...
SGP30_CMD_GET_IAQ_BASELINE_HEX = ...
SGP30_CMD_GET_IAQ_BASELINE_WORDS = ...
SGP30_CMD_GET_IAQ_BASELINE_MAX_MS = ...
SGP30_CMD_SET_IAQ_BASELINE_HEX = ...
SGP30_CMD_SET_IAQ_BASELINE_WORDS = ...
SGP30_CMD_SET_IAQ_BASELINE_MAX_MS = ...
SGP30_CMD_SET_ABSOLUTE_HUMIDITY_HEX = ...
SGP30_CMD_SET_ABSOLUTE_HUMIDITY_WORDS = ...
SGP30_CMD_SET_ABSOLUTE_HUMIDITY_MAX_MS = ...
SGP30_CMD_MEASURE_TEST_HEX = ...
SGP30_CMD_MEASURE_TEST_WORDS = ...
SGP30_CMD_MEASURE_TEST_MAX_MS = ...
SGP30_CMD_GET_FEATURE_SET_HEX = ...
SGP30_CMD_GET_FEATURE_SET_WORDS = ...
SGP30_CMD_GET_FEATURE_SET_MAX_MS = ...
SGP30_CMD_MEASURE_RAW_HEX = ...
SGP30_CMD_MEASURE_RAW_WORDS = ...
SGP30_CMD_MEASURE_RAW_MAX_MS = ...
SGP30_CMD_GET_TVOC_INCEPTIVE_HEX = ...
SGP30_CMD_GET_TVOC_INCEPTIVE_WORDS = ...
SGP30_CMD_GET_TVOC_INCEPTIVE_MAX_MS = ...
SGP30_CMD_SET_TVOC_BASELINE_HEX = ...
SGP30_CMD_SET_TVOC_BASELINE_WORDS = ...
SGP30_CMD_SET_TVOC_BASELINE_MAX_MS = ...
SGP30_CMD_GET_SERIAL_ID_HEX = ...
SGP30_CMD_GET_SERIAL_ID_WORDS = ...
SGP30_CMD_GET_SERIAL_ID_MAX_MS = ...
class SGP30:
    """
    A driver for the SGP30 gas sensor.

    :param i2c: The "I2C" object to use. This is the only required parameter.
    :param int address: (optional) The I2C address of the device.
    :param boolean measure_test: (optional) Whether to run on-chip test during initialisation.
    :param boolean iaq_init: (optional) Whether to initialise SGP30 algorithm / baseline.
    """
    def __init__(self, i2c, addr=..., measure_test=..., iaq_init=...) -> None:
        """Initialises the sensor and display stats"""
        ...
    
    def iaq_init(self): # -> None:
        """
        note:
            en: Initialize the IAQ (Indoor Air Quality) algorithm for the sensor.

        params:
            note:
        """
        ...
    
    def measure_iaq(self): # -> list[Any] | None:
        """
        note:
            en: Measure the CO2 equivalent (CO2eq) and TVOC values.

        params:
            note:

        returns:
            note: A tuple containing CO2eq and TVOC values.
        """
        ...
    
    def get_iaq_baseline(self): # -> list[Any] | None:
        """
        note:
            en: Retrieve the IAQ algorithm baseline values for CO2eq and TVOC.

        params:
            note:

        returns:
            note: A tuple containing baseline values for CO2eq and TVOC.
        """
        ...
    
    def set_iaq_baseline(self, co2eq, tvoc): # -> None:
        """
        note:
            en: Set the previously recorded IAQ algorithm baseline values for CO2eq and TVOC.

        params:
            co2eq:
                note: The CO2 equivalent baseline value.
            tvoc:
                note: The TVOC baseline value.
        """
        ...
    
    def set_absolute_humidity(self, absolute_humidity): # -> None:
        """
        note:
            en: Set the absolute humidity compensation for the sensor. To disable, set the value to 0.

        params:
            absolute_humidity:
                note: The absolute humidity value to set.
        """
        ...
    
    def measure_test(self):
        """
        note:
            en: Run the on-chip self-test.

        params:
            note:

        returns:
            note: The result of the self-test.
        """
        ...
    
    def get_feature_set(self):
        """
        note:
            en: Retrieve the feature set of the sensor.

        params:
            note:

        returns:
            note: The feature set value.
        """
        ...
    
    def measure_raw(self): # -> list[Any] | None:
        """
        note:
            en: Return raw H2 and Ethanol signals for part verification and testing.

        params:
            note:

        returns:
            note: A tuple containing raw H2 and Ethanol signals.
        """
        ...
    
    def get_serial(self): # -> str:
        """
        note:
            en: Retrieve the sensor serial ID.

        params:
            note:

        returns:
            note: The serial ID as a hexadecimal string.
        """
        ...
    
    def co2eq(self):
        """
        note:
            en: Retrieve the Carbon Dioxide Equivalent (CO2eq) in parts per million (ppm).

        params:
            note:

        returns:
            note: The CO2eq value in ppm.
        """
        ...
    
    def baseline_co2eq(self):
        """
        note:
            en: Retrieve the baseline value for CO2eq.

        params:
            note:

        returns:
            note: The baseline CO2eq value.
        """
        ...
    
    def tvoc(self):
        """
        note:
            en: Retrieve the Total Volatile Organic Compound (TVOC) in parts per billion (ppb).

        params:
            note:

        returns:
            note: The TVOC value in ppb.
        """
        ...
    
    def baseline_tvoc(self):
        """
        note:
            en: Retrieve the baseline value for TVOC.

        params:
            note:

        returns:
            note: The baseline TVOC value.
        """
        ...
    
    def raw_h2(self):
        """
        note:
            en: Retrieve the raw H2 signal value.

        params:
            note:

        returns:
            note: The raw H2 signal value.
        """
        ...
    
    def raw_ethanol(self):
        """
        note:
            en: Retrieve the raw Ethanol signal value.

        params:
            note:

        returns:
            note: The raw Ethanol signal value.
        """
        ...
    
    def convert_r_to_a_humidity(self, temp_c, r_humidity_perc, fixed_point=...): # -> int:
        """
        note:
            en: Convert relative humidity to absolute humidity based on the sensor's equation.

        params:
            temp_c:
                note: The ambient temperature in Celsius (°C).
            r_humidity_perc:
                note: The relative humidity in percentage (%).
            fixed_point:
                note: Whether to return the value in 8.8 fixed-point format. Defaults to True.

        returns:
            note: The absolute humidity value, either in g/m³ or fixed-point format.
        """
        ...
    


def generate_crc(data):
    """
    note:
        en: Calculate an 8-bit CRC checksum based on the sensor's specified algorithm.

    params:
        data:
            note: The data array for which to calculate the CRC checksum.

    returns:
        note: The calculated 8-bit CRC checksum.
    """
    ...

