"""
This type stub file was generated by pyright.
"""

"""
`sht20`
================================================================================

MicroPython Driver for the Sensirion SHT20 Temperature Sensor


* Author(s): Jose D. Montoya


"""
__version__ = ...
__repo__ = ...
_SOFTRESET = ...
_TEMPERATURE = ...
_HUMIDITY = ...
_READ_USER1 = ...
_WRITE_USER1 = ...
_TEMP_RH_RES = ...
class SHT20:
    """Driver for the SHT20 Sensor connected over I2C.

    :param ~machine.I2C i2c: The I2C bus the SHT20 is connected to.
    :param int address: The I2C device address. Defaults to :const:`0x40`

    :raises RuntimeError: if the sensor is not found

    **Quickstart: Importing and using the device**

    Here is an example of using the :class:`SHT20` class.
    First you will need to import the libraries to use the sensor

    .. code-block:: python

        from machine import Pin, I2C
        from micropython_sht20 import sht20

    Once this is done you can define your `machine.I2C` object and define your sensor object

    .. code-block:: python

        i2c = I2C(1, sda=Pin(2), scl=Pin(3))
        sht20 = sht20.SHT20(i2c)

    Now you have access to the attributes

    .. code-block:: python

        temperature = sht20.temperature
        humidity = sht20.humidity

    """
    def __init__(self, i2c, address: int = ...) -> None:
        ...
    
    def reset(self) -> None:
        """Perform a soft reset of the sensor, resetting all settings to their power-on defaults"""
        ...
    
    @property
    def temperature(self) -> float:
        """The measured temperature in Celsius."""
        ...
    
    @property
    def humidity(self) -> float:
        """The measured relative humidity in percent."""
        ...
    
    @property
    def temp_rh_resolution(self) -> str:
        """The temperature and relative humidity resolution

        Have one of the following values: [#f1]_

            =======  ==============  ==============
             value       RH res %        T res C
            =======  ==============  ==============
               0      0.04 (12bit)    0.01 (14bit)
               1      0.7  (8bit)     0.04 (12bit)
               2      0.17 (10bit)    0.02 (13bit)
               3      0.08 (11bit)    0.08 (11bit)
            =======  ==============  ==============


        .. [#f1] HTU21D(F) RH/T Sensor IC Datasheet. TE connectivity. 2017. p13

        """
        ...
    
    @temp_rh_resolution.setter
    def temp_rh_resolution(self, val: int) -> None:
        ...
    


