"""
This type stub file was generated by pyright.
"""

__version__ = ...
__author__ = ...
__license__ = ...
DEFAULT_I2C_ADDRESS = ...
class SHT30:
    """
    SHT30 sensor driver in pure python based on I2C bus

    References:
    * https://www.sensirion.com/fileadmin/user_upload/customers/sensirion/Dokumente/2_Humidity_Sensors/Sensirion_Humidity_Sensors_SHT3x_Datasheet_digital.pdf  # NOQA
    * https://www.wemos.cc/sites/default/files/2016-11/SHT30-DIS_datasheet.pdf
    * https://github.com/wemos/WEMOS_SHT3x_Arduino_Library
    * https://www.sensirion.com/fileadmin/user_upload/customers/sensirion/Dokumente/11_Sample_Codes_Software/Humidity_Sensors/Sensirion_Humidity_Sensors_SHT3x_Sample_Code_V2.pdf
    """
    POLYNOMIAL = ...
    ALERT_PENDING_MASK = ...
    HEATER_MASK = ...
    RH_ALERT_MASK = ...
    T_ALERT_MASK = ...
    RESET_MASK = ...
    CMD_STATUS_MASK = ...
    WRITE_STATUS_MASK = ...
    MEASURE_CMD = ...
    STATUS_CMD = ...
    RESET_CMD = ...
    CLEAR_STATUS_CMD = ...
    ENABLE_HEATER_CMD = ...
    DISABLE_HEATER_CMD = ...
    def __init__(self, i2c=..., delta_temp=..., delta_hum=..., i2c_address=...) -> None:
        ...
    
    def is_present(self): # -> bool:
        """
        Return true if the sensor is correctly conneced, False otherwise
        """
        ...
    
    def set_delta(self, delta_temp=..., delta_hum=...): # -> None:
        """
        Apply a delta value on the future measurements of temperature and/or humidity
        The units are Celsius for temperature and percent for humidity (can be negative values)
        """
        ...
    
    def send_cmd(self, cmd_request, response_size=..., read_delay_ms=...): # -> None:
        """
        Send a command to the sensor and read (optionally) the response
        The responsed data is validated by CRC
        """
        ...
    
    def clear_status(self): # -> None:
        """
        Clear the status register
        """
        ...
    
    def reset(self): # -> None:
        """
        Send a soft-reset to the sensor
        """
        ...
    
    def status(self, raw=...): # -> None:
        """
        Get the sensor status register.
        It returns a int value or the bytearray(3) if raw==True
        """
        ...
    
    def measure(self, raw=...): # -> tuple[Any, Any] | None:
        """
        If raw==True returns a bytearrya(6) with sensor direct measurement otherwise
        It gets the temperature (T) and humidity (RH) measurement and return them.

        The units are Celsius and percent
        """
        ...
    
    def measure_int(self, raw=...): # -> tuple[Any, Any, Any, Any] | None:
        """
        Get the temperature (T) and humidity (RH) measurement using integers.
        If raw==True returns a bytearrya(6) with sensor direct measurement otherwise
        It returns a tuple with 4 values: T integer, T decimal, H integer, H decimal
        For instance to return T=24.0512 and RH= 34.662 This method will return
        (24, 5, 34, 66) Only 2 decimal digits are returned, .05 becomes 5
        Delta values are not applied in this method
        The units are Celsius and percent.
        """
        ...
    


class SHT30Error(Exception):
    """
    Custom exception for errors on sensor management
    """
    BUS_ERROR = ...
    DATA_ERROR = ...
    CRC_ERROR = ...
    def __init__(self, error_code=...) -> None:
        ...
    
    def get_message(self): # -> Literal['Bus error', 'Data error', 'CRC error', 'Unknown error']:
        ...
    


