"""
This type stub file was generated by pyright.
"""

from typing import Tuple

_SHT4X_DEFAULT_ADDR = ...
_SHT4X_READSERIAL = ...
_SHT4X_SOFTRESET = ...
class CV:
    """struct helper"""
    @classmethod
    def add_values(cls, value_tuples: Tuple[str, int, str, float]) -> None:
        """Add CV values to the class"""
        ...
    
    @classmethod
    def is_valid(cls, value: int) -> bool:
        """Validate that a given value is a member"""
        ...
    


class Mode(CV):
    """Options for ``power_mode``"""
    ...


class SHT4x:
    """
    SHT4x sensor driver in pure python based on I2C bus

    References:
    * https://sensirion.com/media/documents/33FD6951/63E1087C/Datasheet_SHT4x_1.pdf
    * https://github.com/adafruit/Adafruit_CircuitPython_SHT4x/blob/main/adafruit_sht4x.py
    """
    def __init__(self, i2c, address: int = ...) -> None:
        ...
    
    @property
    def serial_number(self) -> int:
        """The unique 32-bit serial number"""
        ...
    
    def reset(self) -> None:
        """Perform a soft reset of the sensor, resetting all settings to their power-on defaults"""
        ...
    
    @property
    def mode(self) -> int:
        """The current sensor reading mode (heater and precision)"""
        ...
    
    @mode.setter
    def mode(self, new_mode: int) -> None:
        ...
    
    @property
    def relative_humidity(self) -> float:
        """The current relative humidity in % rH. This is a value from 0-100%."""
        ...
    
    @property
    def temperature(self) -> float:
        """The current temperature in degrees Celsius"""
        ...
    
    def measure(self) -> Tuple[float, float]:
        """both `temperature` and `relative_humidity`, read simultaneously"""
        ...
    


