"""
This type stub file was generated by pyright.
"""

from machine import I2C

_REGISTER_ENABLE = ...
_REGISTER_ATIME = ...
_REGISTER_WTIME = ...
_REGISTER_AILT = ...
_REGISTER_AILTH = ...
_REGISTER_AIHT = ...
_REGISTER_AIHTH = ...
_REGISTER_APERS = ...
_REGISTER_CONFIG = ...
_REGISTER_CONTROL = ...
_REGISTER_SENSORID = ...
_REGISTER_STATUS = ...
_REGISTER_CDATA = ...
_REGISTER_CDATAH = ...
_REGISTER_RDATA = ...
_REGISTER_RDATAH = ...
_REGISTER_GDATA = ...
_REGISTER_GDATAH = ...
_REGISTER_BDATA = ...
_REGISTER_BDATAH = ...
_COMMAND_BIT = ...
_ENABLE_AIEN = ...
_ENABLE_WEN = ...
_ENABLE_AEN = ...
_ENABLE_PON = ...
_GAINS = ...
_CYCLES = ...
_INTEGRATION_TIME_THRESHOLD_LOW = ...
_INTEGRATION_TIME_THRESHOLD_HIGH = ...
_TCS3472_DEFAULT_ADDR = ...
class TCS3472:
    """! COLOR is color recognition unit integrated with TCS3472 chipset. As the name says, COLOR is able to detect color value and return RGB data as response.

    @en Unit Color 英文介绍
    @cn Unit Color 中文介绍

    @color #0FE6D7
    @link https://docs.m5stack.com/en/unit/COLOR
    @image https://static-cdn.m5stack.com/resource/docs/products/unit/COLOR/img-5e8f77b1-0a2d-4810-8b8d-c2374bd738fb.webp
    @category unit

    @example

    """
    def __init__(self, i2c: I2C, address: int = ...) -> None:
        """! Initialize TCS3472 sensor with the given I2C interface and address.

        @param i2c: The I2C bus instance for communication.
        @param address: The I2C address of the sensor, default is _TCS3472_DEFAULT_ADDR.
        """
        ...
    
    def get_lux(self) -> float:
        """! Get the lux value computed from the color channels.

        @return: The computed lux value as a float.
        """
        ...
    
    def get_color_temperature(self) -> float:
        """! Get the color temperature in degrees Kelvin.

        @return: The color temperature as a float in Kelvin.
        """
        ...
    
    def get_color_rgb_bytes(self) -> tuple[int, int, int]:
        """! Get the RGB color detected by the sensor.

        @return: A tuple of red, green, and blue component values as bytes (0-255).
        """
        ...
    
    def get_color_r(self) -> int:
        """! Get the red component of the RGB color.

        @return: The red component value (0-255).
        """
        ...
    
    def get_color_g(self) -> int:
        """! Get the green component of the RGB color.

        @return: The green component value (0-255).
        """
        ...
    
    def get_color_b(self) -> int:
        """! Get the blue component of the RGB color.

        @return: The blue component value (0-255).
        """
        ...
    
    def get_color_h(self) -> int:
        """! Get the hue (H) value of the color in degrees.

        @return: The hue value as an integer in the range [0, 360].
        """
        ...
    
    def get_color_s(self) -> float:
        """! Get the saturation (S) value of the color.

        @return: The saturation value as a float in the range [0, 1].
        """
        ...
    
    def get_color_v(self) -> float:
        """! Get the value (V) of the color (brightness).

        @return: The value as a float in the range [0, 1].
        """
        ...
    
    def get_color(self) -> int:
        """! Get the RGB color as an integer value.
        Examples: Red = 16711680 (0xff0000), Green = 65280 (0x00ff00),
        Blue = 255 (0x0000ff), SlateGray = 7372944 (0x708090)
        @return: An integer representing the RGB color, with 8 bits per channel.
        """
        ...
    
    def get_color565(self) -> int:
        """! Get the RGB color in 5-6-5 format as an integer.

        @return: An integer representing the RGB color in 5-6-5 format.
        """
        ...
    
    def get_active(self) -> bool:
        """! Get the active state of the sensor.

        @return: True if the sensor is active, False if it is inactive.
        """
        ...
    
    def set_active(self, val: bool) -> None:
        """! Set the active state of the sensor.

        @param val: True to activate the sensor, False to deactivate it.
        """
        ...
    
    def get_integration_time(self) -> float:
        """! Get the integration time of the sensor in milliseconds.

        @return: The integration time as a float.
        """
        ...
    
    def set_integration_time(self, val: float) -> None:
        """! Set the integration time of the sensor.

        @param val: The desired integration time in milliseconds.
        @raise ValueError: If the integration time is out of the allowed range.
        """
        ...
    
    def get_gain(self) -> int:
        """! Get the gain of the sensor.

        @return: The gain value, which should be one of 1, 4, 16, or 60.
        """
        ...
    
    def set_gain(self, val: int) -> None:
        """! Set the gain of the sensor.

        @param val: The desired gain value (1, 4, 16, or 60).
        @raise ValueError: If the gain is not one of the allowed values.
        """
        ...
    
    def read_interrupt(self) -> bool:
        """! Read the interrupt status.

        @return: True if the interrupt is set, False otherwise.
        """
        ...
    
    def clear_interrupt(self) -> None:
        """! Clear the interrupt status of the sensor by writing to the interrupt register."""
        ...
    
    def get_color_raw(self): # -> tuple[int, ...]:
        """! Read the raw RGBC color detected by the sensor.

        @return: A tuple containing raw red, green, blue, and clear color data.
        """
        ...
    
    def get_cycles(self): # -> Literal[0, 1, 2, 3, 5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, -1]:
        """! Get the persistence cycles of the sensor.

        @return: The persistence cycles or -1 if interrupts are disabled.
        """
        ...
    
    def set_cycles(self, val: int) -> None:
        """! Set the persistence cycles for the sensor.

        @param val: The number of persistence cycles, or -1 to disable interrupts.
        @raise ValueError: If the value is not one of the permitted cycle values.
        """
        ...
    
    def get_min_value(self): # -> int:
        """! Get the minimum threshold value (AILT register) of the sensor.

        @return: The minimum threshold value.
        """
        ...
    
    def set_min_value(self, val: int): # -> None:
        """! Set the minimum threshold value (AILT register) of the sensor.

        @param val: The minimum threshold value to set.
        """
        ...
    
    def get_max_value(self): # -> int:
        """! Get the maximum threshold value (AIHT register) of the sensor.

        @return: The maximum threshold value.
        """
        ...
    
    def set_max_value(self, val: int): # -> None:
        """! Set the maximum threshold value (AIHT register) of the sensor.

        @param val: The maximum threshold value to set.
        """
        ...
    
    def get_glass_attenuation(self): # -> float | None:
        """! Get the Glass Attenuation factor used to compensate for lower light levels due to glass presence.

        @return: The glass attenuation factor (ga).
        """
        ...
    
    def set_glass_attenuation(self, value: float): # -> None:
        """! Set the Glass Attenuation factor used to compensate for lower light levels due to glass presence.

        @param value: The glass attenuation factor to set. Must be greater than or equal to 1.
        @raise ValueError: If the value is less than 1.
        """
        ...
    


