"""
This type stub file was generated by pyright.
"""

wlan_sta = ...
class TZONE:
    def __init__(self, zone=..., win=...) -> None:
        ...
    
    def getntp(self, host=...): # -> Any | Literal[0]:
        ...
    
    def sunday(self, year, month): # -> int | None:
        ...
    
    def adj_tzone(self, utc): # -> int:
        ...
    
    def setzone(self): # -> None:
        ...
    


