"""
This type stub file was generated by pyright.
"""

from machine import I2C

_VL53L1X_I2C_SLAVE_DEVICE_ADDRESS = ...
_VL53L1X_VHV_CONFIG__TIMEOUT_MACROP_LOOP_BOUND = ...
_GPIO_HV_MUX__CTRL = ...
_GPIO__TIO_HV_STATUS = ...
_PHASECAL_CONFIG__TIMEOUT_MACROP = ...
_RANGE_CONFIG__TIMEOUT_MACROP_A_HI = ...
_RANGE_CONFIG__VCSEL_PERIOD_A = ...
_RANGE_CONFIG__TIMEOUT_MACROP_B_HI = ...
_RANGE_CONFIG__VCSEL_PERIOD_B = ...
_RANGE_CONFIG__VALID_PHASE_HIGH = ...
_SD_CONFIG__WOI_SD0 = ...
_SD_CONFIG__INITIAL_PHASE_SD0 = ...
_SYSTEM__INTERRUPT_CLEAR = ...
_SYSTEM__MODE_START = ...
_VL53L1X_RESULT__RANGE_STATUS = ...
_VL53L1X_RESULT__FINAL_CROSSTALK_CORRECTED_RANGE_MM_SD0 = ...
_VL53L1X_IDENTIFICATION__MODEL_ID = ...
TB_SHORT_DIST = ...
TB_LONG_DIST = ...
class VL53L1X:
    """Create a VL53L1X object.

    :param I2C i2c: The I2C bus the ToF4M Unit is connected to.
    :param int address: The I2C address of the device. Default is 0x29.

    UiFlow2 Code Block:

        |init.png|

    MicroPython Code Block:

        .. code-block:: python

            from hardware import I2C
            from unit import TOFUnit

            i2c0 = I2C(0, scl=Pin(1), sda=Pin(2), freq=100000)
            tof_0 = TOFUnit(i2c0)
    """
    def __init__(self, i2c: I2C, address: int = ...) -> None:
        ...
    
    @property
    def get_model_info(self): # -> tuple[Any, Any, Any]:
        ...
    
    @property
    def get_distance(self): # -> Any | None:
        """The distance in units of millimeters.

        :returns: Distance in millimeters or None if measurement is invalid.
        :rtype: int or None

        UiFlow2 Code Block:

            |get_distance.png|

        MicroPython Code Block:

            .. code-block:: python

                distance = tof_0.get_distance
        """
        ...
    
    def set_continuous_start_measurement(self): # -> None:
        """Starts continuous measure operation.

        UiFlow2 Code Block:

            |set_continuous_start_measurement.png|

        MicroPython Code Block:

            .. code-block:: python

                tof_0.set_continuous_start_measurement()
        """
        ...
    
    def set_continuous_stop_measurement(self): # -> None:
        """Stops measure operation.

        UiFlow2 Code Block:

            |set_continuous_stop_measurement.png|

        MicroPython Code Block:

            .. code-block:: python

                tof_0.set_continuous_stop_measurement()
        """
        ...
    
    def clear_interrupt(self): # -> None:
        ...
    
    @property
    def get_data_ready(self): # -> bool:
        """Returns true if new data is ready, otherwise false.

        :returns: True if new data is ready.
        :rtype: bool

        UiFlow2 Code Block:

            |get_data_ready.png|

        MicroPython Code Block:

            .. code-block:: python

                if tof_0.get_data_ready:
                    distance = tof_0.get_distance
        """
        ...
    
    @property
    def get_measurement_timing_budget(self): # -> None:
        """Get measurement duration in milliseconds.

        :returns: The timing budget in milliseconds.
        :rtype: int

        UiFlow2 Code Block:

            |get_measurement_timing_budget.png|

        MicroPython Code Block:

            .. code-block:: python

                budget = tof_0.get_measurement_timing_budget
        """
        ...
    
    def set_measurement_timing_budget(self, val): # -> None:
        """Set the measurement timing budget in milliseconds.

        :param int val: Timing budget in milliseconds.

        UiFlow2 Code Block:

            |set_measurement_timing_budget.png|

        MicroPython Code Block:

            .. code-block:: python

                tof_0.set_measurement_timing_budget(100)
        """
        ...
    
    @property
    def get_distance_mode(self): # -> Literal[1, 2] | None:
        """Get the distance mode.

        :returns: distance mode(1=short, 2=long).
        :rtype: int

        UiFlow2 Code Block:

            |get_distance_mode.png|

        MicroPython Code Block:

            .. code-block:: python

                mode = tof_0.get_distance_mode
        """
        ...
    
    def set_distance_mode(self, mode): # -> None:
        """Set the distance mode.

        :param int mode: 1=short, 2=long.

        UiFlow2 Code Block:

            |set_distance_mode.png|

        MicroPython Code Block:

            .. code-block:: python

                tof_0.set_distance_mode(2)  # Long distance mode
        """
        ...
    
    def set_i2c_address(self, new_address): # -> None:
        """Set a new I2C address to the instantiated object.

        :param int new_address: The new I2C address.

        UiFlow2 Code Block:

            |set_i2c_address.png|

        MicroPython Code Block:

            .. code-block:: python

                tof_0.set_i2c_address(42)
        """
        ...
    


