"""
This type stub file was generated by pyright.
"""

def deserialize(data, schema): # -> tuple[list[Any], Any]:
    ...

def serialize(data, schema): # -> bytes:
    ...

class Bytes(bytes):
    def serialize(self): # -> Self:
        ...
    
    @classmethod
    def deserialize(cls, data): # -> tuple[Self, Literal[b""]]:
        ...
    


class int_t(int):
    _signed = ...
    _size = ...
    def serialize(self, byteorder=...): # -> bytes:
        ...
    
    @classmethod
    def deserialize(cls, data, byteorder=...): # -> tuple[Self, Any]:
        ...
    


class uint_t(int_t):
    _signed = ...


class uint8_t(uint_t):
    _size = ...


class uint16_t(uint_t):
    _size = ...


