"""
This type stub file was generated by pyright.
"""

class Parser:
    def __init__(self, data) -> None:
        ...
    
    @_logging
    def skipuntil(self, chr: bytearray | bytes) -> int:
        ...
    
    @_logging
    def parseint(self, chr=...) -> int:
        ...
    
    @_logging
    def parseutil(self, chr: str | bytearray | bytes): # -> Literal[b""]:
        ...
    
    def reset(self): # -> None:
        ...
    


