# SPDX-FileCopyrightText: 2026 M5Stack Technology CO LTD
#
# SPDX-License-Identifier: MIT

set(IDF_TARGET esp32p4)

# https://github.com/m5stack/m5stack-board-id/blob/main/board.csv#L29
set(BOARD_ID 148)
set(MICROPY_PY_LVGL 1)

# Font Support
set(FONT_MONTSERRAT_12 1)
set(FONT_MONTSERRAT_14 1)
set(FONT_MONTSERRAT_16 1)
set(FONT_MONTSERRAT_18 1)
set(FONT_MONTSERRAT_20 1)
set(FONT_MONTSERRAT_22 1)
set(FONT_MONTSERRAT_24 1)
set(FONT_MONTSERRAT_30 1)
set(FONT_MONTSERRAT_36 1)
set(FONT_MONTSERRAT_40 1)
set(FONT_MONTSERRAT_44 1)
set(FONT_MONTSERRAT_48 1)
set(FONT_ALIBABAPUHUITI_CN24 1)
set(FONT_ALIBABASANS_JA24 1)
set(FONT_ALIBABASANS_KR24 1)

set(SDKCONFIG_DEFAULTS
    ./boards/sdkconfig.base
    ${SDKCONFIG_IDF_VERSION_SPECIFIC}
    ./boards/sdkconfig.disable_iram
    ./boards/sdkconfig.flash_16mb
    ./boards/sdkconfig.freertos
    ./boards/sdkconfig.spiram_hex
    ./boards/M5STACK_Unit_PoEP4/sdkconfig.board
)

# If not enable LVGL, ignore this...
set(LV_CFLAGS
    -DLV_COLOR_DEPTH=16
    -DLV_COLOR_16_SWAP=0
    -DLV_FONT_MONTSERRAT_12=${FONT_MONTSERRAT_12}
    -DLV_FONT_MONTSERRAT_14=${FONT_MONTSERRAT_14}
    -DLV_FONT_MONTSERRAT_16=${FONT_MONTSERRAT_16}
    -DLV_FONT_MONTSERRAT_18=${FONT_MONTSERRAT_18}
    -DLV_FONT_MONTSERRAT_20=${FONT_MONTSERRAT_20}
    -DLV_FONT_MONTSERRAT_22=${FONT_MONTSERRAT_22}
    -DLV_FONT_MONTSERRAT_24=${FONT_MONTSERRAT_24}
    -DLV_FONT_MONTSERRAT_30=${FONT_MONTSERRAT_30}
    -DLV_FONT_MONTSERRAT_36=${FONT_MONTSERRAT_36}
    -DLV_FONT_MONTSERRAT_40=${FONT_MONTSERRAT_40}
    -DLV_FONT_MONTSERRAT_44=${FONT_MONTSERRAT_44}
    -DLV_FONT_MONTSERRAT_48=${FONT_MONTSERRAT_48}
    -DUSR_FONT_ALIBABAPUHUITI_CN24=${FONT_ALIBABAPUHUITI_CN24}
    -DUSR_FONT_ALIBABASANS_JA24=${FONT_ALIBABASANS_JA24}
    -DUSR_FONT_ALIBABASANS_KR24=${FONT_ALIBABASANS_KR24}
)

if(NOT MICROPY_FROZEN_MANIFEST)
    set(MICROPY_FROZEN_MANIFEST ${CMAKE_SOURCE_DIR}/boards/manifest.py)
endif()

# NOTE: 这里的配置是无效的，仅为了兼容ADF，保证编译通过
set(ADF_COMPS     "$ENV{ADF_PATH}/components")
set(ADF_BOARD_DIR "$ENV{ADF_PATH}/components/audio_board/esp32_s3_box_3")

list(APPEND EXTRA_COMPONENT_DIRS
    $ENV{ADF_PATH}/components/audio_pipeline
    $ENV{ADF_PATH}/components/audio_sal
    $ENV{ADF_PATH}/components/esp-adf-libs
    $ENV{ADF_PATH}/components/esp-sr
    ${CMAKE_SOURCE_DIR}/boards
)
