_attrs = {
    "LOGO_IMG": "/system/cardputer/boot/boot_logo_1.jpeg",

    "APPLIST_IMG": "/system/cardputer/applist/main.jpeg",
    "APPLIST_LEFT_IMG": "/system/cardputer/applist/left_cursor.jpeg",
    "APPLIST_RIGHT_IMG": "/system/cardputer/applist/right_cursor.jpeg",
    "RUN_IMG": "/system/cardputer/apprun/run.jpeg",
    "DEVELOP_PRIVATE_IMG": "/system/cardputer/develop/private.jpeg",
    "DEVELOP_PUBLIC_IMG": "/system/cardputer/develop/public.jpeg",
    "BOOT_NO_IMG": "/system/cardputer/setting/boot_no.jpeg",
    "BOOT_YES_IMG": "/system/cardputer/setting/boot_yes.jpeg",
    "COMX_DISABLE_IMG": "/system/cardputer/setting/comx_disable.jpeg",
    "COMX_ENABLE_IMG": "/system/cardputer/setting/comx_enable.jpeg",
    "SCREEN25_IMG": "/system/cardputer/setting/screen_brightness_25.jpeg",
    "SCREEN50_IMG": "/system/cardputer/setting/screen_brightness_50.jpeg",
    "SCREEN75_IMG": "/system/cardputer/setting/screen_brightness_75.jpeg",
    "SCREEN100_IMG": "/system/cardputer/setting/screen_brightness_100.jpeg",
    "SELECT_IMG": "/system/cardputer/setting/select.jpeg",
    "UNSELECT_IMG": "/system/cardputer/setting/unselect.jpeg",
    "WIFI_DEFAULT_IMG": "/system/cardputer/setting/wifi_server.jpeg",
    "WIFI_SSID_IMG": "/system/cardputer/setting/wifi_server_ssid.jpeg",
    "WIFI_PSK_IMG": "/system/cardputer/setting/wifi_server_psk.jpeg",
    "WIFI_SERVER_IMG": "/system/cardputer/setting/wifi_server_server.jpeg",
    "Aa_IMG": "/system/cardputer/sidebar/Aa.jpeg",
    "Aa0_IMG": "/system/cardputer/sidebar/Aa0.jpeg",
    "ALT_IMG": "/system/cardputer/sidebar/alt.jpeg",
    "ALT0_IMG": "/system/cardputer/sidebar/alt0.jpeg",
    "CTRL_IMG": "/system/cardputer/sidebar/ctrl.jpeg",
    "CTRL0_IMG": "/system/cardputer/sidebar/ctrl0.jpeg",
    "FN_IMG": "/system/cardputer/sidebar/fn.jpeg",
    "FN0_IMG": "/system/cardputer/sidebar/fn0.jpeg",
    "OPT_IMG": "/system/cardputer/sidebar/opt.jpeg",
    "OPT0_IMG": "/system/cardputer/sidebar/opt0.jpeg",
    "BATTERY_BLACK_CHARGE_IMG": "/system/cardputer/statusbar/battery/black_charge.jpeg",
    "BATTERY_BLACK_IMG": "/system/cardputer/statusbar/battery/black.jpeg",
    "BATTERY_GREEN_CHARGE_IMG": "/system/cardputer/statusbar/battery/green_charge.jpeg",
    "BATTERY_GREEN_IMG": "/system/cardputer/statusbar/battery/green.jpeg",
    "BATTERY_RED_CHARGE_IMG": "/system/cardputer/statusbar/battery/red_charge.jpeg",
    "BATTERY_RED_IMG": "/system/cardputer/statusbar/battery/red.jpeg",
    "SERVER_EMPTY_IMG": "/system/cardputer/statusbar/cloud/empty.jpeg",
    "SERVER_ERROR_IMG": "/system/cardputer/statusbar/cloud/error.jpeg",
    "SERVER_GREEN_IMG": "/system/cardputer/statusbar/cloud/green.jpeg",
    "WIFI_DISCONNECTED_IMG": "/system/cardputer/statusbar/wifi/disconnected.jpeg",
    "WIFI_EMPTY_IMG": "/system/cardputer/statusbar/wifi/empty.jpeg",
    "WIFI_GOOD_IMG": "/system/cardputer/statusbar/wifi/good.jpeg",
    "WIFI_MID_IMG": "/system/cardputer/statusbar/wifi/mid.jpeg",
    "WIFI_WORSE_IMG": "/system/cardputer/statusbar/wifi/worse.jpeg",
    "APPLIST_ICO": "/system/cardputer/applist.jpeg",
    "DEVELOP_ICO": "/system/cardputer/develop.jpeg",
    "APPRUN_ICO": "/system/cardputer/apprun.jpeg",
    "EZDATA_ICO": "/system/cardputer/ezdata.jpeg",
    "SELETE_BK_IMG": "/system/cardputer/select.jpeg",
    "SETTING_ICO": "/system/cardputer/setting.jpeg",
    "AVATAR_IMG": "/system/common/img/avatar.jpeg",
    "USER_AVATAR_PATH": "/system/common/img/",
}


def __getattr__(attr):
    value = _attrs.get(attr, None)
    if value is None:
        raise AttributeError(attr)
    globals()[attr] = value
    return value
