"""
This type stub file was generated by pyright.
"""

from . import robust
from micropython import schedule

class MQTTClient(robust.MQTTClient):
    def __init__(self, client_id, server, port=..., user=..., password=..., keepalive=..., ssl=..., ssl_params=...) -> None:
        ...
    
    def subscribe(self, topic, handler, qos=...): # -> None:
        ...
    


