"""
This type stub file was generated by pyright.
"""

from . import simple

class MQTTClient(simple.MQTTClient):
    DELAY = ...
    DEBUG = ...
    def delay(self, i): # -> None:
        ...
    
    def log(self, in_reconnect, e): # -> None:
        ...
    
    def reconnect(self): # -> None:
        ...
    
    def publish(self, topic, msg, retain=..., qos=...): # -> None:
        ...
    
    def wait_msg(self): # -> None:
        ...
    
    def check_msg(self, attempts=...): # -> None:
        ...
    


