"""
This type stub file was generated by pyright.
"""

class MQTTException(Exception):
    ...


class MQTTClient:
    def __init__(self, client_id, server, port=..., user=..., password=..., keepalive=..., ssl=..., ssl_params=...) -> None:
        ...
    
    def set_callback(self, f): # -> None:
        ...
    
    def set_last_will(self, topic, msg, retain=..., qos=...): # -> None:
        ...
    
    def connect(self, clean_session=...):
        ...
    
    def disconnect(self): # -> None:
        ...
    
    def ping(self): # -> None:
        ...
    
    def isconnected(self): # -> Literal[False]:
        ...
    
    def publish(self, topic, msg, retain=..., qos=...): # -> None:
        ...
    
    def subscribe(self, topic, qos=...): # -> None:
        ...
    
    def wait_msg(self): # -> None:
        ...
    
    def check_msg(self): # -> None:
        ...
    


