"""
This type stub file was generated by pyright.
"""

class QRCodeM14:
    """
    此驱动适用于 M14 二维码识别模块
    """
    TRIGGER_MODE_KEY = ...
    TRIGGER_MODE_CONTINUOUS = ...
    TRIGGER_MODE_AUTO = ...
    TRIGGER_MODE_PULSE = ...
    TRIGGER_MODE_MOTION_SENSING = ...
    FILL_LIGHT_OFF = ...
    FILL_LIGHT_ON = ...
    FILL_LIGHT_ON_DECODE = ...
    POS_LIGHT_OFF = ...
    POS_LIGHT_ON_DECODE = ...
    POS_LIGHT_FLASH_ON_DECODE = ...
    def __init__(self, id: int = ..., tx: int = ..., rx: int = ..., trig: int = ..., led=...) -> None:
        ...
    
    def set_trig(self, value: int) -> None:
        """Set trigger pin. 设置触发引脚。
        :param int value: ``0`` - 低电平，``1`` - 高电平。
        """
        ...
    
    def start_decode(self) -> None:
        """Start decode. 开始解码。"""
        ...
    
    def stop_decode(self) -> None:
        """Stop decode. 停止解码。"""
        ...
    
    def read(self) -> None | bytes:
        """Read decode data. 读取解码数据。"""
        ...
    
    def set_trigger_mode(self, mode: int) -> None:
        """Set trigger mode. 设置触发解码模式。

        :param int mode: The decode trigger mode.
        """
        ...
    
    def set_decode_delay(self, delay_ms: int) -> None:
        """Set decode delay. 设置命令解码延迟 (按键模式)。

        :param int delay_ms: 解码延迟时间(单位：毫秒), 0 表示持续解码直到成功。
        """
        ...
    
    def set_trigger_timeout(self, timeout_ms: int) -> None:
        """Set trigger timeout. 设置触发超时。(脉冲模式)。

        :param int timeout_ms: 触发超时时间(单位：毫秒), 解码持续时间超过该值时自动停止。
        """
        ...
    
    def set_motion_sensitivity(self, level: int = ...) -> None:
        """Set motion detection sensitivity. 设置移动感应灵敏度。(感应模式中)

        :param int level: 灵敏度等级, 范围 1-5, 等级越高对场景变化越敏感, 默认等级为 3。
        """
        ...
    
    def set_continuous_decode_delay(self, delay_ms: int) -> None:
        """Set continuous decode delay. 设置持续解码延迟时间。(感应模式中)

        :param int delay_ms: 延迟时间，单位为 100 毫秒。值为 0 表示持续解码直到超时。
        """
        ...
    
    def set_trigger_decode_delay(self, delay_ms: int) -> None:
        """设置触发解码延迟时间(感应模式中)

        置触发解码延迟时间。当重新进入检测场景变化阶段，到检测到变化再次开始识读之间的延迟时长。

        :param int delay_ms: 触发解码延迟时间，单位为毫秒。
        """
        ...
    
    def set_same_code_interval(self, interval_ms: int) -> None:
        """Set same code interval. 设置同码间隔时间。

        :param interval_ms: 同一条码的重复识读间隔时间，单位为毫秒。
        """
        ...
    
    def set_diff_code_interval(self, interval_ms: int) -> None:
        """Set difference code interval. 设置异码间隔时间。

        :param int interval_ms: 不同条码的识读间隔时间，单位为毫秒。
        """
        ...
    
    def set_same_code_no_delay(self, enable: bool) -> None:
        """Set same code no delay. 设置同码非延迟输出。

        :param bool enable: 是否开启同码非延迟输出, True 表示开启, False 表示关闭。
        """
        ...
    
    def set_fill_light_mode(self, mode: int = ...) -> None:
        """Set fill light mode. 设置补光灯模式。

        :param int mode: The fill light mode. Available options:
            - ``FILL_LIGHT_OFF``: Light off. 常灭
            - ``FILL_LIGHT_ON``: Light on. 常亮
            - ``FILL_LIGHT_ON_DECODE``: Light on during decoding. 解码时亮
        """
        ...
    
    def set_fill_light_brightness(self, brightness: int = ...) -> None:
        """Set fill light brightness. 设置补光灯亮度。

        :param int brightness: The fill light brightness. Range: 0~100.
        """
        ...
    
    def set_pos_light_mode(self, mode: int = ...) -> None:
        """Set positioning light mode. 设置定位灯模式。

        :param int mode: The positioning light mode. Available options:
            - ``POS_LIGHT_OFF``: Light off. 常灭
            - ``POS_LIGHT_ON_DECODE``: Light on during decoding. 解码时亮
            - ``POS_LIGHT_FLASH_ON_DECODE``: Light flash during decoding. 解码时闪烁
        """
        ...
    
    def set_startup_tone(self, mode: int) -> None:
        """Set startup tone. 设置启动提示音。

        :param mode: 0 - 关闭启动提示音
                     1 - 播放 4 声
                     2 - 播放 2 声
        """
        ...
    
    def set_decode_success_beep(self, count: int) -> None:
        """Set decode success beep. 设置解码成功提示音次数。

        :param count: 0 - 无提示音
                      1 - 播放 1 次提示音
                      2 - 播放 2 次提示音
        """
        ...
    
    def set_case_conversion(self, mode: int = ...) -> None:
        """Set case conversion. 设置数据大小写转换模式。
        :param mode: 0x00 - 关闭（原始数据）
                     0x01 - 转大写（小写字母转换为大写）
                     0x02 - 转小写（大写字母转换为小写）
        """
        ...
    
    def set_protocol_format(self, mode: int) -> None:
        """Set protocol format. 设置协议格式。
        :param mode: 0 - 无协议
                     1 - 格式 1: [0x03] + 数据长度(2bytes) + 数据
                     2 - 格式 2: [0x03] + 数据长度 + 条码个数 + 条码 1 数据长度 + 条码 1 数据 +... + CRC
                     3 - 格式 3: [0x03] + 数据长度 + 条码个数 + 条码 1ID 号 + 条码 1 数据长度 + 条码 1 数据 + ... + CRC
        """
        ...
    
    def get_version(self, timeout_ms=...): # -> None:
        ...
    


