"""
This type stub file was generated by pyright.
"""

class CmdStatus:
    SUCCESS = ...
    INVALID_PARAM = ...
    TIMEOUT = ...
    ACK_MISMATCH = ...


class SerialCmdHelper:
    def __init__(self, serial, debug: bool = ...) -> None:
        ...
    
    def cmd(self, cmd, cmd_ack=..., timeout_ms: int = ...) -> CmdStatus:
        """
        发送串口命令并处理响应。
        :param cmd: 要发送的命令。
        :param cmd_ack: 期望的响应 (None 表示不期望响应)。
        :param timeout_ms: 等待响应的超时时间 (仅在 cmd_ack 不为 None 时生效)。
        :return: 执行状态。
        """
        ...
    
    def cmd_retry(self, cmd: bytes, cmd_ack: bytes, timeout_ms: int = ..., retries: int = ..., retry_delay_ms: int = ...) -> CmdStatus:
        """
        发送命令并进行重试。
        :param retries: 重试次数。
        :param retry_delay_ms: 每次重试之间的延迟时间 (毫秒)。
        :return: 执行状态。
        """
        ...
    


