# SPDX-FileCopyrightText: 2024 M5Stack Technology CO LTD
#
# SPDX-License-Identifier: MIT
package(
    "base",
    (
        "__init__.py",
        "atom_can.py",
        "atom_gps.py",
        "atom_socket.py",
        "display.py",
        "dtu_lorawan.py",
        "dtu_lorawan_rui3.py",
        "dtu_nbiot.py",
        "echo.py",
        "gpsv2.py",
        "hdriver.py",
        "motion.py",
        "pwm.py",
        "qrcode.py",
        "qrcode2.py",
        "rs232.py",
        "speaker.py",
        "stepmotor.py",
        "tfcard.py",
    ),
    base_path="..",
    opt=3,
)
