"""
This type stub file was generated by pyright.
"""

class Response:
    def __init__(self, f) -> None:
        ...
    
    def close(self): # -> None:
        ...
    
    @property
    def content(self):
        ...
    
    @property
    def text(self): # -> str:
        ...
    
    def json(self): # -> Any:
        ...
    


def urlencode(query): # -> LiteralString:
    ...

