"""
This type stub file was generated by pyright.
"""

import lvgl as lv

class M5Bar(lv.bar):
    """Initialize a new M5Bar widget.

    :param int x: The x-coordinate of the bar.
    :param int y: The y-coordinate of the bar.
    :param int w: The width of the bar.
    :param int h: The height of the bar.
    :param int min_value: The minimum value of the bar range.
    :param int max_value: The maximum value of the bar range.
    :param int value: The initial value of the bar.
    :param bool is_show_value: Whether to display the current value as text.
    :param int bg_c: The background color of the bar.
    :param int color: The indicator color of the bar.
    :param lv.obj parent: The parent object. If None, uses the active screen.
    :return: None

    UiFlow2 Code Block:

        None

    MicroPython Code Block:

        .. code-block:: python

            bar = M5Bar(x=50, y=50, w=200, h=30, min_value=0, max_value=100, value=50)
    """
    def __init__(self, x=..., y=..., w=..., h=..., min_value=..., max_value=..., value=..., is_show_value=..., bg_c=..., color=..., parent=...) -> None:
        ...
    
    def set_style_radius(self, radius: int, part: int) -> None:
        ...
    
    def __getattr__(self, name): # -> Callable[..., Any]:
        ...
    


