"""
This type stub file was generated by pyright.
"""

class M5Base:
    @staticmethod
    def set_flag(self, flag: int, value: bool) -> None:
        """Set a flag on the object. If `value` is True, the flag is added; if False, the flag is removed.

        :param int flag: The flag to set.
        :param bool value: If True, the flag is added; if False, the flag is removed.
        :return: None
        """
        ...
    
    @staticmethod
    def toggle_flag(self, flag): # -> None:
        """Toggle a flag on the object. If the flag is set, it is removed; if not set, it is added.

        :param int flag: The flag to toggle.
        """
        ...
    
    @staticmethod
    def set_state(self, state: int, value: bool) -> None:
        """Set a state on the object.

        :param int state: The state to set.
        :param bool value: If True, the state is added; if False, the state is removed.
        :return: None
        """
        ...
    
    @staticmethod
    def toggle_state(self, state: int) -> None:
        """Toggle a state on the object. If the state is set, it is removed; if not set, it is added.

        :param int state: The state to toggle.
        :return: None
        """
        ...
    
    @staticmethod
    def set_text_color(self, color: int, opa: int, part: int) -> None:
        """Set the text color and opacity for a given part of the object.

        :param int color: The color to set, can be an integer (hex) or a lv.color object.
        :param int opa: The opacity level (0-255).
        :param int part: The part of the object to apply the style to (e.g., lv.PART.MAIN).
        :return: None
        """
        ...
    
    @staticmethod
    def set_line_color(self, color: int, opa: int, part: int) -> None:
        """Set the line color and opacity for a given part of the object.

        :param int color: The color to set, can be an integer (hex) or a lv.color object.
        :param int opa: The opacity level (0-255).
        :param int part: The part of the object to apply the style to (e.g., lv.PART.MAIN).
        :return: None
        """
        ...
    
    @staticmethod
    def set_bg_color(self, color: int, opa: int, part: int) -> None:
        """Set the background color and opacity for a given part of the object.

        :param int color: The color to set, can be an integer (hex) or a lv.color object.
        :param int opa: The opacity level (0-255).
        :param int part: The part of the object to apply the style to (e.g., lv.PART.MAIN).
        :return: None
        """
        ...
    
    @staticmethod
    def set_line_color(self, color: int, opa: int, part: int = ...) -> None:
        """Set the line color and opacity for a given part of the object.

        :param int color: The color to set, can be an integer (hex) or a lv.color object.
        :param int opa: The opacity level (0-255).
        :param int part: The part of the object to apply the style to (e.g., lv.PART.MAIN).
        :return: None
        """
        ...
    
    @staticmethod
    def set_bg_grad_color(self, color, opa, grad_color, grad_opd, grad_dir, part: int) -> None:
        """Set the background gradient color of the bar.

        :param int color: The start color of the gradient, can be an integer (RGB).
        :param int opa: The opacity of the start color (0-255).
        :param int grad_color: The end color of the gradient, can be an integer (RGB).
        :param int grad_opd: The opacity of the end color (0-255).
        :param int grad_dir: The direction of the gradient (e.g., lv.GRAD_DIR.VER).
        :param int part: The part of the object to apply the style to (e.g., lv.PART.MAIN).
        :return: None
        """
        ...
    
    @staticmethod
    def set_border_color(self, color: int, opa: int, part: int): # -> None:
        """Set the border color and opacity for a given part of the object.

        :param int color: The color to set, can be an integer (hex) or a lv.color object.
        :param int opa: The opacity level (0-255).
        :param int part: The part of the object to apply the style to (e.g., lv.PART.MAIN).
        :return: None
        """
        ...
    


