"""
This type stub file was generated by pyright.
"""

import lvgl as lv

class M5Button(lv.button):
    """Create a button object.

    :param str text: The text to display on the button.
    :param int x: The x position of the button.
    :param int y: The y position of the button.
    :param int w: The width of the button. when set to 0, the button will automatically size to fit the text.
    :param int h: The height of the button. when set to 0, the button will automatically size to fit the text.
    :param int bg_c: The background color of the button in hexadecimal format.
    :param int text_c: The text color of the button in hexadecimal format.
    :param lv.lv_font_t font: The font to use for the button text.
    :param lv.obj parent: The parent object to attach the button to. If not specified, the button will be attached to the default screen.

    UiFlow2 Code Block:

        None

    MicroPython Code Block:

        .. code-block:: python

            from m5ui import M5Button
            import lvgl as lv

            m5ui.init()
            button_0 = M5Button(text="Click Me", x=10, y=10, bg_c=0x2196F3, text_c=0xFFFFFF, parent=page0)
    """
    EFFECT_SIMPLE = ...
    EFFECT_WAVE = ...
    EFFECT_GUMMY = ...
    def __init__(self, text=..., x=..., y=..., w=..., h=..., bg_c=..., text_c=..., font=..., parent=...) -> None:
        ...
    
    def set_btn_text(self, text: str) -> None:
        """Set the text of the button.

        :param str text: The text to set on the button.

        UiFlow2 Code Block:

            |set_btn_text.png|

        MicroPython Code Block:

            .. code-block:: python

                button_0.set_btn_text("Click Me")
        """
        ...
    
    def set_style_radius(self, radius: int, part: int) -> None:
        ...
    
    def get_btn_text(self) -> str:
        """Get the text of the button.

        :return: The text of the button.
        :rtype: str

        UiFlow2 Code Block:

            |get_btn_text.png|

        MicroPython Code Block:
            .. code-block:: python

                text = button_0.get_btn_text()
        """
        ...
    
    def set_shadow(self, color, opa, align, offset_x, offset_y): # -> None:
        ...
    
    def unset_shadow(self):
        ...
    
    def set_pressed_effect(self, effect): # -> None:
        ...
    
    def __getattr__(self, name): # -> Callable[..., Any]:
        ...
    


