"""
This type stub file was generated by pyright.
"""

import lvgl as lv

class M5Calendar(lv.calendar):
    """Create a calendar object.

    :param int x: The x position of the calendar.
    :param int y: The y position of the calendar.
    :param int w: The width of the calendar.
    :param int h: The height of the calendar.
    :param str style: The style of the calendar, can be "arrow" or "dropdown" and None.
    :param list today_date: The date to highlight as today in the format [year, month, day].
    :param list show_month: The month to show in the format [year, month].
    :param lv.obj parent: The parent object to attach the calendar to. If not specified, the calendar will be attached to the default screen.

    MicroPython Code Block:

        .. code-block:: python

            from m5ui import M5Calendar
            import lvgl as lv

            m5ui.init()
            calendar_0 = M5Calendar(x=0, y=0, w=200, h=200, style=None, today_date=[2024, 1, 1], show_month=[2024, 1], parent=page0)
    """
    def __init__(self, x=..., y=..., w=..., h=..., style=..., today_date=..., show_month=..., parent=...) -> None:
        ...
    
    def set_calendar_style(self, style): # -> None:
        """Set the style of the calendar header.

        :param str style: The style of the calendar header, can be "arrow", "dropdown", or None.

        UiFlow2 Code Block:

            |set_calendar_style.png|

        MicroPython Code Block:

            .. code-block:: python

                calendar_0.set_calendar_style("arrow")
                calendar_0.set_calendar_style("dropdown")
                calendar_0.set_calendar_style(None)
        """
        ...
    
    def set_highlighted_dates(self, dates): # -> None:
        """Set the highlighted dates in the calendar.

        :param list dates: A list of dates to highlight in the format [year, month, day, year, month, day, ...]

        UiFlow2 Code Block:

            |set_highlighted_dates.png|

        MicroPython Code Block:

            .. code-block:: python

                calendar_0.set_highlighted_dates([2024, 1, 1, 2024, 1, 2, 2024, 1, 3])
        """
        ...
    
    def set_style_radius(self, radius: int, part: int) -> None:
        ...
    
    def __getattr__(self, name): # -> Callable[..., Any]:
        ...
    


