"""
This type stub file was generated by pyright.
"""

import lvgl as lv

class M5Canvas(lv.canvas):
    """Create a canvas widget for drawing.

    :param int x: The x-coordinate of the canvas.
    :param int y: The y-coordinate of the canvas.
    :param int w: The width of the canvas.
    :param int h: The height of the canvas.
    :param lv.COLOR_FORMAT color_format: The color format of the canvas (default is ARGB8888).
    :param int bg_c: The background color of the canvas in hexadecimal format (e.g., 0xRRGGBB).
    :param int bg_opa: The opacity of the background (0-255).
    :param lv.obj parent: The parent object of the canvas. If not specified, it will be
                   set to the active screen.
    """
    def __init__(self, x=..., y=..., w=..., h=..., color_format=..., bg_c=..., bg_opa=..., parent=...) -> None:
        ...
    
    def fill_bg(self, color: int, opa: int): # -> None:
        """Fill the canvas background with the specified color and opacity.

        :param int color: The background color in hexadecimal format (e.g., 0xRRGGBB).
        :param int opa: The opacity of the background (0-255).

        UiFlow2 Code Block:

            |set_bg_color.png|

        MicroPython Code Block:

            .. code-block:: python

                canvas_0.fill_bg(0x001122, 255)

        """
        ...
    
    def set_px(self, x: int, y: int, color: lv.color_t, opa: int): # -> None:
        """Set a pixel at (x, y) with the specified color and opacity.

        :param int x: The x-coordinate of the pixel.
        :param int y: The y-coordinate of the pixel.
        :param int color: The color of the pixel in hexadecimal format (e.g., 0xRRGGBB).
        :param int opa: The opacity of the pixel (0-255).

        UiFlow2 Code Block:

            |set_px.png|

        MicroPython Code Block:

            .. code-block:: python

                canvas_0.set_px(100, 100, 0xFF0000, 255)
        """
        ...
    
    def get_px_color(self, x: int, y: int) -> int:
        """Get the color of the pixel at (x, y).

        :param int x: The x-coordinate of the pixel.
        :param int y: The y-coordinate of the pixel.
        :return: The color of the pixel in hexadecimal format (e.g., 0xRRGGBB).
        :rtype: int

        UiFlow2 Code Block:

            |get_px_color.png|

        MicroPython Code Block:

            .. code-block:: python

                color = canvas_0.get_px_color(100, 100)
                print(hex(color))  # Prints the color in hexadecimal format
        """
        ...
    
    def get_px_opa(self, x: int, y: int) -> int:
        """Get the opacity of the pixel at (x, y).

        :param int x: The x-coordinate of the pixel.
        :param int y: The y-coordinate of the pixel.
        :return: The opacity of the pixel (0-255).
        :rtype: int

        UiFlow2 Code Block:

            |get_px_opa.png|

        MicroPython Code Block:

            .. code-block:: python
        """
        ...
    
    def draw_arc(self, x: int, y: int, r: int, color: int = ..., opa: int = ..., width: int = ..., start_angle: int = ..., end_angle: int = ...): # -> None:
        """Draw an arc on the canvas.

        :param int x: The x-coordinate of the center of the arc.
        :param int y: The y-coordinate of the center of the arc.
        :param int r: The radius of the arc.
        :param int color: The color of the arc in hexadecimal format (e.g., 0xRRGGBB).
        :param int opa: The opacity of the arc (0-255).
        :param int width: The width of the arc line.
        :param int start_angle: The starting angle of the arc in degrees.
        :param int end_angle: The ending angle of the arc in degrees.

        UiFlow2 Code Block:

            |draw_arc.png|

        MicroPython Code Block:

            .. code-block:: python

                canvas_0.draw_arc(100, 100, 50, 0xFF0000, 255, 2, 0, 180)
        """
        ...
    
    def draw_rect(self, x: int, y: int, w: int, h: int, radius: int = ..., bg_c: int = ..., bg_opa: int = ..., border_c: int = ..., border_opa: int = ..., border_w: int = ..., border_side: int = ..., outline_c: int = ..., outline_opa: int = ..., outline_w: int = ..., outline_pad: int = ..., shadow_c: int = ..., shadow_opa: int = ..., shadow_w: int = ..., shadow_offset_x: int = ..., shadow_offset_y: int = ..., shadow_spread: int = ...): # -> None:
        """Draw a rectangle on the canvas.

        :param int x: The x-coordinate of the rectangle.
        :param int y: The y-coordinate of the rectangle.
        :param int w: The width of the rectangle.
        :param int h: The height of the rectangle.
        :param int radius: The corner radius of the rectangle.
        :param int bg_c: The background color of the rectangle in hexadecimal format (e.g., 0xRRGGBB).
        :param int bg_opa: The opacity of the background (0-255).
        :param int border_c: The border color of the rectangle in hexadecimal format (e.g., 0xRRGGBB).
        :param int border_opa: The opacity of the border (0-255).
        :param int border_w: The width of the border.
        :param int border_side: The side of the border to draw (e.g., lv.BORDER_SIDE.FULL).
        :param int outline_c: The outline color of the rectangle in hexadecimal format (e.g., 0xRRGGBB).
        :param int outline_opa: The opacity of the outline (0-255).
        :param int outline_w: The width of the outline.
        :param int outline_pad: The padding of the outline.
        :param int shadow_c: The shadow color of the rectangle in hexadecimal format (e.g., 0xRRGGBB).
        :param int shadow_opa: The opacity of the shadow (0-255).
        :param int shadow_w: The width of the shadow.
        :param int shadow_offset_x: The horizontal offset of the shadow.
        :param int shadow_offset_y: The vertical offset of the shadow.
        :param int shadow_spread: The spread of the shadow.

        UiFlow2 Code Block:

            |draw_rect.png|

        MicroPython Code Block:

            .. code-block:: python

                canvas_0.draw_rect(10, 10, 100, 50, radius=5, bg_c=0xFF0000,
                                   bg_opa=255, border_c=0x00FF00, border_opa=255,
                                   border_w=2, outline_c=0x0000FF, outline_opa=255,
                                   outline_w=1, shadow_c=0x000000, shadow_opa=128,
                                   shadow_w=5, shadow_offset_x=2, shadow_offset_y= 2,
                                   shadow_spread=0)
        """
        ...
    
    def draw_image(self, img_src: str, x: int = ..., y: int = ..., rotation: int = ..., scale_x: float = ..., scale_y: float = ..., skew_x: int = ..., skew_y: int = ...): # -> None:
        """Draw an image at the specified coordinates.

        :param str img_src: The source of the image (e.g., a file path or an image object).
        :param int x: The x-coordinate where the image will be drawn.
        :param int y: The y-coordinate where the image will be drawn.
        :param int rotation: The rotation angle of the image in degrees.
        :param float scale_x: The horizontal scaling factor of the image.
        :param float scale_y: The vertical scaling factor of the image.
        :param int skew_x: The horizontal skew angle of the image in degrees.
        :param int skew_y: The vertical skew angle of the image in degrees.

        UiFlow2 Code Block:

            |draw_image.png|

        MicroPython Code Block:

            .. code-block:: python

                canvas_0.draw_image("path/to/image.png", x=10, y=20, rotation=0,
                                    scale_x=1.0, scale_y=1.0, skew_x=0, skew_y=0)
        """
        ...
    
    def draw_line(self, x1: int, y1: int, x2: int, y2: int, color: int = ..., opa: int = ..., width: int = ...): # -> None:
        """Draw a line from (x1, y1) to (x2, y2).

        :param int x1: The x-coordinate of the start point of the line.
        :param int y1: The y-coordinate of the start point of the line.
        :param int x2: The x-coordinate of the end point of the line.
        :param int y2: The y-coordinate of the end point of the line.
        :param int color: The color of the line in hexadecimal format (e.g., 0xRRGGBB).
        :param int opa: The opacity of the line (0-255).
        :param int width: The width of the line.

        UiFlow2 Code Block:

            |draw_line.png|

        MicroPython Code Block:

            .. code-block:: python

                canvas_0.draw_line(10, 10, 100, 100, color=0xFF0000, opa=255, width=2)
        """
        ...
    
    def draw_label(self, txt: str, x: int = ..., y: int = ..., font=..., color=..., opa=...): # -> None:
        """Draw a label with the specified text at the given coordinates.

        :param str txt: The text to be displayed.
        :param int x: The x-coordinate where the label will be drawn.
        :param int y: The y-coordinate where the label will be drawn.
        :param font: The font to be used for the label (default is lv.font_montserrat_14).
        :param int color: The color of the text in hexadecimal format (e.g., 0xRRGGBB).
        :param int opa: The opacity of the text (0-255).

        UiFlow2 Code Block:

            |draw_label.png|

        MicroPython Code Block:

            .. code-block:: python

                canvas_0.draw_label("Hello, World!", x=10, y=20, font=lv.font_montserrat_14,
                                    color=0xFFFFFF, opa=255)
        """
        ...
    
    def draw_triangle(self, x1: int, y1: int, x2: int, y2: int, x3: int, y3: int, bg_c: int = ..., bg_opa: int = ...): # -> None:
        """Draw a triangle with the specified vertices.

        :param int x1: The x-coordinate of the first vertex.
        :param int y1: The y-coordinate of the first vertex.
        :param int x2: The x-coordinate of the second vertex.
        :param int y2: The y-coordinate of the second vertex.
        :param int x3: The x-coordinate of the third vertex.
        :param int y3: The y-coordinate of the third vertex.
        :param int bg_c: The background color of the triangle in hexadecimal format (e.g., 0xRRGGBB).
        :param int bg_opa: The opacity of the triangle (0-255).

        UiFlow2 Code Block:

            |draw_triangle.png|

        MicroPython Code Block:

            .. code-block:: python

                canvas_0.draw_triangle(10, 10, 50, 10, 30, 40, bg_c=0xFF0000, bg_opa=255)
        """
        ...
    
    def set_style_radius(self, radius: int, part: int) -> None:
        ...
    
    def __getattr__(self, name): # -> Callable[..., Any]:
        ...
    


