"""
This type stub file was generated by pyright.
"""

import lvgl as lv

class M5Checkbox(lv.checkbox):
    """Create a checkbox object.

    :param str title: The title text of the checkbox.
    :param bool value: The initial checked state of the checkbox.
    :param int x: The x position of the checkbox.
    :param int y: The y position of the checkbox.
    :param int title_c: The color of the title text in hexadecimal format.
    :param lv.lv_font_t title_font: The font to use for the title text.
    :param int bullet_border_c: The border color of the checkbox bullet in hexadecimal format.
    :param int bullet_bg_c: The background color of the checkbox bullet in hexadecimal format.
    :param lv.obj parent: The parent object to attach the checkbox to. If not specified, the checkbox will be attached to the default screen.

    UiFlow2 Code Block:

        None

    MicroPython Code Block:

        .. code-block:: python

            from m5ui import M5Checkbox
            import lvgl as lv
            m5ui.init()
            checkbox_0 = M5Checkbox(title="Check Me", value=True, x=10, y=10, title_c=0x2121, title_font=lv.font_montserrat_14, bullet_border_c=0x2196F3, bullet_bg_c=0xFFFFFF, parent=page0)

    """
    def __init__(self, title=..., value=..., x=..., y=..., title_c=..., title_font=..., bullet_border_c=..., bullet_bg_c=..., parent=...) -> None:
        ...
    
    def set_style_radius(self, radius: int, part: int) -> None:
        ...
    
    def __getattr__(self, name): # -> Callable[..., Any]:
        ...
    


