"""
This type stub file was generated by pyright.
"""

import lvgl as lv

class M5Dropdown(lv.dropdown):
    """Create a dropdown object.

    :param x: The x position of the dropdown.
    :param y: The y position of the dropdown.
    :param w: The width of the dropdown.
    :param h: The height of the dropdown, default is `lv.SIZE_CONTENT`.
    :param options: A list of options to display in the dropdown.
    :param direction: The direction of the dropdown, can be `lv.DIR.LEFT`, `lv.DIR.RIGHT`, `lv.DIR.TOP`, or `lv.DIR.BOTTOM`.
    :param show_selected: Whether to highlight the selected option, default is `True`.
    :param font: The font used for the text in the dropdown, default is `lv.font_montserrat_14`.
    :param parent: The parent object for this dropdown, default is the active screen.
    """
    def __init__(self, x=..., y=..., w=..., h=..., options: list = ..., direction: int = ..., show_selected: bool = ..., font: lv.font_t = ..., parent=...) -> None:
        ...
    
    def set_options(self, options: list): # -> None:
        """Set the options for the dropdown.

        :param options: A list of options to display in the dropdown.

        UiFlow2 Code Block:

            |set_options.png|

        MicroPython Code Block:

            .. code-block:: python

                dropdown_0.set_options(["option1", "option2", "option3"])
        """
        ...
    
    def get_options(self) -> list:
        """Get the list of options in the dropdown.

        :return: The list of options.
        :rtype: list
        """
        ...
    
    def add_option(self, option: str, pos: int) -> None:
        """Add an option to the dropdown at a specific position.

        :param option: The option to add.
        :param pos: The position to insert the option at.

        UiFlow2 Code Block:

            |add_option.png|

        MicroPython Code Block:

            .. code-block:: python

                dropdown_0.add_option("New Option", 1)
        """
        ...
    
    def clear_options(self) -> None:
        """Clear all options in the dropdown.

        UiFlow2 Code Block:

            |clear_options.png|

        MicroPython Code Block:

            .. code-block:: python

                dropdown_0.clear_options()
        """
        ...
    
    def get_selected_str(self) -> str:
        """Get the currently selected option as a string.

        :return: The selected option as a string.

        UiFlow2 Code Block:

            |get_selected_str.png|

        MicroPython Code Block:

            .. code-block:: python

                selected_option = dropdown_0.get_selected_str()
        """
        ...
    
    def set_dir(self, direction: int) -> None:
        """Set the direction of the dropdown.

        :param direction: The direction of the dropdown, can be `lv.DIR.LEFT`, `lv.DIR.RIGHT`, `lv.DIR.TOP`, or `lv.DIR.BOTTOM`.

        UiFlow2 Code Block:

            |set_dir.png|

        MicroPython Code Block:

            .. code-block:: python

                dropdown_0.set_dir(lv.DIR.LEFT)
        """
        ...
    
    def set_style_radius(self, radius: int, part: int) -> None:
        """Set the radius of the dropdown's corners.

        :param radius: The radius of the corners in pixels.
        :param part: The part of the dropdown to apply the radius to, e.g., `lv.PART.MAIN`.

        UiFlow2 Code Block:

            None

        MicroPython Code Block:

            .. code-block:: python

                dropdown_0.set_style_radius(10, lv.PART.MAIN | lv.STATE.DEFAULT)
        """
        ...
    
    def __getattr__(self, name): # -> Callable[..., Any]:
        ...
    


