"""
This type stub file was generated by pyright.
"""

import lvgl as lv

class M5Image(lv.image):
    """Create a image object.

    :param str path: The path of the image file.
    :param int x: The x position of the image.
    :param int y: The y position of the image.
    :param lv.obj parent: The parent object to attach the image to. If not specified, the image will be attached to the default screen.

    MicroPython Code Block:

        .. code-block:: python

            from m5ui import M5Image
            import lvgl as lv

            m5ui.init()
            image_0 = M5Image("/flash/res/img/defalut.jpg", x=10, y=10, parent=page0)
            image_1 = M5Image("/flash/res/img/uiflow.jpg", x=50, y=50, parent=page0)
    """
    def __init__(self, path, x=..., y=..., rotation=..., scale_x=..., scale_y=..., parent=...) -> None:
        ...
    
    def set_image(self, path): # -> None:
        """Set the image to be displayed.

        :param str path: The path of the image file.

        UiFlow2 Code Block:

            |set_image.png|

        MicroPython Code Block:

            .. code-block:: python

                image_0.set_image("/flash/res/img/uiflow.jpg")
                image_1.set_image("/sd/uiflow.png")
        """
        ...
    
    def set_rotation(self, rotation): # -> None:
        """Set the rotation of the image.

        :param int rotation: The rotation angle in degrees (0, 90, 180, 270).

        UiFlow2 Code Block:

            |set_rotation.png|

        MicroPython Code Block:

            .. code-block:: python

                image_0.set_rotation(90)
        """
        ...
    
    def set_scale(self, scale, scale_y=...): # -> None:
        """Set the scale of the image.

        :param float scale_x: The horizontal scale factor.
        :param float scale_y: The vertical scale factor.

        UiFlow2 Code Block:

            |set_scale.png|

        MicroPython Code Block:

            .. code-block:: python

                image_0.set_scale(2.0, 2.0)
        """
        ...
    
    def set_style_radius(self, radius: int, part: int) -> None:
        ...
    
    def __getattr__(self, name): # -> Callable[..., Any]:
        ...
    


