"""
This type stub file was generated by pyright.
"""

import lvgl as lv

class M5Keyboard(lv.keyboard):
    """Create a keyboard widget.

    :param int x: The x position of the keyboard.
    :param int y: The y position of the keyboard.
    :param int w: The width of the keyboard.
    :param int h: The height of the keyboard.
    :param int mode: The keyboard mode, default is `lv.keyboard.MODE.TEXT_LOWER`.
    :param lv.obj target_textarea: The target textarea to link with the keyboard.
    :param lv.obj parent: The parent object, default is the active screen.

    UiFlow2 Code Block:

        None

    MicroPython Code Block:

        .. code-block:: python

            import m5ui
            import lvgl as lv

            m5ui.init()
            keyboard = m5ui.M5Keyboard(x=0, y=120, w=320, h=100, target_textarea=None, parent=page0)
    """
    def __init__(self, x=..., y=..., w=..., h=..., mode=..., target_textarea=..., parent=...) -> None:
        ...
    
    def __getattr__(self, name): # -> Callable[..., Any]:
        ...
    


