"""
This type stub file was generated by pyright.
"""

import lvgl as lv

class M5Label(lv.label):
    """Create a label object.

    :param str text: The text to display on the label.
    :param int x: The x position of the label.
    :param int y: The y position of the label.
    :param int text_c: The text color of the label in hexadecimal format.
    :param int bg_c: The background color of the label in hexadecimal format.
    :param int bg_opa: The background opacity of the label (0-255).
    :param lv.lv_font_t font: The font to use for the button text.
    :param lv.obj parent: The parent object to attach the button to. If not specified, the button will be attached to the default screen.

    UiFlow2 Code Block:

        None

    MicroPython Code Block:

        .. code-block:: python

            from m5ui import M5Label
            import lvgl as lv

            m5ui.init()
            label_0 = M5Label(text="Hello, World!", x=10, y=10, text_c=0x212121, bg_c=0xFFFFFF, bg_opa=0, font=lv.font_montserrat_14, parent=page0)
    """
    def __init__(self, text, x=..., y=..., text_c=..., bg_c=..., bg_opa=..., font=..., parent=...) -> None:
        ...
    
    def set_shadow(self, color: int, opa: int, align: int, offset_x: int, offset_y: int) -> None:
        """Set a shadow for the label.

        :param int color: The color of the shadow in hexadecimal format or an integer.
        :param int opa: The opacity of the shadow (0-255).
        :param int align: The alignment of the shadow relative to the label.
        :param int offset_x: The horizontal offset of the shadow.
        :param int offset_y: The vertical offset of the shadow.
        :return: None

        UiFlow2 Code Block:

            |set_shadow.png|

        MicroPython Code Block:

            .. code-block:: python

                label_0.set_shadow(color=0x000000, opa=128, align=lv.ALIGN.BOTTOM_RIGHT, offset_x=5, offset_y=5)
        """
        ...
    
    def unset_shadow(self) -> None:
        """Remove the shadow from the label.

        UiFlow2 Code Block:

            |unset_shadow.png|

        MicroPython Code Block:

            .. code-block:: python

                label_0.unset_shadow()
        """
        ...
    
    def set_style_radius(self, radius: int, part: int) -> None:
        ...
    
    def __del__(self): # -> None:
        ...
    
    def __getattr__(self, name): # -> Callable[..., Any]:
        ...
    


