"""
This type stub file was generated by pyright.
"""

import lvgl as lv

class M5Line(lv.line):
    """Create a line object.

    :param list points: A list of points where each point is a pair of x and y coordinates.
    :param int width: The width of the line.
    :param int color: The color of the line in hexadecimal format.
    :param bool rounded: If True, the line will have rounded ends; otherwise, it will have square ends.
    :param lv.obj parent: The parent object to attach the line to. If not specified, the line will be attached to the default screen.

    MicroPython Code Block:

        .. code-block:: python

            from m5ui import M5Image
            import lvgl as lv

            m5ui.init()
            line_0 = M5Line(
                points=[5, 5, 70, 70, 120, 10, 180, 60, 240, 20],
                width=2,
                color=0x2196F3,
                rounded=True,
                parent=page0,
            )
    """
    def __init__(self, points=..., width=..., color=..., rounded=..., parent=...) -> None:
        ...
    
    def set_points(self, points: list): # -> None:
        """Set the points of the line.

        :param list points: A list of points where each point is a pair of x and y coordinates.

        UiFlow2 Code Block:

            |set_points.png|

        MicroPython Code Block:

            .. code-block:: python

                line_0.set_points([0, 0, 100, 100, 200, 50])
        """
        ...
    
    def add_point(self, x, y): # -> None:
        """Add a point to the line end.

        :param int x: The x position of the point.
        :param int y: The y position of the point.

        UiFlow2 Code Block:

            |add_point.png|

        MicroPython Code Block:

            .. code-block:: python

                line_0.add_point(100, 100)
        """
        ...
    
    def set_style_radius(self, radius: int, part: int) -> None:
        ...
    
    def __getattr__(self, name): # -> Callable[..., Any]:
        ...
    


