"""
This type stub file was generated by pyright.
"""

import lvgl as lv

class M5List(lv.list):
    """Create a list object.

    :param int x: The x position of the list.
    :param int y: The y position of the list.
    :param int w: The width of the list.
    :param int h: The height of the list.
    :param lv.obj parent: The parent object to attach the list to. If not specified, the list will be attached to the default screen.

    UiFlow2 Code Block:

        None

    MicroPython Code Block:

        .. code-block:: python

            from m5ui import M5List
            import lvgl as lv

            m5ui.init()
            list_0 = M5List(x=120, y=80, w=60, h=30, parent=page0)
    """
    def __init__(self, x=..., y=..., w=..., h=..., parent=...) -> None:
        ...
    
    def add_text(self, text, text_c=..., text_opa=..., bg_c=..., bg_opa=..., font=...): # -> Any:
        """Add a text label to the list.

        :param str text: The text to display on the label.
        :param int text_c: The text color of the label in hexadecimal format.
        :param int text_opa: The text opacity of the label (0-255).
        :param int bg_c: The background color of the label in hexadecimal format.
        :param int bg_opa: The background opacity of the label (0-255).
        :param lv.font font: The font to use for the label.
        :return: The created label object :ref:`m5ui.M5Label <m5ui.M5Label>`.
        :rtype: lv.obj

        UiFlow2 Code Block:

            |add_text.png|
            |add_text2.png|

        MicroPython Code Block:

            .. code-block:: python

                list_0.add_text("Item 1", text_c=0x000000, text_opa=255, bg_c=0xFFFFFF, bg_opa=255, font=lv.font_montserrat_14)
        """
        ...
    
    def add_button(self, icon, text=..., h=..., bg_c=..., bg_opa=..., text_c=..., text_opa=..., font=...): # -> Any:
        """Add a button to the list.

        :param int icon: The icon to display on the button.
        :param str text: The text to display on the button.
        :param int h: The height of the button.
        :param int bg_c: The background color of the button in hexadecimal format.
        :param int bg_opa: The background opacity of the button (0-255).
        :param int text_c: The text color of the button in hexadecimal format.
        :param int text_opa: The text opacity of the button (0-255).
        :param lv.font font: The font to use for the button text.
        :return: The created button object :ref:`m5ui.M5Button <m5ui.M5Button>`.
        :rtype: lv.obj

        UiFlow2 Code Block:

            |add_button.png|
            |add_button2.png|

        MicroPython Code Block:

            .. code-block:: python

                list_0.add_button(lv.SYMBOL.BULLET, text="Home", h=40, bg_c=0xFFFFFF, text_c=0x000000, font=lv.font_montserrat_14)
        """
        ...
    
    def __getattr__(self, name): # -> Callable[..., Any]:
        ...
    


