"""
This type stub file was generated by pyright.
"""

import lvgl as lv

class M5Page(lv.obj):
    """Create a page object.

    :param int bg_c: The background color of the page in hexadecimal format. Default is 0xFFFFFF (white).

    UiFlow2 Code Block:

        None

    MicroPython Code Block:

        .. code-block:: python

            from m5ui import M5Page
            import lvgl as lv

            m5ui.init()
            page_0 = M5Page(bg_c=0xFFFFFF)
    """
    def __init__(self, bg_c=...) -> None:
        ...
    
    def screen_load(self): # -> None:
        """Load the page as the active screen.

        UiFlow2 Code Block:

            |screen_load.png|

        MicroPython Code Block:

            .. code-block:: python

                page_0.screen_load()
        """
        ...
    
    def set_style_radius(self, radius: int, part: int) -> None:
        ...
    
    def __getattr__(self, name): # -> Callable[..., Any]:
        ...
    


