"""
This type stub file was generated by pyright.
"""

import lvgl as lv

class M5Scale(lv.scale):
    """Create a scale object.

    :param int x: The x position of the scale.
    :param int y: The y position of the scale.
    :param int w: The width of the scale. If not specified, it will be set based on the mode.
    :param int h: The height of the scale. If not specified, it will be set based on the mode.
    :param int start_pos: The starting position of the scale.
    :param int end_pos: The ending position of the scale.
    :param int tick_count: The total number of ticks on the scale.
    :param int tick_every: The interval between major ticks on the scale.
    :param int mode: The mode of the scale. It can be one of the following:

        Options:

            - `lv.scale.MODE.HORIZONTAL_TOP`: Horizontal top scale.
            - `lv.scale.MODE.HORIZONTAL_BOTTOM`: Horizontal bottom scale.
            - `lv.scale.MODE.VERTICAL_LEFT`: Vertical left scale.
            - `lv.scale.MODE.VERTICAL_RIGHT`: Vertical right scale.
            - `lv.scale.MODE.ROUND_INNER`: Round inner scale.
            - `lv.scale.MODE.ROUND_OUTER`: Round outer scale.

    :param lv.obj parent: The parent object to attach the scale to. If not specified, the scale will be attached to the default screen.

    MicroPython Code Block:

        .. code-block:: python

            from m5ui import M5Scale
            import lvgl as lv

            m5ui.init()
            scale_0 = M5Scale(x=10, y=10, w=200, h=20, start_pos=0, end_pos=100, tick_count=11, tick_every=2, mode=lv.scale.MODE.HORIZONTAL_TOP, parent=page0)
    """
    def __init__(self, x=..., y=..., w=..., h=..., start_pos=..., end_pos=..., tick_count=..., tick_every=..., show_mode=..., parent=...) -> None:
        ...
    
    def __getattr__(self, name): # -> Callable[..., Any]:
        ...
    


