"""
This type stub file was generated by pyright.
"""

import lvgl as lv

class M5Slider(lv.slider):
    """Create a slider widget.

    :param x: The x position of the slider.
    :param y: The y position of the slider.
    :param w: The width of the slider.
    :param h: The height of the slider.
    :param mode: only `lv.slider.MODE.NORMAL` is supported.
    :param min_value: The minimum value of the slider.
    :param max_value: The maximum value of the slider.
    :param value: The initial value of the slider.
    :param bg_c: The background color of the slider.
    :param color: The color of the slider indicator.
    :param parent: The parent object of the slider. If not specified, it will be set to the active screen.
    """
    def __init__(self, x=..., y=..., w=..., h=..., mode=..., min_value=..., max_value=..., value=..., bg_c=..., color=..., parent=...) -> None:
        ...
    
    def set_style_radius(self, radius: int, part: int) -> None:
        ...
    
    def __getattr__(self, name): # -> Callable[..., Any]:
        ...
    


