"""
This type stub file was generated by pyright.
"""

import lvgl as lv

class M5Switch(lv.switch):
    """Create a switch object.

    :param int x: The x position of the switch.
    :param int y: The y position of the switch.
    :param int w: The width of the switch.
    :param int h: The height of the switch.
    :param int bg_c: The color of the switch in the off state in hexadecimal format.
    :param int bg_c_checked: The color of the switch in the on state in hexadecimal format.
    :param int circle_c: This color refers to the color of the circle on the switch in hexadecimal format.
    :param lv.obj parent: The parent object to attach the switch to. If not specified, the switch will be attached to the default screen.

    UiFlow2 Code Block:

        None

    MicroPython Code Block:

        .. code-block:: python

            from m5ui import M5Switch
            import lvgl as lv

            m5ui.init()
            switch_0 = M5Switch(x=120, y=80, w=60, h=30, bg_c=0xE7E3E7, color=0x2196F3, parent=page0)
    """
    def __init__(self, x=..., y=..., w=..., h=..., bg_c=..., bg_c_checked=..., circle_c=..., parent=...) -> None:
        ...
    
    def set_direction(self, direction): # -> None:
        """Set the direction of the switch.

        :param int direction: The direction of the switch.

            Options:

                - 0: Horizontal
                - 1: Vertical

        UIFlow2 Code Block:

            |set_direction.png|

        MicroPython Code Block:

            .. code-block:: python

                switch_0.set_direction(0)  # Set to horizontal
                switch_0.set_direction(1)  # Set to vertical
        """
        ...
    
    def set_size(self, w, h): # -> None:
        ...
    
    def set_style_radius(self, radius: int, part: int) -> None:
        ...
    
    def set_style_radius(self, radius: int, part: int) -> None:
        ...
    
    def set_style_radius(self, radius: int, part: int) -> None:
        ...
    
    def __getattr__(self, name): # -> Callable[..., Any]:
        ...
    


