"""
This type stub file was generated by pyright.
"""

import lvgl as lv

class M5TextArea(lv.textarea):
    """Create a text area widget.

    :param str text: Initial text content of the text area.
    :param str placeholder: Placeholder text when the text area is empty.
    :param int x: X position of the text area.
    :param int y: Y position of the text area.
    :param int w: Width of the text area.
    :param int h: Height of the text area.
    :param lv.font_t font: Font used for the text.
    :param int bg_c: Background color of the text area.
    :param int border_c: Border color of the text area.
    :param int text_c: Text color of the text area.
    :param lv.obj parent: Parent object of the text area. If not specified, it will be set to the active screen.
    """
    def __init__(self, text=..., placeholder=..., x=..., y=..., w=..., h=..., font=..., bg_c=..., border_c=..., text_c=..., parent=...) -> None:
        ...
    
    def set_style_radius(self, radius: int, part: int) -> None:
        ...
    
    def __getattr__(self, name): # -> Callable[..., Any]:
        ...
    


