package(
    "module",
    (
        "__init__.py",
        "dual_kmeter.py",
        "mbus.py",
        "relay_4.py",
        "module_helper.py",
        "encoder4_motor.py",
        "pps.py",
    ),
    base_path="..",
    opt=0,
)
