"""
This type stub file was generated by pyright.
"""

def read_coils(starting_address, quantity): # -> bytes:
    ...

def read_discrete_inputs(starting_address, quantity): # -> bytes:
    ...

def read_holding_registers(starting_address, quantity): # -> bytes:
    ...

def read_input_registers(starting_address, quantity): # -> bytes:
    ...

def write_single_coil(output_address, output_value): # -> bytes:
    ...

def write_single_register(register_address, register_value, signed=...): # -> bytes:
    ...

def write_multiple_coils(starting_address, value_list): # -> bytes:
    ...

def write_multiple_registers(starting_address, register_values, signed=...): # -> bytes:
    ...

def validate_resp_data(data, function_code, address, value=..., quantity=..., signed=...): # -> bool:
    ...

