"""
This type stub file was generated by pyright.
"""

class uSerial:
    def __init__(self, uart_id, tx, rx, baudrate=..., data_bits=..., stop_bits=..., parity=..., ctrl_pin=..., debug=...) -> None:
        ...
    
    def read_coils(self, slave_addr, starting_addr, coil_qty, timeout=...): # -> list[Any] | None:
        ...
    
    def read_discrete_inputs(self, slave_addr, starting_addr, input_qty, timeout=...): # -> list[Any] | None:
        ...
    
    def read_holding_registers(self, slave_addr, starting_addr, register_qty, signed=..., timeout=...): # -> list[Any] | None:
        ...
    
    def read_input_registers(self, slave_addr, starting_address, register_quantity, signed=..., timeout=...): # -> list[Any] | None:
        ...
    
    def write_single_coil(self, slave_addr, output_address, output_value, timeout=...): # -> bool | None:
        ...
    
    def write_single_register(self, slave_addr, register_address, register_value, signed=..., timeout=...): # -> bool | None:
        ...
    
    def write_multiple_coils(self, slave_addr, starting_address, output_values, timeout=...): # -> bool | None:
        ...
    
    def write_multiple_registers(self, slave_addr, starting_address, register_values, signed=..., timeout=...): # -> bool | None:
        ...
    
    def bytes_to_hex_str(self, bins): # -> LiteralString:
        ...
    
    def print_debug(self, tag, msg): # -> None:
        ...
    
    def close(self): # -> None:
        ...
    


