"""
This type stub file was generated by pyright.
"""

import urequests as requests
import _thread
import time
import micropython
from M5 import Widgets

class ImagePlus(Widgets.Image):
    def __init__(self, url, x, y, enable, period, default_img=..., parent=...) -> None:
        ...
    
    def set_update_enable(self, enable): # -> None:
        ...
    
    def set_update_period(self, period): # -> None:
        ...
    
    def is_valid_image(self): # -> bool:
        ...
    
    def __del__(self): # -> None:
        ...
    


