"""
This type stub file was generated by pyright.
"""

import socket

class Response:
    def __init__(self, f) -> None:
        ...
    
    def close(self): # -> None:
        ...
    
    @property
    def content(self):
        ...
    
    @property
    def text(self): # -> str:
        ...
    
    def json(self): # -> Any:
        ...
    


def request(method, url, data=..., json=..., headers=..., stream=..., auth=..., timeout=..., parse_headers=...):
    ...

def head(url, **kw):
    ...

def get(url, **kw):
    ...

def post(url, **kw):
    ...

def put(url, **kw):
    ...

def patch(url, **kw):
    ...

def delete(url, **kw):
    ...

def urlencode(query): # -> LiteralString:
    ...

