"""
This type stub file was generated by pyright.
"""

class AIN4Module:
    """! Module AIN4 is a Slide Potentiometer with color indicator.

    @en Module AIN4 英文介绍
    @cn Module AIN4 中文介绍

    @color #0FE6D7
    @link https://docs.m5stack.com/en/module/AIN4-20mA%20Module%2013.2
    @image https://static-cdn.m5stack.com/resource/docs/products/module/AIN4-20mA%20Module%2013.2/img-ddec758e-78ce-43e8-9af7-bc101f3dc175.webp
    @category module

    @example

    """
    _AIN_ADDR = ...
    _AIN_ADC_RAW_REG = ...
    _AIN_CURRENT_REG = ...
    _AIN_CAL_REG = ...
    _AIN_FW_VERSION_REG = ...
    _AIN_I2C_ADDR_REG = ...
    def __init__(self, address: int | list | tuple = ...) -> None:
        """! Init I2C Module AIN 4-20mA I2C Address.

        @param i2c I2C port to use.
        @param address I2C address of the AIN4Module.
        """
        ...
    
    def get_adc_raw_value(self, channel: int = ...) -> int:
        """! Get ADC raw value (12-bit).

        Retrieves the raw ADC value from the specified channel.

        @param channel: The channel number (1 to 4) to read the ADC value from.
        @return The 12-bit raw ADC value.

        @raise ValueError: If the channel is not in the range 1 to 4.
        """
        ...
    
    def get_current_value(self, channel: int = ...) -> int:
        """! Get AIN 4-20mA current value.

        Retrieves the current value (in mA) from the specified channel.

        @param channel: The channel number (1 to 4) to read the current value from.
        @return The current value in mA, rounded to two decimal places.

        @raise ValueError: If the channel is not in the range 1 to 4.
        """
        ...
    
    def set_cal_current(self, channel: int, val: int) -> None:
        """! Set calibration current for a given channel.

        Sets the calibration current for the specified channel.

        @param channel: The channel number (1 to 4) to set the calibration for.
        @param val: The calibration current value, ranging from 4 to 20 mA.

        @raise ValueError: If the channel is not in the range 1 to 4, or if the value is not between 4 and 20 mA.
        """
        ...
    
    def get_firmware_version(self) -> int:
        """! Get firmware version.

        Retrieves the firmware version of the AIN 4-20mA module.

        @return The firmware version as an integer.
        """
        ...
    
    def get_i2c_address(self) -> int:
        """! Get I2C address.

        Retrieves the current I2C address of the AIN 4-20mA module.

        @return The I2C address in hexadecimal format.
        """
        ...
    
    def set_i2c_address(self, addr: int) -> None:
        """! Set I2C address.

        Sets a new I2C address for the AIN 4-20mA module.

        @param addr: The new I2C address, must be between 0x08 and 0x77.

        @raise ValueError: If the address is not within the range 0x08 to 0x77.
        """
        ...
    


