"""
This type stub file was generated by pyright.
"""

class _Expander:
    REG_MICROPHONE_STATUS = ...
    REG_HEADPHONE_MODE = ...
    REG_HEADPHONE_INSERT_STATUS = ...
    REG_RGB_BRIGHTNESS = ...
    REG_RGB_LED = ...
    REG_FLASH_WRITE = ...
    REG_FIRMWARE_VERSION = ...
    REG_I2C_ADDRESS = ...
    AUDIO_MIC_CLOSE = ...
    AUDIO_MIC_OPEN = ...
    AUDIO_HPMODE_NATIONAL = ...
    AUDIO_HPMODE_AMERICAN = ...
    def __init__(self, i2c, address=...) -> None:
        ...
    
    def set_mic_status(self, status: int): # -> None:
        ...
    
    def set_hp_mode(self, mode: int): # -> None:
        ...
    
    def set_color(self, num: int, color: int): # -> None:
        ...
    
    def fill_color(self, color: int): # -> None:
        ...
    
    def set_brightness(self, br: int): # -> None:
        ...
    
    def set_flash_write_back(self): # -> None:
        ...
    
    def set_i2c_address(self, address: int): # -> None:
        ...
    
    def get_mic_status(self): # -> int:
        ...
    
    def get_hp_mode(self): # -> int:
        ...
    
    def get_hp_insert_status(self): # -> int:
        ...
    
    def get_firmware_version(self) -> int:
        ...
    
    def get_i2c_address(self): # -> int:
        ...
    
    def write_register(self, reg: int, data: int) -> None:
        ...
    
    def read_register(self, reg: int) -> int:
        ...
    


class AudioModule:
    """Initialize the audio module.

    :param i2s_port: I2S port number.
    :param sample_rate: Sample rate (default is 16000).
    :param i2s_sck: I2S clock pin.
    :param i2s_ws: I2S word select pin.
    :param i2s_di: I2S data input pin.
    :param i2s_do: I2S data output pin.
    :param i2s_mclk: I2S master clock pin.
    :param work_mode: Work mode (0: headphone, 1: line in).
    :param offset: Generally speaking, when using line in, offset is False; if the input is connected to an ADC microphone, offset is True. (Only valid in line in mode).
    :param mux: Select the TRRS plug to be used. (default is MUX_NATIONAL).

    UiFlow2 Code Block:

        |init.png|

    MicroPython Code Block:

        .. code-block:: python

            from module import AudioModule

            audio_0 = AudioModule(0, 16000, i2s_sck=7, i2s_ws=6, i2s_di=14, i2s_do=13, i2s_mclk=0, work_mode=AudioModule.MODE_HEADPHONE, offset=False, mux=AudioModule.MUX_NATIONAL)
    """
    MUX_NATIONAL = ...
    MUX_AMERICAN = ...
    MODE_LINE = ...
    MODE_HEADPHONE = ...
    MONO = ...
    STEREO = ...
    def __init__(self, i2s_port, sample_rate=..., i2s_sck=..., i2s_ws=..., i2s_di=..., i2s_do=..., i2s_mclk=..., work_mode=..., offset=..., mux=...) -> None:
        ...
    
    def play_wav_file(self, file: str) -> None:
        """Play a WAV file.

        :param str file: The path of the WAV file to play.
        :return: None

        UiFlow2 Code Block:

            |play_wav_file.png|

        MicroPython Code Block:

            .. code-block:: python

                audio_0.play_wav_file("/flash/res/audio/test.wav")
        """
        ...
    
    def tone(self, freq: int, duration: int) -> None:
        """Play simple tone sound.

        :param int freq: Frequency of the tone in Hz.
        :param int duration: Duration of the tone in milliseconds.
        :return: None

        UiFlow2 Code Block:

            |tone.png|

        MicroPython Code Block:

            .. code-block:: python

                audio_0.tone(2000, 50)
        """
        ...
    
    def play_wav(self, buf: bytes, duration: int = ...) -> None:
        """Play a WAV buffer.

        :param bytes buf: The WAV buffer to play.
        :param int duration: Duration of the WAV buffer in milliseconds. when duration is -1, it will play until stopped. (default is -1).
        :return: None

        UiFlow2 Code Block:

            |play_wav.png|

        MicroPython Code Block:

            .. code-block:: python

                audio_0.play_wav(wav_buffer, duration=1000)
        """
        ...
    
    def play_raw(self, buf: bytes, rate: int = ..., bits: int = ..., channel: int = ..., duration: int = ...) -> None:
        """Play a pcm buffer.

        :param bytes buf: The PCM buffer to play.
        :param int rate: Sample rate (default is 16000).
        :param int bits: Bit depth (default is 16).
        :param int channel: Number of channels (default is 2).
        :param int duration: Duration of the PCM buffer in milliseconds. when duration is -1, it will play until stopped. (default is -1).
        :return: None

        UiFlow2 Code Block:

            |play_raw.png|

        MicroPython Code Block:

            .. code-block:: python

                audio_0.play_raw(pcm_buffer, rate=16000, bits=16, channel=2, duration=1000)
        """
        ...
    
    def pause(self) -> None:
        """Pause the playback.

        UiFlow2 Code Block:

            |pause.png|

        MicroPython Code Block:

            .. code-block:: python

                audio.tone(2000, 100)
                time.sleep(0.05)
                audio_0.pause()
                time.sleep(0.05)
                audio_0.resume()
        """
        ...
    
    def resume(self): # -> None:
        """Resume the playback.

        UiFlow2 Code Block:

            |resume.png|

        MicroPython Code Block:

            .. code-block:: python

                audio.tone(2000, 100)
                time.sleep(0.05)
                audio_0.pause()
                time.sleep(0.05)
                audio_0.resume()
        """
        ...
    
    def stop(self): # -> None:
        """Stop the playback.

        UiFlow2 Code Block:

            |stop.png|

        MicroPython Code Block:

            .. code-block:: python

                audio.tone(2000, 100)
                time.sleep(0.05)
                audio_0.stop()
        """
        ...
    
    def get_volume(self) -> int:
        """Get the speaker volume level.

        :return: The volume level (0-100).

        UiFlow2 Code Block:

            |get_volume.png|

        MicroPython Code Block:

            .. code-block:: python

                audio_0.get_volume()
        """
        ...
    
    def set_volume(self, volume): # -> None:
        """Set the speaker volume level.

        :param int volume: The volume level (0-100).

        UiFlow2 Code Block:

            |set_volume.png|

        MicroPython Code Block:

            .. code-block:: python

                audio_0.set_volume(50)
        """
        ...
    
    def record_wav_file(self, path: str, rate: int = ..., bits: int = ..., channel: int = ..., duration: int = ...): # -> None:
        """Record audio to a WAV file.

        :param str path: The path to save the WAV file.
        :param int rate: Sample rate (default is 16000).
        :param int bits: Bit depth (default is 16).
        :param int channel: Number of channels (default is 2).
        :param int duration: Duration of the recording in milliseconds (default is 3000).

        UiFlow2 Code Block:

            |record_wav_file.png|

        MicroPython Code Block:

            .. code-block:: python

                audio_0.record_wav_file("/flash/res/audio/test.wav", rate=16000, bits=16, channel=2, duration=3000)
        """
        ...
    
    def record(self, rate=..., bits=..., channel=..., duration=...):
        """Record audio to a PCM buffer.

        :param int rate: Sample rate (default is 16000).
        :param int bits: Bit depth (default is 16).
        :param int channel: Number of channels (default is 2).
        :param int duration: Duration of the recording in milliseconds (default is 3000).

        UiFlow2 Code Block:

            |record.png|

        MicroPython Code Block:

            .. code-block:: python

                audio_0.record(rate=16000, bits=16, channel=2, duration=3000)
        """
        ...
    
    @property
    def pcm_buffer(self) -> bytes:
        """Get the PCM buffer.

        :return: The PCM buffer.

        UiFlow2 Code Block:

            |pcm_buffer.png|

        MicroPython Code Block:

            .. code-block:: python

                audio_0.pcm_buffer
        """
        ...
    
    def set_color(self, num: int, color: int): # -> None:
        """Set the RGB LED color.

        :param int num: The LED number (0-2).
        :param int color: The color value (0xRRGGBB).

        UiFlow2 Code Block:

            |set_color.png|

        MicroPython Code Block:

            .. code-block:: python

                audio_0.set_color(0, 0xFF0000)
        """
        ...
    
    def fill_color(self, color: int): # -> None:
        """Fill all RGB LEDs with the same color.

        :param int color: The color value (0xRRGGBB).

        UiFlow2 Code Block:

            |fill_color.png|

        MicroPython Code Block:

            .. code-block:: python

                audio_0.fill_color(0xFF0000)
        """
        ...
    
    def set_brightness(self, br: int): # -> None:
        """Set the RGB LED brightness.

        :param int br: The brightness level (0-100).

        UiFlow2 Code Block:

            |set_brightness.png|

        MicroPython Code Block:

            .. code-block:: python

                audio_0.set_brightness(50)
        """
        ...
    
    def deinit(self): # -> None:
        ...
    


