"""
This type stub file was generated by pyright.
"""

REG_MTR1_CTRL = ...
REG_MTR2_CTRL = ...
REG_ENCODER1 = ...
REG_ENCODER2 = ...
REG_SERVO_ANGLE = ...
REG_SERVO_PULSE = ...
class Bala2Module:
    """Create an Bala2Module object.

    :param int timer_id: The Timer ID. Range: 0~3. Default is 0.

    UiFlow2 Code Block:

        |init.png|

    MicroPython Code Block:

        .. code-block:: python

            from module import Bala2Module

            module_bala2_0 = Bala2Module(timer_id = 0)
    """
    def __init__(self, timer_id: int = ...) -> None:
        ...
    
    def calibrate(self) -> None:
        """Calibrate sensor

        UiFlow2 Code Block:

            |calibrate.png|

        MicroPython Code Block:

            .. code-block:: python

                module_bala2_0.calibrate()
        """
        ...
    
    def set_motor_speed(self, left: int, right: int) -> None:
        """Set motor speed.

        :param int left: The speed of the left motor. Range: -1023 ~ 1023.
        :param int right: The speed of the right motor. Range: -1023 ~ 1023.

        UiFlow2 Code Block:

            |set_motor_speed.png|

        MicroPython Code Block:

            .. code-block:: python

                module_bala2_0.set_motor_speed(left, right)
        """
        ...
    
    def set_encoder_value(self, left: int, right: int) -> None:
        """Set encoder value.

        :param int left: The value of the left encoder. Range: -2^31 ~ 2^31.
        :param int right: The value of the right encoder. Range: -2^31 ~ 2^31.

        UiFlow2 Code Block:

            |set_encoder_value.png|

        MicroPython Code Block:

            .. code-block:: python

                module_bala2_0.set_encoder_value(left, right)
        """
        ...
    
    def get_encoder_value(self) -> tuple[int, int]:
        """The left, right encoder value returned in a 2-tuple

        :returns: left, right encoder value
        :rtype: tuple[int, int]

        The encoder count increases when rotating forward and decreases when rotating backward.
        A full rotation results in a value change of 420.

        UiFlow2 Code Block:

            |get_encoder_value.png|

        MicroPython Code Block:

            .. code-block:: python

                module_bala2_0.get_encoder_value()
        """
        ...
    
    def set_servo_angle(self, pos: int, angle: int) -> None:
        """Set servo angle.

        :param int pos: The position of the output cahnnel. Range: 1 ~ 4.
        :param int angle: The value of the right encoder. Range: 0 ~ 180.

        UiFlow2 Code Block:

            |set_servo_angle.png|

        MicroPython Code Block:

            .. code-block:: python

                module_bala2_0.set_servo_angle(pos, angle)
        """
        ...
    
    def set_servo_pulse(self, pos: int, width: int) -> None:
        """Set pulse width for PWM signal.

        :param int pos: The position of the output cahnnel. Range: 1 ~ 4.
        :param int width: The value of the PWM signal witdh. Range: 500 ~ 2500, corresponds to 0.5ms ~ 2.5ms.

        The PWM frequency is fixed at 50Hz, with a period of 20ms.

        UiFlow2 Code Block:

            |set_servo_pulse.png|

        MicroPython Code Block:

            .. code-block:: python

                module_bala2_0.set_servo_pulse(pos, width)
        """
        ...
    
    def start(self) -> None:
        """Start the balance control task.

        UiFlow2 Code Block:

            |start.png|

        MicroPython Code Block:

            .. code-block:: python

                module_bala2_0.start()
        """
        ...
    
    def stop(self) -> None:
        """Stop the balance control task.

        UiFlow2 Code Block:

            |stop.png|

        MicroPython Code Block:

            .. code-block:: python

                module_bala2_0.stop()
        """
        ...
    
    def get_angle(self) -> float:
        """The angle of the car.

        :returns: The angle of the car
        :rtype: int

        UiFlow2 Code Block:

            |get_angle.png|

        MicroPython Code Block:

            .. code-block:: python

                module_bala2_0.get_angle()
        """
        ...
    
    def set_angle_pid(self, kp: float, ki: float, kd: float) -> None:
        """Set angle loop PID parameters.

        :param float kp: Proportional gain
        :param float ki: Integral gain
        :param float kd: Derivative gain

        UiFlow2 Code Block:

            |set_angle_pid.png|

        MicroPython Code Block:

            .. code-block:: python

                module_bala2_0.set_angle_pid(kp, ki, kd)
        """
        ...
    
    def get_angle_pid(self) -> tuple[float, float, float]:
        """The angle loop PID parameters returned in a 3-tuple

        :returns: kp, ki, kd parameters
        :rtype: tuple[float, float, float]

        UiFlow2 Code Block:

            |get_angle_pid.png|

        MicroPython Code Block:

            .. code-block:: python

                module_bala2_0.get_angle_pid()
        """
        ...
    
    def set_angle_pid_target(self, angle: float = ...) -> None:
        """Set angle loop PID control target.

        :param float angle: The angle of the angle loop PID control target. Default is 0.

        UiFlow2 Code Block:

            |set_angle_pid_target.png|

        MicroPython Code Block:

            .. code-block:: python

                module_bala2_0.set_angle_pid_target(angle)
        """
        ...
    
    def get_angle_pid_target(self) -> float:
        """Get angle loop PID control target

        :returns: The angle loop PID control target
        :rtype: float

        UiFlow2 Code Block:

            |get_angle_pid_target.png|

        MicroPython Code Block:

            .. code-block:: python

                module_bala2_0.get_angle_pid_target()
        """
        ...
    
    def set_speed_pid(self, kp: float, ki: float, kd: float) -> None:
        """Set speed loop PID parameters.

        :param float kp: Proportional gain
        :param float ki: Integral gain
        :param float kd: Derivative gain

        UiFlow2 Code Block:

            |set_speed_pid.png|

        MicroPython Code Block:

            .. code-block:: python

                module_bala2_0.set_speed_pid(kp, ki, kd)
        """
        ...
    
    def get_speed_pid(self) -> tuple[float, float, float]:
        """The speed loop PID parameters returned in a 3-tuple

        :returns: kp, ki, kd parameters
        :rtype: tuple[float, float, float]

        UiFlow2 Code Block:

            |get_speed_pid.png|

        MicroPython Code Block:

            .. code-block:: python

                module_bala2_0.get_speed_pid()
        """
        ...
    
    def set_speed_pid_target(self, speed: float = ...) -> None:
        """Set speed loop PID control target.

        :param float speed: The speed of the speed loop PID control target. Default is 0.

        UiFlow2 Code Block:

            |set_speed_pid_target.png|

        MicroPython Code Block:

            .. code-block:: python

                module_bala2_0.set_speed_pid_target(speed)
        """
        ...
    
    def get_speed_pid_target(self) -> float:
        """Get speed loop PID control target

        :returns: The speed loop PID control target
        :rtype: float

        UiFlow2 Code Block:

            |get_speed_pid_target.png|

        MicroPython Code Block:

            .. code-block:: python

                module_bala2_0.get_speed_pid_target()
        """
        ...
    
    def set_turn_speed(self, speed: float) -> None:
        """Set turn speed.

        :param float speed: The speed of the left and right motor offset

        UiFlow2 Code Block:

            |set_turn_speed.png|

        MicroPython Code Block:

            .. code-block:: python

                module_bala2_0.set_turn_speed(speed)
        """
        ...
    


