"""
This type stub file was generated by pyright.
"""

from driver.mcp2515.mcp2515_spi import MCP2515_CAN

ERROR_OK = ...
ERROR_FAIL = ...
ERROR_ALLTXBUSY = ...
ERROR_FAILINIT = ...
ERROR_FAILTX = ...
ERROR_NOMSG = ...
CAN_SFF_MASK = ...
CAN_EFF_MASK = ...
MBusIO = ...
iomap = ...
class CommuModuleCAN(MCP2515_CAN):
    """Create an CommuModuleCAN object

    :param int mode: The CAN mode to use(NORMAL, LISTEN_ONLY), Default is NORMAL.

        Options:
            - ``NORMAL``: Normal mode
            - ``LISTEN_ONLY``: Listen only mode

    :param int baudrate: The baudrate to use, Default is CAN_1000KBPS.

        Options:
            - ``CAN_5KBPS``: 5Kbps
            - ``CAN_10KBPS``: 10Kbps
            - ``CAN_20KBPS``: 20Kbps
            - ``CAN_31K25BPS``: 31.25Kbps
            - ``CAN_33KBPS``: 33Kbps
            - ``CAN_40KBPS``: 40Kbps
            - ``CAN_50KBPS``: 50Kbps
            - ``CAN_80KBPS``: 80Kbps
            - ``CAN_83K3BPS``: 83.33Kbps
            - ``CAN_95KBPS``: 95Kbps
            - ``CAN_100KBPS``: 100Kbps
            - ``CAN_125KBPS``: 125Kbps
            - ``CAN_200KBPS``: 200Kbps
            - ``CAN_250KBPS``: 250Kbps
            - ``CAN_500KBPS``: 500Kbps
            - ``CAN_1000KBPS``: 1Mbps


    :param int spi_baud: The SPI baudrate to use, Default is 8000000.
    :param int canIDMode: The CAN ID mode to use(MCP_STDEXT, MCP_EXTDONLY), Default is MCP_STDEXT.

        Options:
            - ``MCP_STDEXT``: Standard and Extended
            - ``MCP_EXTDONLY``: Extended only

    :param bool debug: Whether to enable debug mode, Default is False.

    UiFlow2 Code Block:

        |init.png|

    MicroPython Code Block:

        .. code-block:: python

            from module import CommuModuleCAN

            commu = CommuModuleCAN(CommuModule.NORMAL, baudrate=16)

    """
    NORMAL = ...
    LISTEN_ONLY = ...
    MCP_STDEXT = ...
    MCP_8MHZ = ...
    CAN_5KBPS = ...
    CAN_10KBPS = ...
    CAN_20KBPS = ...
    CAN_31K25BPS = ...
    CAN_33KBPS = ...
    CAN_40KBPS = ...
    CAN_50KBPS = ...
    CAN_80KBPS = ...
    CAN_83K3BPS = ...
    CAN_95KBPS = ...
    CAN_100KBPS = ...
    CAN_125KBPS = ...
    CAN_200KBPS = ...
    CAN_250KBPS = ...
    CAN_500KBPS = ...
    CAN_1000KBPS = ...
    def __init__(self, mode: int = ..., baudrate: int = ..., spi_baud=..., canIDMode: int = ..., debug=...) -> None:
        ...
    
    def info(self): # -> int:
        """Get the state of error information.

        :returns: The current error information.
        :rtype: str

        UiFlow2 Code Block:

            |info.png|

        MicroPython Code Block:

            .. code-block:: python

                commu.info()
        """
        ...
    
    def reset(self) -> None:
        ...
    
    def get_irq_state(self) -> bool:
        ...
    
    def any(self) -> bool:
        """Check if any message is available.

        :returns: The current message availability.
        :rtype: bool

        UiFlow2 Code Block:

            |any.png|

        MicroPython Code Block:

            .. code-block:: python

                commu.any()
        """
        ...
    
    def clear_interrupts(self): # -> None:
        ...
    
    def recv(self, fifo=..., list=..., timeout=...): # -> list[Any] | Literal[True] | None:
        """Read a message from the CAN bus.

        :param int fifo: The fifo is an integer, it can be any number and compatible with Pyb.CAN
        :param list list: list is an optional list object to be used as the return value.
        :param int timeout: timeout is the timeout in milliseconds to wait for the receive.
        :returns: Tuple containing (can_id, is_extended, is_rtr, fmi, data)
        :rtype: tuple

            - The id of the message.
            - A boolean that indicates if the message ID is standard or extended.
            - A boolean that indicates if the message is an RTR message.
            - The FMI (Filter Match Index) value.
            - An array containing the data.

        UiFlow2 Code Block:

            |recv_message.png|

            |recv_message_into.png|

        MicroPython Code Block:

            .. code-block:: python

                commu.recv(0)

                buf = bytearray(8)
                lst = [0, 0, 0, 0, memoryview(buf)]
                # No heap memory is allocated in the following call
                commu.recv(0, lst)
        """
        ...
    
    def send(self, data: str, can_id: int, extframe: bool = ...) -> int:
        """Send a message to the CAN bus.

        :param str data: The message data.
        :param int can_id: The CAN ID.
        :param bool extframe: Whether to use extended frame format.
        :returns: The message data.
        :rtype: str

        UiFlow2 Code Block:

            |send.png|

        MicroPython Code Block:

            .. code-block:: python

                commu.send('uiflow2', 0, extframe=False)
        """
        ...
    
    def commu_can_debug(self, enable=...) -> None:
        ...
    
    def deinit(self): # -> None:
        ...
    
    def commu_can_config_rate(self, canSpeed: int, canClock: int = ...) -> int:
        ...
    


class CommuModuleRS485:
    def __new__(cls, id, **kwargs):
        ...
    


class CommuModuleI2C:
    def __new__(cls, id, **kwargs):
        ...
    


