"""
This type stub file was generated by pyright.
"""

SLAVE_ADDR = ...
MOTOR_ADDR_BASE = ...
ENCODER_ADDR_BASE = ...
MOTOR_COUNT = ...
class DCMotorModule:
    """Create an DCMotorModule object.

    UiFlow2 Code Block:

        |init.png|

    MicroPython Code Block:

        .. code-block:: python

            from module import DCMotorModule

            dcmotor_module = DCMotorModule()
    """
    def __init__(self) -> None:
        ...
    
    def set_motor_speed(self, id: int, speed: int) -> None:
        """Set speed of motor.

        :param int id: port num, range: 1~4
        :param int speed: motor speed, range: -255~255

        UiFlow2 Code Block:

            |set_motor_speed.png|

        MicroPython Code Block:

            .. code-block:: python

                dcmotor_module.set_motor_speed(id, speed)
        """
        ...
    
    def set_motor_speed_percent(self, id: int, percent: float) -> None:
        """Set motor speed as a percentage.

        :param int id: port num, range: 1~4.
        :param float percent: motor speed percent, range: -100.0% ~ +100.0%.

        UiFlow2 Code Block:

            |set_motor_speed_percent.png|

        MicroPython Code Block:

            .. code-block:: python

                dcmotor_module.set_motor_speed_percent(id, percent)
        """
        ...
    
    def get_encoder(self, id: int) -> int:
        """Get encoder count.

        :param int id: port num, range: 1~4.
        :returns: encoder count.
        :rtype: int

        UiFlow2 Code Block:

            |get_encoder.png|

        MicroPython Code Block:

            .. code-block:: python

                dcmotor_module.get_encoder()
        """
        ...
    
    def clear_encoder(self, id: int) -> bool:
        """Clear encoder value.

        UiFlow2 Code Block:

            |clear_encoder.png|

        MicroPython Code Block:

            .. code-block:: python

                dcmotor_module.clear_encoder()
        """
        ...
    


