"""
This type stub file was generated by pyright.
"""

from driver.dmx512 import DMX512

MBusIO = ...
iomap = ...
class DMX512Module(DMX512):
    def __init__(self, id=..., mode=...) -> None:
        ...
    


