"""
This type stub file was generated by pyright.
"""

class ECGModule:
    """Create an ECGModule object.

    :param int id: UART id.
    :param int tx: the UART TX pin.
    :param int rx: the UART RX pin.

    UiFlow2 Code Block:

        |init.png|

    MicroPython Code Block:

        .. code-block:: python

            from module import ECGModule

            module_ecg = ECGModule(id = 1, tx = 7, rx = 1)
    """
    def __init__(self, id: int = ..., tx: int = ..., rx: int = ...) -> None:
        ...
    
    def poll_data(self) -> None:
        """Poll data.

        This function checks for new data from the module and
        should be called repeatedly in a loop to ensure continuous
        data retrieval.

        UiFlow2 Code Block:

            |poll_data.png|

        MicroPython Code Block:

            .. code-block:: python

                module_ecg.poll_data()
        """
        ...
    
    def read_heartrate(self) -> int:
        """Read heartrate.

        :returns: heart rate
        :rtype: int

        If heart rate is no valid, return -1.

        UiFlow2 Code Block:

            |read_heartrate.png|

        MicroPython Code Block:

            .. code-block:: python

                module_ecg.read_heartrate()
        """
        ...
    
    def read_raw_ecg_data(self) -> list:
        """Read raw ECG data.

        :returns: ECG data
        :rtype: list

        UiFlow2 Code Block:

            |read_raw_ecg_data.png|

        MicroPython Code Block:

            .. code-block:: python

                module_ecg.read_raw_ecg_data()
        """
        ...
    


