"""
This type stub file was generated by pyright.
"""

class Encoder4MotorModule:
    """Create an Encoder4MotorModule object

    :param int address: The I2C address of the device. Default is 0x24.

    UiFlow2 Code Block:

        |init.png|

    MicroPython Code Block:

        .. code-block:: python

            from module import Encoder4MotorModule

            encoder4_motor = Encoder4MotorModule(0x24)
    """
    DEVADDR = ...
    MTR_PWM_DUTY = ...
    MTR_ENCODER = ...
    MTR_SPEED = ...
    MTR1_MODE = ...
    MTR2_MODE = ...
    MTR3_MODE = ...
    MTR4_MODE = ...
    VIN_AMPS_FLT = ...
    VIN_ADC8 = ...
    VIN_ADC12 = ...
    VIN_AMPS_INT = ...
    ENCODER_AB = ...
    SOFT_START = ...
    FIRM_VER = ...
    I2C_ADDR = ...
    NORMAL_MODE = ...
    POSITION_MODE = ...
    SPEED_MODE = ...
    def __init__(self, address: int = ...) -> None:
        ...
    
    def available(self): # -> None:
        ...
    
    def set_motor_mode(self, motor, mode): # -> None:
        """Set the motor mode.

        :param int motor: The motor to set the mode.
        :param int mode: The mode of the motor.

            Options:
                - ``NORMAL_MODE``: 0
                - ``POSITION_MODE``: 1
                - ``SPEED_MODE``: 2

        UiFlow2 Code Block:

            |set_motor_mode.png|

        MicroPython Code Block:

            .. code-block:: python

                encoder4_motor.set_motor_mode(0, encoder4_motor.NORMAL_MODE)
        """
        ...
    
    def set_all_motors_mode(self, mode): # -> None:
        """Set the mode of all motors.

        :param int mode: The mode of the motors.

            Options:
                - ``NORMAL_MODE``: 0
                - ``POSITION_MODE``: 1
                - ``SPEED_MODE``: 2

        UiFlow2 Code Block:

            |set_all_motors_mode.png|

        MicroPython Code Block:

            .. code-block:: python

                encoder4_motor.set_all_motors_mode(encoder4_motor.NORMAL_MODE)
        """
        ...
    
    def set_motor_pwm_dutycycle(self, motor, duty): # -> None:
        """Set the PWM duty cycle of a motor.

        :param int motor: The motor to set the PWM duty cycle.
        :param int duty: The PWM duty cycle.

        UiFlow2 Code Block:

            |set_motor_pwm_dutycycle.png|

        MicroPython Code Block:

            .. code-block:: python

                encoder4_motor.set_motor_pwm_dutycycle(0, 127)
        """
        ...
    
    def get_motor_encoder_value(self, pos): # -> Any:
        """Get the encoder value of a motor.

        :param int pos: The motor to get the encoder value.

        :returns: The encoder value.
        :rtype: int

        UiFlow2 Code Block:

            |get_motor_encoder_value.png|

        MicroPython Code Block:

            .. code-block:: python

                encoder4_motor.get_motor_encoder_value(0)
        """
        ...
    
    def set_motor_encoder_value(self, pos, value): # -> None:
        """Set the encoder value of a motor.

        :param int pos: The motor to set the encoder value.
        :param int value: The encoder value.

        UiFlow2 Code Block:

            |set_motor_encoder_value.png|

        MicroPython Code Block:

            .. code-block:: python

                encoder4_motor.set_motor_encoder_value(0, 100)
        """
        ...
    
    def get_encoder_mode(self):
        """Get the encoder mode.

        :return: The encoder mode.
        :rtype: int

        UiFlow2 Code Block:

            |get_encoder_mode.png|

        MicroPython Code Block:

            .. code-block:: python

                encoder4_motor.get_encoder_mode()
        """
        ...
    
    def set_encoder_mode(self, mode): # -> None:
        """Set the encoder mode.

        :param int mode: The mode of the encoder.

            Options:
                - ``AB``: 0
                - ``BA``: 1

        UiFlow2 Code Block:

            |set_encoder_mode.png|

        MicroPython Code Block:

            .. code-block:: python

                encoder4_motor.set_encoder_mode(0x00)
        """
        ...
    
    def get_motor_speed_value(self, pos):
        """Get the speed value of a motor.

        :param int pos: The motor to get the speed value.

        :returns: The speed value.
        :rtype: int

        UiFlow2 Code Block:

            |get_motor_speed_value.png|

        MicroPython Code Block:

            .. code-block:: python

                encoder4_motor.get_motor_speed_value(0)
        """
        ...
    
    def set_position_encoder_value(self, pos, value): # -> None:
        """Set the position encoder value of a motor.

        :param int pos: The motor to set the position encoder value.
        :param int value: The position encoder value.

        UiFlow2 Code Block:

            |set_position_encoder_value.png|

        MicroPython Code Block:

            .. code-block:: python

                encoder4_motor.set_position_encoder_value(0, 100)
        """
        ...
    
    def set_position_max_speed_value(self, pos, value): # -> None:
        """Set the maximum speed value of a motor.

        :param int pos: The motor to set the maximum speed value.
        :param int value: The maximum speed value.

        UiFlow2 Code Block:

            |set_position_max_speed_value.png|

        MicroPython Code Block:

            .. code-block:: python

                encoder4_motor.set_position_max_speed_value(0, 127)
        """
        ...
    
    def get_position_pid_value(self, pos): # -> list[Any]:
        """Get the position PID value of a motor.

        :param int pos: The motor to get the position P,I,D value.

        :returns: The position PID value.
        :rtype: list[int, int, int]

        UiFlow2 Code Block:

            |get_position_PID_value.png|

        MicroPython Code Block:

            .. code-block:: python

                encoder4_motor.get_position_pid_value(0)
        """
        ...
    
    def set_position_pid_value(self, pos, p, i, d): # -> None:
        """Set the position P,I,D value of a motor.

        :param int pos: The motor to set the position P,I,D value.
        :param int p: The P value.
        :param int i: The I value.
        :param int d: The D value.

        UiFlow2 Code Block:

            |set_position_PID_value.png|

        MicroPython Code Block:

            .. code-block:: python

                encoder4_motor.set_position_pid_value(0, 100, 100, 100)
        """
        ...
    
    def get_speed_pid_value(self, pos): # -> list[Any]:
        """Get the speed PID value of a motor.

        :param int pos: The motor to get the speed P,I,D value.

        :returns: The speed P,I,D value.
        :rtype: list[int, int, int]

        UiFlow2 Code Block:

            |get_speed_PID_value.png|

        MicroPython Code Block:

            .. code-block:: python

                encoder4_motor.get_speed_PID_value(0)
        """
        ...
    
    def set_speed_pid_value(self, pos, p, i, d): # -> None:
        """Set the speed PID value of a motor.

        :param int pos: The motor to set the speed PID value.
        :param int p: The P value.
        :param int i: The I value.
        :param int d: The D value.

        UiFlow2 Code Block:

            |set_speed_PID_value.png|

        MicroPython Code Block:

            .. code-block:: python

                encoder4_motor.set_speed_PID_value(0, 100, 100, 100)
        """
        ...
    
    def set_speed_point_value(self, pos, point): # -> None:
        """Set the speed point value of a motor.

        :param int pos: The motor to set the speed point value.
        :param int point: The speed point value.

        UiFlow2 Code Block:

            |set_speed_point_value.png|

        MicroPython Code Block:

            .. code-block:: python

                encoder4_motor.set_speed_point_value(0, 127)
        """
        ...
    
    def get_vin_current_float_value(self): # -> Any:
        """Get the input current value in float.

        :return: The input current value.
        :rtype: float

        UiFlow2 Code Block:

            |get_vin_current_float_value.png|

        MicroPython Code Block:

            .. code-block:: python

                encoder4_motor.get_vin_current_float_value()
        """
        ...
    
    def get_vin_current_int_value(self): # -> Any:
        """Get the input current value in int.

        :return: The input current value.
        :rtype: int

        UiFlow2 Code Block:

            |get_vin_current_int_value.png|

        MicroPython Code Block:

            .. code-block:: python

                encoder4_motor.get_vin_current_int_value()
        """
        ...
    
    def get_vin_adc_raw8_value(self):
        """Get the input voltage ADC raw value in 8-bit.

        :return: The input voltage ADC raw value.
        :rtype: int

        UiFlow2 Code Block:

            |get_vin_adc_raw8_value.png|

        MicroPython Code Block:

            .. code-block:: python

                encoder4_motor.get_vin_adc_raw8_value()
        """
        ...
    
    def get_vin_adc_raw12_value(self): # -> Any:
        """Get the input voltage ADC raw value in 12-bit.

        :return: The input voltage ADC raw value.
        :rtype: int

        UiFlow2 Code Block:

            |get_vin_adc_raw12_value.png|

        MicroPython Code Block:

            .. code-block:: python

                encoder4_motor.get_vin_adc_raw12_value()
        """
        ...
    
    def get_vin_voltage(self): # -> Any:
        """Get the input voltage value.

        :return: The input voltage value.
        :rtype: float

        UiFlow2 Code Block:

            |get_vin_voltage.png|

        MicroPython Code Block:

            .. code-block:: python

                encoder4_motor.get_vin_voltage()
        """
        ...
    
    def get_device_spec(self, info):
        """Get the device specification.

        :param int info: The information to get.

        :returns: The device specification(firmware version/I2C address).
        :rtype: int

        UiFlow2 Code Block:

            |get_device_spec.png|

        MicroPython Code Block:

            .. code-block:: python

                encoder4_motor.get_device_spec(0xFE)
        """
        ...
    
    def get_soft_start_state(self, motor): # -> bool:
        """Get the soft start state of a motor.

        :param int motor: The motor to get the soft start state.

        :returns: The soft start state.
        :rtype: bool

        UiFlow2 Code Block:

            |get_soft_start_state.png|

        MicroPython Code Block:

            .. code-block:: python

                encoder4_motor.get_soft_start_state(0)
        """
        ...
    
    def set_soft_start_state(self, motor, state): # -> None:
        """Set the soft start state of a motor.

        :param int motor: The motor to set the soft start state.
        :param int state: The soft start state.

            Options:
                - ``True``: 1
                - ``False``: 0

        UiFlow2 Code Block:

            |set_soft_start_state.png|

        MicroPython Code Block:

            .. code-block:: python

                encoder4_motor.set_soft_start_state(0, True)
        """
        ...
    
    def set_i2c_address(self, addr): # -> None:
        """Set the I2C address of the device.

        :param int addr: The I2C address to set.

        UiFlow2 Code Block:

            |set_i2c_address.png|

        MicroPython Code Block:

            .. code-block:: python

                encoder4_motor.set_i2c_address(0x24)
        """
        ...
    


