"""
This type stub file was generated by pyright.
"""

class FanModule:
    _FAN_ADDR = ...
    _FAN_STATE_CTR_REG = ...
    _FAN_PWM_FREQ_REG = ...
    _FAN_PWM_DUTY_CYCLE_REG = ...
    _FAN_RPM_REG = ...
    _FAN_SIGNAL_FREQ_REG = ...
    _FAN_FLASH_REG = ...
    _FAN_FW_VERSION_REG = ...
    _FAN_I2C_ADDR_REG = ...
    def __init__(self, address: int | list | tuple = ...) -> None:
        ...
    
    def set_fan_state(self, state: bool): # -> None:
        """Set the fan state to on or off.

        :param bool state: The state of the fan.

        UiFlow2 Code Block:

            |set_fan_state.png|

        MicroPython Code Block:

            .. code-block:: python

                fan_v11_0.set_fan_state(True)
        """
        ...
    
    def get_fan_state(self) -> bool:
        """Get current fan state.

        :returns: The current fan state.
        :rtype: bool

        UiFlow2 Code Block:

            |get_fan_state.png|

        MicroPython Code Block:

            .. code-block:: python

                fan_v11_0.get_fan_state()
        """
        ...
    
    def set_pwm_frequency(self, freq: int = ...) -> None:
        """Set the PWM frequency of the fan.

        :param int freq: The PWM frequency of the fan.

        UiFlow2 Code Block:

            |set_pwm_frequency.png|

        MicroPython Code Block:

            .. code-block:: python

                fan_v11_0.set_pwm_frequency(2)
        """
        ...
    
    def get_pwm_frequency(self) -> int:
        """Get current PWM frequency.

        :returns: The current PWM frequency.
        :rtype: int

        UiFlow2 Code Block:

            |get_pwm_frequency.png|

        MicroPython Code Block:

            .. code-block:: python

                fan_v11_0.get_pwm_frequency()
        """
        ...
    
    def set_pwm_duty_cycle(self, duty_cycle: int) -> None:
        """Set the PWM duty cycle of the fan.

        :param int duty_cycle: The PWM duty cycle of the fan.

        UiFlow2 Code Block:

            |set_pwm_duty_cycle.png|

        MicroPython Code Block:

            .. code-block:: python

                fan_v11_0.set_pwm_duty_cycle(50)
        """
        ...
    
    def get_pwm_duty_cycle(self) -> int:
        """Get current PWM duty cycle.

        :returns: The current PWM duty cycle.
        :rtype: int

        UiFlow2 Code Block:

            |get_pwm_duty_cycle.png|

        MicroPython Code Block:

            .. code-block:: python

                fan_v11_0.get_pwm_duty_cycle()
        """
        ...
    
    def get_fan_rpm(self) -> int:
        """Get current fan RPM.

        :returns: The current fan RPM.
        :rtype: int

        UiFlow2 Code Block:

            |get_fan_rpm.png|

        MicroPython Code Block:

            .. code-block:: python

                fan_v11_0.get_fan_rpm()
        """
        ...
    
    def get_single_frequency(self) -> int:
        """Get current single frequency.

        :returns: The current single frequency.
        :rtype: int

        UiFlow2 Code Block:

            |get_single_frequency.png|

        MicroPython Code Block:

            .. code-block:: python

                fan_v11_0.get_single_frequency()
        """
        ...
    
    def write_flash(self) -> None:
        """Save the current configuration(fan status, PWM frequency, and PWM duty cycle) to the flash.

        UiFlow2 Code Block:

            |write_flash.png|

        MicroPython Code Block:

            .. code-block:: python

                fan_v11_0.write_flash()
        """
        ...
    
    def get_firmware_version(self) -> int:
        """Get current firmware version.

        :returns: The current firmware version.
        :rtype: int

        UiFlow2 Code Block:

            |get_firmware_version.png|

        MicroPython Code Block:

            .. code-block:: python

                fan_v11_0.get_firmware_version()
        """
        ...
    
    def get_i2c_address(self) -> int:
        """Get current I2C address.

        :returns: The current I2C address.
        :rtype: int

        UiFlow2 Code Block:

            |get_i2c_address.png|

        MicroPython Code Block:

            .. code-block:: python

                fan_v11_0.get_i2c_address()
        """
        ...
    
    def set_i2c_address(self, addr: int) -> None:
        """Set the I2C address of the fan.

        :param int addr: The I2C address of the fan.

        UiFlow2 Code Block:

            |set_i2c_address.png|

        MicroPython Code Block:

            .. code-block:: python

                fan_v11_0.set_i2c_address(0x18)
        """
        ...
    


