"""
This type stub file was generated by pyright.
"""

class GatewayH2Module:
    """Create GatewayH2Module object.

    :param int id: UART id. range:1~2
    :param int rx: the UART RX pin.
    :param int tx: the UART TX pin.

    """
    def __init__(self, id: int = ..., rx: int = ..., tx: int = ..., boot: int = ..., en: int = ...) -> None:
        ...
    
    def create_switch_ep(self):
        ...
    


