"""
This type stub file was generated by pyright.
"""

import sys
from driver.bmi270_bmm150 import BMI270_BMM150
from driver.bmp280 import BMP280
from typing import Literal

if sys.platform != "esp32":
    ...
_timTh = ...
_BMI270_ADDR = ...
_SF_G = ...
_SF_M_S2 = ...
_SF_DEG_S = ...
_SF_RAD_S = ...
class GNSSModule(BMI270_BMM150, BMP280):
    """

    note:
        en: GNSS Module is a global positioning wireless communication module featuring the NEO-M9N-00B GPS module. It incorporates BMI270, BMM150 and a barometric pressure sensor.
        cn: GNSS Module是一款多功能全球定位通信模块, 内置NEO-M9N-OOB高精度GNSS定位模组, 同时集成六轴姿态传感器BMI270、三轴地磁计BMM150和气压传感器。

    details:
        color: "#e60f4c"
        link: https://docs.m5stack.com/en/module/GNSS%20Module
        image: https://static-cdn.m5stack.com/resource/docs/products/module/GNSS%20Module/img-b0cdbc6c-d5d5-42bb-bdf6-69016e003b14.webp
        category: module

    """
    def __init__(self, id: Literal[0, 1, 2] = ..., rx: int = ..., tx: int = ..., address: int = ...) -> None:
        """
        note:
            en: initialize Function.
        label:
            en: 'Init %1 with UART %2 RX: %3 TX: %4 BMI270 I2C address %5'
        params:
            id:
                name: id
                type: int
                default: '1'
                note:
                    en: UART controllers id, the range is 0 to 2.
                field: slider
                step: '1'
                min: '0'
                max: '2'
                precision: '1'
            rx:
                name: rx
                type: int
                default: '13'
                note:
                    en: UART rx pin.
            tx:
                name: tx
                type: int
                default: '14'
                note:
                    en: UART tx pin.
            address:
                name: address
                field: dropdown
                options:
                    '0x69': '0x69'
                    '0x68': '0x68'
        """
        ...
    
    def set_accel_gyro_odr(self, accel_odr, gyro_odr) -> None:
        """
        note:
            en: Set the accelerometer and gyroscope output data rate.
        label:
            en: Set %1 accelerometer ODR (Hz) %2 gyroscrope ODR (Hz) %3
        params:
            accel_odr:
                name: accel_odr
                note:
                    en: range of 0.78 Hz … 1.6 kHz.
                field: dropdown
                options:
                    '0.78': '0.78'
                    '1.5': '1.5'
                    '3.1': '3.1'
                    '6.25': '6.25'
                    '12.5': '12.5'
                    '25': '25'
                    '50': '50'
                    '100': '100'
                    '200': '200'
                    '400': '400'
                    '800': '800'
                    '1600': '1600'
            gyro_odr:
                name: gyro_odr
                note:
                    en: range of 25 Hz … 6.4 kHz.
                field: dropdown
                options:
                    '25': '25'
                    '50': '50'
                    '100': '100'
                    '200': '200'
                    '400': '400'
                    '800': '800'
                    '1600': '1600'
                    '3200': '3200'
        """
        ...
    
    def set_accel_range(self, accel_scale) -> None:
        """
        note:
            en: Set the accelerometer scale range.
        label:
            en: Set %1 accelerometer scale %2 g
        params:
            accel_scale:
                name: accel_scale
                note:
                    en: scale range of ±2g, ±4g, ±8g and ±16g.
                field: dropdown
                options:
                    '2': '2'
                    '4': '4'
                    '8': '8'
                    '16': '16'
        """
        ...
    
    def set_gyro_range(self, gyro_scale) -> None:
        """
        note:
            en: Set the gyroscope scale range.
        label:
            en: Set %1 gyroscrope scale %2 dps
        params:
            gyro_scale:
                name: gyro_scale
                field: dropdown
                options:
                    '125': '125'
                    '250': '250'
                    '500': '500'
                    '1000': '1000'
                    '2000': '2000'
        """
        ...
    
    def set_magnet_odr(self, magnet_odr) -> None:
        """
        label:
            en: Set %1 magnetometer ODR %2 Hz
        params:
            magnet_odr:
                name: magnet_odr
                field: dropdown
                options:
                    '2': '2'
                    '6': '6'
                    '8': '8'
                    '10': '10'
                    '15': '15'
                    '20': '20'
                    '25': '25'
                    '30': '30'
        """
        ...
    
    def set_gyro_offsets(self, x, y, z) -> None:
        """
        note:
            en: Set the manual gyro calibrations offsets value.
        label:
            en: Set %1 gyroscrope offset calibration x %2 y %3 z %4
        params:
            x:
                name: x
                type: float
                default: '0'
                note:
                    en: gyro calibrations offsets value of X-axis
                field: number
            y:
                name: y
                type: float
                default: '0'
                note:
                    en: gyro calibrations offsets value of Y-axis
                field: number
            z:
                name: z
                type: float
                default: '0'
                note:
                    en: gyro calibrations offsets value of Z-axis
                field: number
        """
        ...
    
    def get_gyroscope(self) -> tuple:
        """
        note:
            en: Get the tuple of x, y, and z values of the gyroscope and gyroscope vector
                in rad/sec.
        label:
            en: Get %1 gyroscope value (return tuple)
        return:
            note: gyroscope tuple (float, float, float)
        """
        ...
    
    def get_accelerometer(self) -> tuple:
        """
        note:
            en: Get the tuple of x, y, and z values of the accelerometer and acceleration
                vector in gravity units (9.81m/s^2).
        label:
            en: Get %1 accelerometer value (m/s^2, return tuple)
        return:
            note: accelerometer tuple (float, float, float)
        """
        ...
    
    def get_magnetometer(self) -> tuple:
        """
        note:
            en: Get the tuple of x, y, and z values of the magnetometer and magnetometer vector in uT.
        label:
            en: Get %1 magnetometer value (uT, return tuple)
        return:
            note: magnetometer tuple (float, float, float)
        """
        ...
    
    def get_compass(self) -> float:
        """
        note:
            en: Get the compass heading value is in range of 0º ~ 360º.
        label:
            en: Get %1 compass heading angle (0 to 360 degree, return float)
        return:
            note: range is 0 to 360 degree
        """
        ...
    
    def get_attitude(self) -> tuple:
        """
        note:
            en: Get the attitude angles as yaw, pitch, and roll in degrees.
        label:
            en: Get %1 attitude (return tuple, [yaw, pitch, roll])
        return:
            note: tuple of yaw, pitch, and roll (float, float, float)
        """
        ...
    
    def get_temperature(self) -> float:
        """
        note:
            en: Get the temperature value in degrees celsius from the BMP280 sensor.
        label:
            en: Get %1 temperature (°C, return float)
        return:
            note: range is -40 ~ +85 °C.
        """
        ...
    
    def get_pressure(self) -> float:
        """
        note:
            en: Get the pressure value in pascals from the BMP280 sensor.
        label:
            en: Get %1 pressure (hPa, return float)
        return:
            note: range is 300 ~ 1100 hPa.
        """
        ...
    
    def set_time_zone(self, value: int) -> None:
        """
        note:
            en: set timezone function.
        label:
            en: Set %1 timezone %2
        params:
            value:
                name: value
                type: int
                default: '8'
                note:
                    en: timezone value
                field: number
        """
        ...
    
    def get_time_zone(self) -> int:
        """
        note:
            en: get timezone function.
        label:
            en: Get %1 timezone (return int)

        return:
            note: timezone value
        """
        ...
    
    def get_satellite_num(self) -> str:
        """
        note:
            en: get satellite numbers.
        label:
            en: Get %1 satellite numbers (return string)

        return:
            note: satellite numbers value.
        """
        ...
    
    def get_altitude(self) -> str:
        """
        note:
            en: get altitude.
        label:
            en: Get %1 altitude (return string, unit is meter)

        return:
            note: altitude unit is meter.
        """
        ...
    
    def get_time(self) -> str:
        """
        note:
            en: get time.
        label:
            en: Get %1 time (return string, format is hh:mm:ss)

        return:
            note: time(hh:mm:ss)
        """
        ...
    
    def get_date(self) -> str:
        """
        note:
            en: get date.
        label:
            en: Get %1 date (return string, format is dd/mm/yy)

        return:
            note: date(dd/mm/yy)
        """
        ...
    
    def get_latitude(self) -> str:
        """
        note:
            en: get latitude.
        label:
            en: Get %1 latitude (return string, format is ddmm.mmmmmN/S)

        return:
            note: latitude, using degrees minutes format (ddmm.mmmmmN/S).
        """
        ...
    
    def get_longitude(self) -> str:
        """
        note:
            en: get longitude.
        label:
            en: Get %1 longitude (return string, format is ddmm.mmmmmE/W)

        return:
            note: longitude, using degrees minutes format (ddmm.mmmmmE/W).
        """
        ...
    
    def get_latitude_decimal(self) -> float:
        """
        note:
            en: get latitude decimal.
        label:
            en: Get %1 latitude decimal (return float, format is dd.dddd)

        return:
            note: latitude decimal(dd.dddd).
        """
        ...
    
    def get_longitude_decimal(self) -> float:
        """
        note:
            en: get longitude decimal.
        label:
            en: Get %1 longitude decimal (return float, format is dd.dddd)

        return:
            note: longitude decimal(dd.dddd).
        """
        ...
    
    def get_speed(self, type=...) -> str:
        """
        note:
            en: get speed.
        label:
            en: Get %1 speed %2(return string)
        params:
            type:
                name: type
                note:
                    en: speed type, 0 km/h, 1 knot/h
                field: dropdown
                options:
                    km/h: '0'
                    knot/h: '1'

        return:
            note: speed.
        """
        ...
    
    def get_course(self) -> str:
        """
        note:
            en: get course.
        label:
            en: Get %1 course (return string, 0 to 360 degree)

        return:
            note: course unit is °.
        """
        ...
    
    def is_locate_valid(self) -> bool:
        """
        note:
            en: get locate status.
        label:
            en: Get %1 locate status (return True or False)

        return:
            note: locate status, true is locate, false is not locate.
        """
        ...
    


