"""
This type stub file was generated by pyright.
"""

class GoPlus2Module:
    """! GoPlus2 is a stackable multi-functional motor and servo control module.

    @en Module GoPlus2 英文介绍
    @cn Module GoPlus2 中文介绍

    @color #0FE6D7
    @link https://docs.m5stack.com/en/module/goplus2
    @image https://static-cdn.m5stack.com/resource/docs/products/module/goplus2/goplus2_01.webp
    @category module

    """
    _GOPLUS2_ADDR = ...
    _GOPLUS2_SERVO_ANGLE_REG = ...
    _GOPLUS2_SERVO_PLUSEWIDTH_REG = ...
    _GOPLUS2_MOTOR_CTR_REG = ...
    _GOPLUS2_PBI_ANALOG_INPUT_REG = ...
    _GOPLUS2_PBI_DIGITAL_INPUT_REG = ...
    _GOPLUS2_PBO_DIGITAL_OUTPUT_REG = ...
    _GOPLUS2_PBO_DIGITAL_INPUT_REG = ...
    _GOPLUS2_PBO_CTR_REG = ...
    def __init__(self, address: int | list | tuple = ...) -> None:
        """! Initialize the GoPlus2Module.

        @param address The I2C address of the GoPlus2 module (default is 0x38).
        """
        ...
    
    def set_servo_angle(self, servo_num: int, angle: int) -> None:
        """! Set the angle of the specified servo.

        @param servo_num The number of the servo (1 to 4).
        @param angle The angle to set the servo to (0 to 180 degrees).
        """
        ...
    
    def set_servo_pulse_width(self, servo_num: int, pulse_width: int) -> None:
        """! Set the pulse width for the specified servo.

        @param servo_num The number of the servo (1 to 4).
        @param pulse_width The pulse width to set (in microseconds).
        """
        ...
    
    def set_motor_speed(self, motor_num: int, speed: int) -> None:
        """! Set the speed of the specified motor.

        @param motor_num The number of the motor (1 or 2).
        @param speed The speed to set (negative for reverse).
        """
        ...
    
    def set_digital_output(self, pin_num: int, value: int) -> None:
        """! Set the digital output for the specified pin.

        @param pin_num The number of the pin (1 to 3).
        @param value The value to set (0 or 1).
        """
        ...
    
    def get_digital_input(self, pin_num: int) -> int:
        """! Get the digital input value of the specified pin.

        @param pin_num The number of the pin (1 to 3).
        @return The digital input value (0 or 1).
        """
        ...
    
    def get_analog_input(self, pin_num: int) -> int:
        """! Get the analog input value of the specified pin.

        @param pin_num The number of the pin (1 to 3).
        @return The analog input value (0 to 1023).
        """
        ...
    


