"""
This type stub file was generated by pyright.
"""

import sys
from typing import Literal

if sys.platform != "esp32":
    ...
_timTh = ...
class GPSModule:
    """

    note:
        en: COM.GPS is a satellite positioning module in the M5Stack stacking module series. It is developed based on the NEO-M8N module.
        cn: COM.GPS 是M5Stack堆叠模块系列中的一款,卫星定位模块.基于NEO-M8N模组开发。

    details:
        color: "#0f2fe6"
        link: https://docs.m5stack.com/en/module/comx_gps
        image: https://static-cdn.m5stack.com/resource/docs/products/module/comx_gps/comx_gps_03.webp
        category: module

    """
    def __init__(self, id: Literal[0, 1, 2] = ..., rx: int = ..., tx: int = ...) -> None:
        """
        note:
            en: initialize Function.
        label:
            en: 'Init %1 with UART %2 RX: %3 TX: %4'
        params:
            id:
                name: id
                type: int
                default: '1'
                note:
                    en: UART controllers id, the range is 0 to 2.
                field: slider
                step: '1'
                min: '0'
                max: '2'
                precision: '1'
            rx:
                name: rx
                type: int
                default: '13'
                note:
                    en: UART rx pin.
            tx:
                name: tx
                type: int
                default: '14'
                note:
                    en: UART tx pin.
        """
        ...
    
    def set_time_zone(self, value: int) -> None:
        """
        note:
            en: set timezone function.
        label:
            en: Set %1 timezone %2
        params:
            value:
                name: value
                type: int
                default: '8'
                note:
                    en: timezone value
                field: number
        """
        ...
    
    def get_time_zone(self) -> int:
        """
        note:
            en: get timezone function.
        label:
            en: Get %1 timezone (return int)

        return:
            note: timezone value
        """
        ...
    
    def get_satellite_num(self) -> str:
        """
        note:
            en: get satellite numbers.
        label:
            en: Get %1 satellite numbers (return string)

        return:
            note: satellite numbers value.
        """
        ...
    
    def get_altitude(self) -> str:
        """
        note:
            en: get altitude.
        label:
            en: Get %1 altitude (return string, unit is meter)

        return:
            note: altitude unit is meter.
        """
        ...
    
    def get_time(self) -> str:
        """
        note:
            en: get time.
        label:
            en: Get %1 time (return string, format is hh:mm:ss)

        return:
            note: time(hh:mm:ss)
        """
        ...
    
    def get_date(self) -> str:
        """
        note:
            en: get date.
        label:
            en: Get %1 date (return string, format is dd/mm/yy)

        return:
            note: date(dd/mm/yy)
        """
        ...
    
    def get_latitude(self) -> str:
        """
        note:
            en: get latitude.
        label:
            en: Get %1 latitude (return string, format is ddmm.mmmmmN/S)

        return:
            note: latitude, using degrees minutes format (ddmm.mmmmmN/S).
        """
        ...
    
    def get_longitude(self) -> str:
        """
        note:
            en: get longitude.
        label:
            en: Get %1 longitude (return string, format is ddmm.mmmmmE/W)

        return:
            note: longitude, using degrees minutes format (ddmm.mmmmmE/W).
        """
        ...
    
    def get_latitude_decimal(self) -> float:
        """
        note:
            en: get latitude decimal.
        label:
            en: Get %1 latitude decimal (return float, format is dd.dddd)

        return:
            note: latitude decimal(dd.dddd).
        """
        ...
    
    def get_longitude_decimal(self) -> float:
        """
        note:
            en: get longitude decimal.
        label:
            en: Get %1 longitude decimal (return float, format is dd.dddd)

        return:
            note: longitude decimal(dd.dddd).
        """
        ...
    
    def get_speed(self, type=...) -> str:
        """
        note:
            en: get speed.
        label:
            en: Get %1 speed %2(return string)
        params:
            type:
                name: type
                note:
                    en: speed type, 0 km/h, 1 knot/h
                field: dropdown
                options:
                    km/h: '0'
                    knot/h: '1'

        return:
            note: speed.
        """
        ...
    
    def get_course(self) -> str:
        """
        note:
            en: get course.
        label:
            en: Get %1 course (return string, 0 to 360 degree)

        return:
            note: course unit is °.
        """
        ...
    
    def is_locate_valid(self) -> bool:
        """
        note:
            en: get locate status.
        label:
            en: Get %1 locate status (return True or False)

        return:
            note: locate status, true is locate, false is not locate.
        """
        ...
    


