"""
This type stub file was generated by pyright.
"""

import sys
from driver.atgm336h import ATGM336H
from typing import Literal

if sys.platform != "esp32":
    ...
class GPSV2Module(ATGM336H):
    def __init__(self, id: Literal[0, 1, 2] = ..., rx: int = ..., tx: int = ..., pps: int = ...) -> None:
        """
        note:
            en: Initialize the GPSModule with a specific UART id and port for communication.

        params:
            id:
                note: The UART ID for communication with the GPS module. It can be 0, 1, or 2.
            tx:
                note: The TX pin for UART communication.
            rx:
                note: The RX pin for UART communication.
            pps:
                note: The PPS (Pulse Per Second) pin, used for high-precision time synchronization.
        """
        ...
    


