"""
This type stub file was generated by pyright.
"""

class GRBLModule:
    """

    note:
        cn: GRBL 13.2 是 M5Stack 堆叠模块系列中的三轴步进电机驱动器模块。它采用 ATmega328P-AU 控制器，带有三组 DRV8825PWPR 步进电机驱动芯片控制方式，可以同时驱动三个双极步进电机。
        en: GRBL 13.2 is a three-axis stepper motor driver module in the M5Stack stacking module series. It uses an ATmega328P-AU controller with three sets of DRV8825PWPR stepper motor driver chip control ways, which can drive three bipolar steppers at the same time.

    details:
        color: "#0FE6D7"
        link: https://docs.m5stack.com/en/module/grbl13.2
        image: https://static-cdn.m5stack.com/resource/docs/products/module/grbl13.2/grbl13.2_01.webp
        category: Module

    example:
        - ../../../examples/module/grbl_example.py

    m5f2:
        - module/grbl_example.m5f2


    """
    MODE_ABSOLUTE = ...
    MODE_RELATIVE = ...
    def __init__(self, address: int = ...) -> None:
        """
        note:
            en: Initialize the GRBLModule.
            cn: 初始化GRBL模块。

        params:
            address:
                note: The I2C address of the device.
        """
        ...
    
    def g_code(self, command): # -> int:
        """
        note:
            en: Send the G-code command.
            cn: 发送G代码命令。

        params:
            command:
                note: The G-code command.
        """
        ...
    
    def get_code_time(self, code) -> int:
        """
        note:
            en: Get the time of the code.
            cn: 获取代码的时间。

        params:
            code:
                note: The G-code command

        return:
            note: The estimated time of the command.

        """
        ...
    
    def turn(self, x=..., y=..., z=..., speed=...) -> int:
        """
        note:
            en: Turn the motor to a specific position.
            cn: 将电机转到特定位置。

        params:
            x:
                note: The position of the X motor, 1.6=360°.
            y:
                note: The position of the Y motor, 1.6=360°.
            z:
                note: The position of the Z motor, 1.6=360°.
            speed:
                note: The speed of the motor.
        """
        ...
    
    def set_mode(self, mode): # -> int:
        """
        note:
            en: Set the mode of the motor.
            cn: 设置电机的模式。

        params:
            mode:
                note: The mode of the motor.
                field: dropdown
                options:
                    Absolute: GRBLModule.MODE_ABSOLUTE
                    Relative: GRBLModule.MODE_RELATIVE
        """
        ...
    
    def init(self, x_step=..., y_step=..., z_step=..., acc=...): # -> None:
        """
        note:
            en: Initialize the motor.
            cn: 初始化电机。

        params:
            x_step:
                note: The step of the X motor.
            y_step:
                note: The step of the Y motor.
            z_step:
                note: The step of the Z motor.
            acc:
                note: The acceleration of the motor.
        """
        ...
    
    def flush(self): # -> None:
        """
        note:
            en: Flush the buffer.
            cn: 清空缓冲区。
        """
        ...
    
    def get_message(self) -> str:
        """
        note:
            en: Get the message.
            cn: 获取消息。
        return:
            note: The message string.
        """
        ...
    
    def get_status(self) -> str:
        """
        note:
            en: Get the status.
            cn: 获取状态。
        return:
            note: The status string.
        """
        ...
    
    def get_idle_state(self) -> bool:
        """
        note:
            en: Get the idle state.
            cn: 获取空闲状态。
        return:
            note: The idle state.
        """
        ...
    
    def get_lock_state(self) -> bool:
        """
        note:
            en: Get the lock state.
            cn: 获取锁定状态。
        return:
            note: The lock state.
        """
        ...
    
    def wait_idle(self): # -> None:
        """
        note:
            en: Wait until the motor is idle.
            cn: 等待电机空闲。
        """
        ...
    
    def unlock_alarm_state(self): # -> None:
        """
        note:
            en: Unlock the alarm state.
            cn: 解锁报警状态。
        """
        ...
    
    def lock(self): # -> None:
        """
        note:
            en: Lock the motor.
            cn: 锁定电机。
        """
        ...
    
    def unlock(self): # -> None:
        """
        note:
            en: Unlock the motor.
            cn: 解锁电机。
        """
        ...
    


