"""
This type stub file was generated by pyright.
"""

class HMIModule:
    """! HMI Module is a human-computer interactive module.

    @en Module HMI 英文介绍
    @cn Module HMI 中文介绍

    @color #0FE6D7
    @link https://docs.m5stack.com/en/module/HMI%20Module
    @image https://static-cdn.m5stack.com/resource/docs/products/module/HMI%20Module/img-4c227abf-0a4c-4e3a-b711-b81a35899aaf.webp
    @category module

    """
    _HMI_ADDR = ...
    _HMI_ENCODER_REG = ...
    _HMI_INCREMENT_REG = ...
    _HMI_BUTTON_REG = ...
    _HMI_LED_REG = ...
    _HMI_RESET_COUNTER_REG = ...
    _HMI_FIRMWARE_VERSION_REG = ...
    _HMI_I2C_ADDRESS_REG = ...
    def __init__(self, address: int | list | tuple = ...) -> None:
        """! Init I2C Module HMI I2C Address.

        @param address I2C address of the HMIModule.
        """
        ...
    
    def get_rotary_value(self) -> int:
        """! Get the current value of the rotary.

        @return: The value of the rotary.
        """
        ...
    
    def set_rotary_value(self, value: int) -> None:
        """! Set the rotary value.

        @param value: rotary value(-2147483648-2147483647).
        """
        ...
    
    def reset_rotary_value(self) -> None:
        """! Reset the rotary value."""
        ...
    
    def get_rotary_increments(self) -> int:
        """! Get the increment value of the rotary.

        @return: The increment value of the rotary.
        """
        ...
    
    def get_button_status(self, btn_num: int) -> int:
        """! Get the state of a specific button.

        @param btn_num: Button number (1 to 3).
        @return: The state of the button.
        """
        ...
    
    def get_led_state(self, led_num: int) -> int:
        """! Get the state of a specific LED.

        @param led_num: LED number (1 to 2).
        @return: The state of the LED.
        """
        ...
    
    def set_led_state(self, led_num: int, state: int) -> None:
        """! Set the state of a specific LED.

        @param led_num: LED number (1 to 2).
        @param state: The state to set for the LED.
        """
        ...
    
    def get_firmware_version(self) -> int:
        """! Get the firmware version of the HMI module.

        @return: The firmware version number.
        """
        ...
    
    def get_i2c_address(self) -> int:
        """! Get the current I2C address of the HMI module.

        @return: The I2C address as a hex string.
        """
        ...
    
    def set_i2c_address(self, addr: int) -> None:
        """! Set a new I2C address for the HMI module.
        @param addr: The new I2C address to set.
        """
        ...
    


