"""
This type stub file was generated by pyright.
"""

from driver.simcom.sim7080 import SIM7080
from driver.modbus.master.uSerial import uSerial

AT_CMD = ...
MBusIO = ...
iomap = ...
class IotBaseCatmModule(SIM7080, uSerial):
    def __init__(self) -> None:
        ...
    
    def rs485_init(self, baudrate=..., data_bits=..., stop_bits=..., parity=...): # -> None:
        ...
    
    def modem_power_ctrl(self, ctrl=...): # -> bool | None:
        ...
    
    def write(self, payload): # -> None:
        ...
    
    def read(self, byte=...):
        ...
    
    def readline(self):
        ...
    
    def any(self):
        ...
    


