from lora import RxPacket
from machine import I2C


class LoRa1262Module:
    BANDWIDTHS: tuple[str, ...]

    def __init__(
        self,
        i2c: I2C,
        pin_cs: int = ...,
        pin_irq: int = ...,
        pin_busy: int = ...,
        address: int = ...,
        freq_khz: int = ...,
        bw: str = ...,
        sf: int = ...,
        coding_rate: int = ...,
        preamble_len: int = ...,
        syncword: int = ...,
        output_power: int = ...,
    ) -> None: ...

    def set_freq(self, freq_khz: int = ...) -> None: ...
    def set_sf(self, sf: int) -> None: ...
    def set_bw(self, bw: str) -> None: ...
    def set_coding_rate(self, coding_rate: int) -> None: ...
    def set_syncword(self, syncword: int) -> None: ...
    def set_preamble_len(self, preamble_len: int) -> None: ...
    def set_output_power(self, output_power: int) -> None: ...
    def send(
        self,
        packet: str | list | tuple | int | bytearray,
        tx_at_ms: int = ...,
    ) -> int: ...
    def recv(
        self,
        timeout_ms: int = ...,
        rx_length: int = ...,
        rx_packet: RxPacket = ...,
    ) -> RxPacket: ...
    def start_recv(self) -> None: ...
    def set_tx_callback(self, callback) -> None: ...
    def set_rx_callback(self, callback) -> None: ...
    def standby(self) -> None: ...
    def sleep(self) -> None: ...
    def irq_triggered(self) -> bool: ...
    def deinit(self) -> None: ...
