"""
This type stub file was generated by pyright.
"""

import sys
from typing import Literal

ATCommand = ...
if sys.platform != "esp32":
    ...
class LTEModule:
    """LTE module class.

    :param int id: UART ID connected to the LTE module.
    :param int tx: Connect to the UART TX pin of the LTE module.
    :param int rx: Connect to the UART RX pin of the LTE module.
    :param bool verbose: Whether to print verbose information.

    UiFlow2 Code Block:

        |init.png|

    MicroPython Code Block:

        .. code-block:: python

            from module import LTEModule

            comlte_0 = LTEModule(2, 14, 13, verbose=True)
    """
    ERR_NONE = ...
    ERR_GENERIC = ...
    ERR_TIMEOUT = ...
    def __init__(self, id: Literal[0, 1, 2], tx: int, rx: int, verbose: bool = ...) -> None:
        ...
    
    def execute_at_command2(self, cmd: ATCommand, repeat=..., clean_output=..., line_end=...) -> tuple[bytearray, int]:
        ...
    
    def response_at_command2(self, command: ATCommand, repeat=..., clean_output=..., line_end=...) -> tuple[bytearray, int]:
        ...
    
    def chat(self, script: tuple) -> None:
        """Chat with the LTE module.

        :param tuple script: A tuple of commands to chat with the LTE module.
                             Each command is a tuple of two elements: the first
                             element is the expect value, and the second element
                             is the command. For example, (("OK", "AT").

        UiFlow2 Code Block:

            |chat.png|

        MicroPython Code Block:

            .. code-block:: python

                comlte_0.chat((("OK", "AT"), ("OK", "AT+CGDCONT=1,\"IP\",\"CMNET\""), ("OK", "ATD*99#")))
        """
        ...
    
    def chat2(self, pdp_type: str, apn: str) -> None:
        """Chat with the LTE module to establish a PPP connection.

        :param str pdp_type: PDP type. For example, "IP", "PPP", "IPV4V6", "IPV6".
        :param str apn: Access Point Name. For example, "CMNET".

        UiFlow2 Code Block:

            |chat2.png|

        MicroPython Code Block:

            .. code-block:: python

                comlte_0.chat2("IP", "CMNET")

        """
        ...
    
    def __getattr__(self, attr): # -> Any:
        ...
    
    def deinit(self) -> None:
        """Deinitialize the LTE module.

        UiFlow2 Code Block:

            |deinit.png|

        MicroPython Code Block:

            .. code-block:: python

                comlte_0.deinit()
        """
        ...
    


