"""
This type stub file was generated by pyright.
"""

class Module4In8Out:
    """! 4In8Out Module is a human-computer interactive module.

    @en Module 4In8Out 英文介绍
    @cn Module 4In8Out 中文介绍

    @color #0FE6D7
    @link https://docs.m5stack.com/en/module/4in8out
    @image https://static-cdn.m5stack.com/resource/docs/products/module/4in8out/4in8out_01.webp
    @category module

    """
    _MODULE4IN8OUT_ADDR = ...
    _MODULE4IN8OUT_SWTICH_REG = ...
    _MODULE4IN8OUT_LOAD_REG = ...
    _MODULE4IN8OUT_FIRMWARE_VERSION_REG = ...
    _MODULE4IN8OUT_I2C_ADDRESS_REG = ...
    def __init__(self, address: int | list | tuple = ...) -> None:
        """! Init I2C Module 4In8Out I2C Address.

        @param address I2C address of the 4In8OutModule.
        """
        ...
    
    def get_switch_value(self, switch_num: int) -> bool:
        """! Get the current value of the rotary.

        @return: The value of the rotary.
        """
        ...
    
    def get_load_state(self, load_num: int) -> bool:
        """! Get the state of a specific LED.

        @param load_num: Load number (1 to 8).
        @return: The state of the Load.
        """
        ...
    
    def set_load_state(self, load_num: int, state: int) -> None:
        """! Set the state of a specific Load.

        @param load_num: Load number (1 to 8).
        @param state: The state to set for the Load.
        """
        ...
    
    def get_firmware_version(self) -> int:
        """! Get the firmware version of the 4In8Out module.

        @return: The firmware version number.
        """
        ...
    
    def get_i2c_address(self) -> int:
        """! Get the current I2C address of the 4In8Out module.

        @return: The I2C address as a hex string.
        """
        ...
    
    def set_i2c_address(self, addr: int) -> None:
        """! Set a new I2C address for the 4In8Out module.
        @param addr: The new I2C address to set.
        """
        ...
    


