"""
This type stub file was generated by pyright.
"""

import machine
import sys
from driver.simcom.sim7020 import SIM7020
from driver.simcom.common import Modem

if sys.platform != "esp32":
    ...
class NBIOTModule(SIM7020, Modem):
    def __init__(self, uart_or_id: machine.UART | int, tx: int = ..., rx: int = ..., verbose: bool = ...) -> None:
        ...
    


