"""
This type stub file was generated by pyright.
"""

READ_TIMEOUT = ...
class ODriveModule:
    """

    note:
        cn: ODrive是M5Stack推出的高性能伺服电机驱动模块，基于开源运动控制解决方案ODrive。
        en: ODrive is a high-performance servo motor drive module launched by M5Stack, based on the open source motion control solution ODrive.

    details:
        color: "#0FE6D7"
        link: https://docs.m5stack.com/en/module/odrive
        image: https://static-cdn.m5stack.com/resource/docs/products/module/odrive/odrive_01.webp
        category: Module

    example: |
        from module import ODriveModule
        drive = ODriveModule(port=(13,5))
        drive.get_vbus_voltage()
        drive.set_velocity(10)
        drive.set_current(5)
        drive.set_control_mode(ODriveModule.CONTROL_MODE_POSITION_CONTROL)
        drive.set_position(1000)


    """
    AXIS_STATE_UNDEFINED = ...
    AXIS_STATE_IDLE = ...
    AXIS_STATE_STARTUP_SEQUENCE = ...
    AXIS_STATE_FULL_CALIBRATION_SEQUENCE = ...
    AXIS_STATE_MOTOR_CALIBRATION = ...
    AXIS_STATE_SENSORLESS_CONTROL = ...
    AXIS_STATE_ENCODER_INDEX_SEARCH = ...
    AXIS_STATE_ENCODER_OFFSET_CALIBRATION = ...
    AXIS_STATE_CLOSED_LOOP_CONTROL = ...
    CONTROL_MODE_VOLTAGE_CONTROL = ...
    CONTROL_MODE_TORQUE_CONTROL = ...
    CONTROL_MODE_VELOCITY_CONTROL = ...
    CONTROL_MODE_POSITION_CONTROL = ...
    def __init__(self, id=..., port=...) -> None:
        """
        note:
            en: Initialize the ODriveModule.
            cn: 初始化ODriveModule。
        """
        ...
    
    def set_position(self, position, velocity_feedforward=..., current_feedforward=...): # -> None:
        """
        note:
            en: Set the target position with optional feedforward values.
            cn: 设置目标位置，并可选地提供前馈值。

        params:
            position:
                note: The target position in counts or radians, depending on the configuration.
            velocity_feedforward:
                note: The feedforward velocity in counts/s or radians/s to assist the controller.
            current_feedforward:
                note: The feedforward current in amperes to assist the controller.
        """
        ...
    
    def set_velocity(self, velocity, current_feedforward=...): # -> None:
        """
        note:
            en: Set the target velocity with optional current feedforward.
            cn: 设置目标速度，并可选地提供电流前馈值。

        params:
            velocity:
                note: The target velocity in counts/s or radians/s.
            current_feedforward:
                note: The feedforward current in amperes to assist the controller.
        """
        ...
    
    def set_current(self, current): # -> None:
        """
        note:
            en: Set the target current.
            cn: 设置目标电流。

        params:
            current:
                note: The target current in amperes for torque control.
        """
        ...
    
    def set_gain(self, pos_gain, vel_gain, vel_integrator_gain): # -> None:
        """
        note:
            en: Set the controller gains for position and velocity control.
            cn: 设置位置和速度控制的控制器增益。

        params:
            pos_gain:
                note: The proportional gain for position control (units: counts or radians).
            vel_gain:
                note: The proportional gain for velocity control (units: A/(counts/s) or A/(rad/s)).
            vel_integrator_gain:
                note: The integral gain for velocity control (units: A/(counts/s * s) or A/(rad/s * s)).
        """
        ...
    
    def set_control_mode(self, mode): # -> None:
        """
        note:
            en: Set the control mode of the controller.
            cn: 设置控制器的控制模式。

        params:
            mode:
                note: The control mode.
                options:
                    Voltage Control: ODriveModule.CONTROL_MODE_VOLTAGE_CONTROL
                    Torque Control: ODriveModule.CONTROL_MODE_TORQUE_CONTROL
                    Velocity Control: ODriveModule.CONTROL_MODE_VELOCITY_CONTROL
                    Position Control: ODriveModule.CONTROL_MODE_POSITION_CONTROL
        """
        ...
    
    def set_control_input_pos(self, pos): # -> None:
        """
        note:
            en: Set the control input position for the controller.
            cn: 设置控制器的输入位置。

        params:
            pos:
                note: The desired input position in counts or radians for position control.
        """
        ...
    
    def trapezoidal_move(self, position): # -> None:
        """
        note:
            en: Perform a trapezoidal move to the given position.
            cn: 执行到指定位置的梯形运动。

        params:
            position:
                note: The target position in counts or radians to move to using a trapezoidal velocity profile.
        """
        ...
    
    def run_state(self, requested_state, timeout):
        """
        note:
            en: Run the axis to the requested state within a timeout period.
            cn: 在超时时间内将轴运行到请求的状态。

        params:
            requested_state:
                note: The desired axis state to transition to, using the AXIS_STATE_* constants.
                options:
                    Idle: ODriveModule.AXIS_STATE_UNDEFINED
                    Startup: ODriveModule.AXIS_STATE_STARTUP_SEQUENCE
                    Calibration: ODriveModule.AXIS_STATE_FULL_CALIBRATION_SEQUENCE
                    Motor Calibration: ODriveModule.AXIS_STATE_MOTOR_CALIBRATION
                    Sensorless Control: ODriveModule.AXIS_STATE_SENSORLESS_CONTROL
                    Encoder Index Search: ODriveModule.AXIS_STATE_ENCODER_INDEX_SEARCH
                    Encoder Offset Calibration: ODriveModule.AXIS_STATE_ENCODER_OFFSET_CALIBRATION
                    Closed Loop Control: ODriveModule.AXIS_STATE_CLOSED_LOOP_CONTROL
            timeout:
                note: Timeout in milliseconds to wait for the axis to reach the requested state.
        returns:
            note: True if the axis reached the requested state within the timeout period, False otherwise.
        """
        ...
    
    def get_velocity(self) -> float:
        """
        note:
            en: Get the estimated velocity of the motor.
            cn: 获取电机的估计速度。
        return:
            note: The estimated velocity in counts/s or radians/s.
        """
        ...
    
    def get_vbus_voltage(self) -> float:
        """
        note:
            en: Get the measured bus voltage.
            cn: 获取测量的母线电压。
        return:
            note: The bus voltage in volts.
        """
        ...
    
    def get_phase_current(self) -> float:
        """
        note:
            en: Get the measured phase current of the motor.
            cn: 获取电机的测量相电流。
        return:
            note: The phase current in amperes.
        """
        ...
    
    def get_bus_current(self) -> float:
        """
        note:
            en: Get the bus current drawn by the motor.
            cn: 获取电机消耗的母线电流。
        return:
            note: The bus current in amperes.
        """
        ...
    
    def get_encoder_shadow_count(self) -> int:
        """
        note:
            en: Get the encoder's shadow count, which is an internal counter.
            cn: 获取编码器的影子计数，这是一个内部计数器。
        return:
            note: The shadow count as an integer value.
        """
        ...
    
    def get_encoder_pos_estimate(self) -> float:
        """
        note:
            en: Get the estimated position from the encoder.
            cn: 获取编码器的估计位置。
        return:
            note: The estimated position in counts or radians.
        """
        ...
    
    def get_motor_temp(self) -> float:
        """
        note:
            en: Get the temperature of the motor thermistor.
            cn: 获取电机热敏电阻的温度。
        return:
            note: The motor temperature in degrees Celsius.
        """
        ...
    
    def erase_config(self): # -> None:
        """
        note:
            en: Erase the current configuration settings.
            cn: 擦除当前的配置设置。
        """
        ...
    
    def save_config(self): # -> None:
        """
        note:
            en: Save the current configuration to non-volatile memory.
            cn: 将当前配置保存到非易失性存储器。
        """
        ...
    
    def reboot(self): # -> None:
        """
        note:
            en: Reboot the ODrive device.
            cn: 重启ODrive设备。
        """
        ...
    
    def set_default_config(self): # -> None:
        """
        note:
            en: Set the default configuration parameters.
            cn: 设置默认的配置参数。
        """
        ...
    
    def check_error(self) -> dict:
        """
        note:
            en: Check for any errors in the system components.
            cn: 检查系统组件中的任何错误。
        returns:
            note: A dictionary containing error codes for 'axis', 'motor_thermistor', 'encoder', and 'controller'. Zero indicates no error.
        """
        ...
    
    def read_flush(self): # -> None:
        """
        note:
            en: Flush the UART read buffer to clear any residual data.
            cn: 清空UART读取缓冲区，清除任何残留数据。
        """
        ...
    
    def read_string(self) -> str:
        """
        note:
            en: Read a string terminated by a newline character from the device.
            cn: 从设备读取以换行符结尾的字符串。
        return:
            note: The string read from the device, excluding the newline character.
        """
        ...
    
    def read_float(self) -> float:
        """
        note:
            en: Read a floating-point value from the device.
            cn: 从设备读取浮点值。
        return:
            note: The float value read from the device; returns 0.0 if parsing fails.
        """
        ...
    
    def read_int(self) -> int:
        """
        note:
            en: Read an integer value from the device.
            cn: 从设备读取整数值。
        return:
            note: The integer value read from the device; returns 0 if parsing fails.
        """
        ...
    
    def write_to_device(self, data): # -> None:
        """
        note:
            en: Write a command string to the device via UART.
            cn: 通过UART将命令字符串写入设备。

        params:
            data:
                note: The command string to send to the device, ending with a newline character.
        """
        ...
    
    def write_config(self, config, value): # -> None:
        """
        note:
            en: Write a configuration parameter to the device.
            cn: 将配置参数写入设备。

        params:
            config:
                note: The configuration key as a string, e.g., 'axis0.controller.config.pos_gain'.
            value:
                note: The value to set for the configuration parameter; can be a float or integer.
        """
        ...
    
    def read_config_int(self, config) -> int:
        """
        note:
            en: Read an integer configuration parameter from the device.
            cn: 从设备读取整数配置参数。

        params:
            config:
                note: The configuration key as a string, e.g., 'axis0.encoder.error'.
        return:
            note: The integer value of the specified configuration parameter; returns 0 if parsing fails.
        """
        ...
    
    def read_config_float(self, config) -> float:
        """
        note:
            en: Read a floating-point configuration parameter from the device.
            cn: 从设备读取浮点配置参数。

        params:
            config:
                note: The configuration key as a string, e.g., 'axis0.motor_thermistor.temperature'.
        return:
            note: The float value of the specified configuration parameter; returns 0.0 if parsing fails.
        """
        ...
    


