"""
This type stub file was generated by pyright.
"""

class PLUSModule:
    """! PLUS is a enhanced M5 module comes with lithium polymer battery(500mAh), gear potentiometer, IR transmitter, extend PORT B(GPIO Port), PORT C(UART Port) from M5 core and a Microphone soldering pad.

    @en Module PLUS 英文介绍
    @cn Module PLUS 中文介绍

    @color #0FE6D7
    @link https://docs.m5stack.com/en/module/plus
    @image https://static-cdn.m5stack.com/resource/docs/products/module/plus/plus_01.webp
    @category module
    """
    _PLUS_ADDR = ...
    def __init__(self, address: int | list | tuple = ...) -> None:
        """! Init I2C Module PLUS I2C Address.

        @param address I2C address of the PLUSModule.
        """
        ...
    
    def get_rotary_value(self) -> int:
        """Get the current value of the rotary.

        @return: The value of the rotary relative to the zero point.
        """
        ...
    
    def reset_rotary_value(self) -> None:
        ...
    
    def set_rotary_value(self, value: int) -> None:
        """! Set the rotary value.

        @param value: rotary value.
        """
        ...
    
    def get_rotary_increments(self) -> int:
        """Get the increments of the rotary value since the last call of this function.

        @return: The increment value of the rotary.
        """
        ...
    
    def get_button_status(self) -> bool:
        """! Get the state of a specific button.

        @return: The state of the button.
        """
        ...
    


