"""
This type stub file was generated by pyright.
"""

import sys
from typing import Literal

if sys.platform != "esp32":
    ...
MBusIO = ...
iomap = ...
class PM25Module:
    def __init__(self, id: Literal[0, 1, 2]) -> None:
        """
        label:
            en: Init %1 with UART
        """
        ...
    
    def set_module_power(self, state): # -> None:
        """
        label:
            en: Set %1 power state to %2
        params:
            state:
                name: state
                type: bool
                default: 'False'
                field: switch
        """
        ...
    
    def get_module_power(self):
        """
        label:
            en: Get %1 power state (return True / False)
        """
        ...
    
    def set_module_mode(self, mode): # -> None:
        """
        label:
            en: Set %1 work mode to %2
        params:
            mode:
                name: mode
                field: dropdown
                options:
                    Active mode: '1'
                    Passive mode: '0'
        """
        ...
    
    def refresh_data(self) -> bool:
        """
        label:
            en: Refresh  %1 data
        """
        ...
    
    def request_air_data(self): # -> None:
        """
        label:
            en: Request %1 air data
        """
        ...
    
    def get_pm_data(self, data_num: int) -> int:
        """
        label:
            en: Get %1 %2 data
        params:
            data_num:
                name: data_num
                field: dropdown
                options:
                    PM1.0 Concentration(Std): 0
                    PM2.5 Concentration(Std): 1
                    PM10 Concentration(Std): 2
                    PM1.0 Concentration(Env): 3
                    PM2.5 Concentration(Env): 4
                    PM10 Concentration(Env): 5
                    Particels more than 0.3um in 0.1 liters of air: 6
                    Particels more than 0.5um in 0.1 liters of air: 7
                    Particels more than 1.0um in 0.1 liters of air: 8
                    Particels more than 2.5um in 0.1 liters of air: 9
                    Particels more than 5.0um in 0.1 liters of air: 10
                    Particels more than 10um in 0.1 liters of air: 11
        """
        ...
    
    def get_temperature(self): # -> float | None:
        """
        label:
            en: Get %1 env temperature
        """
        ...
    
    def get_humidity(self): # -> float | None:
        """
        label:
            en: Get %1 env humidity
        """
        ...
    


