"""
This type stub file was generated by pyright.
"""

class PPSModule:
    """! Programmable Power Supply (PPS), supports output up to 30V 5A.

    @en The Programmable Power Supply (PPS), capable of providing an output up to 30V and 5A. It allows for precise control over the output voltage and current, with features to read back the actual output values and the module's status.
    @cn 可编程电源供应器（PPS），能够提供最高30V和5A的输出。它允许对输出电压和电流进行精确控制，并具有读回实际输出值和模块状态的功能。

    @attr OUT_DISABLED PPS output is disabled.
    @attr OUT_CV_MODE PPS output is in constant voltage mode.
    @attr OUT_CC_MODE PPS output is in constant current mode.
    @color #0FE6D7
    @link https://docs.m5stack.com/en/module/pps
    @image https://static-cdn.m5stack.com/resource/docs/products/module/pps/pps_01.webp

    @init
        from module import PPS
                pps = PPS(addr=0x35)

    @test
                pps.set_output_voltage(5.5)
                pps.set_output_current(1)
                pps.set_output(True)
                pps.read_psu_running_mode()
                pps.read_output_current()
                pps.read_output_voltage()
                pps.read_input_voltage()
                pps.read_data_update_flag()
                pps.read_mcu_temperature()
                pps.read_module_id()
                pps.read_uid()

    """
    OUT_DISABLED = ...
    OUT_CV_MODE = ...
    OUT_CC_MODE = ...
    def __init__(self, address=...) -> None:
        """! Initialize the PPS.

        @param port I2C port to use.
        @param addr I2C address of the device.
        """
        ...
    
    def set_output(self, enable: bool): # -> None:
        """Enable or disable the PPS module output.

        @en Set the output mode of %1 to %2.
        @cn 设置%1的输出模式%2。

        @param enable True to enable, False to disable.
        """
        ...
    
    def enable_output(self): # -> None:
        """Enable the PPS module output.

        @en Enable the output of %1.
        @cn 启用%1的输出。
        """
        ...
    
    def disable_output(self): # -> None:
        """Disable the PPS module output.

        @en Disable the output of %1.
        @cn 禁用%1的输出。
        """
        ...
    
    def set_output_voltage(self, voltage: float): # -> None:
        """Set the output voltage of the PPS.

        @en Set the output voltage of %1 to %2 V.
        @cn 将%1的输出电压设置为%2 V。

        @param voltage: float, Desired output voltage in volts, range 0 to 30.0.
        """
        ...
    
    def set_output_current(self, current: float): # -> None:
        """Set the output current of the PPS.

        @en Set the output current of %1 to %2 A.
        @cn 将%1的输出电流设置为%2 A。

        @param current Desired output current, from 0.0A to 5.0A.
        """
        ...
    
    def read_psu_running_mode(self) -> int:
        """Read the PSU running mode.

        @en Read the PSU running mode of %1.
        @cn 读取%1的PSU运行模式。

        Returns:
            int: The current running mode of the PSU. One of OUT_DISABLED, OUT_CV_MODE, or OUT_CC_MODE.
        """
        ...
    
    def read_output_current(self) -> float:
        """Read the output current.

        @en Read the output current of %1.
        @cn 读取%1的输出电流。

        Returns:
            float: The current output current in Amperes.
        """
        ...
    
    def read_output_voltage(self) -> float:
        """Read the output voltage.

        @en Read the output voltage of %1.
        @cn 读取%1的输出电压。

        Returns:
            float: The current output voltage in Volts.
        """
        ...
    
    def read_input_voltage(self) -> float:
        """Read the input voltage.

        @en Read the input voltage of %1.
        @cn 读取%1的输入电压。

        Returns:
            float: The current input voltage in Volts.
        """
        ...
    
    def read_data_update_flag(self) -> int:
        """Read the data update flag. When the PSU data is updated, this value will increase by 1.

        @en Read the data update flag of %1.
        @cn 读取%1的数据更新标志。

        Returns:
            int: The data update flag value.
        """
        ...
    
    def read_mcu_temperature(self) -> float:
        """Read the MCU temperature.

        @en Read the MCU temperature of %1.
        @cn 读取%1的MCU温度。

        Returns:
            float: The current MCU temperature in degrees Celsius.
        """
        ...
    
    def read_module_id(self) -> int:
        """Read the module ID.

        @en Read the module ID of %1.
        @cn 读取%1的模块ID。

        Returns:
            int: The module ID as an unsigned 16-bit integer.
        """
        ...
    
    def read_uid(self) -> bytearray:
        """!
        @en Read the unique identifier (UID) of %1.
        @cn 读取%1的唯一标识符（UID）。

        Returns:
            bytearray: The UID as a bytearray.
        """
        ...
    
    def get_i2c_address(self) -> int:
        """Get the current I2C address of the device.

        @en Get the current I2C address of %1.
        @cn 获取%1的当前I2C地址。

        Returns:
            int: The current I2C address.
        """
        ...
    
    def set_i2c_address(self, new_address: int): # -> None:
        """Set a new I2C address for the device.

        @en Set a new I2C address for %1.
        @cn 为%1设置新的I2C地址。

        @param new_address: The new I2C address to set.
        """
        ...
    


