"""
This type stub file was generated by pyright.
"""

import m5can
import sys
from typing import Literal

if sys.platform != "esp32":
    ...
class PwrCANModule(m5can.CAN):
    def __init__(self, id: Literal[0, 1] = ..., port: list | tuple = ..., mode: int = ..., prescaler: int = ..., sjw: int = ..., bs1: int = ..., bs2: int = ..., triple_sampling: bool = ..., quantum_resolution_hz: int = ..., baudrate: int = ..., verbose: bool = ...) -> None:
        ...
    


class PwrCANModuleRS485:
    def __new__(cls, id, **kwargs):
        ...
    


