"""
This type stub file was generated by pyright.
"""

from driver.qrcode.qrcode_m14 import QRCodeM14

class QRCodeModule(QRCodeM14):
    PI4IO_REG_CHIP_RESET = ...
    PI4IO_REG_IO_DIR = ...
    PI4IO_REG_OUT_SET = ...
    PI4IO_REG_OUT_H_IM = ...
    PI4IO_REG_IN_DEF_STA = ...
    PI4IO_REG_PULL_EN = ...
    PI4IO_REG_PULL_SEL = ...
    PI4IO_REG_IN_STA = ...
    PI4IO_REG_INT_MASK = ...
    PI4IO_REG_IRQ_STA = ...
    def __init__(self, id: int = ..., tx: int = ..., rx: int = ...) -> None:
        ...
    
    def init_device(self): # -> None:
        ...
    
    def set_power(self, enable: bool = ...) -> None:
        """Set power. 设置电源。

        :param enable: True - power on. 开启
                       False - power off. 关闭

        UiFlow2 Code Block:

            |set_power.png|

        MicroPython Code Block:

            .. code-block:: python

                module_qrcode.set_power(enable)
        """
        ...
    
    def set_trig(self, value: int) -> None:
        """Set trigger value.

        :param int value: ``0`` - Low level, ``1`` - High level.

        UiFlow2 Code Block:

            |set_trig.png|

        MicroPython Code Block:

            .. code-block:: python

                module_qrcode.set_trig(value)
        """
        ...
    


