"""
This type stub file was generated by pyright.
"""

class RCAModule:
    """Initialize the RCA Module.

    :param int pin: The dac pin to which the RCA Module is connected.
    :param int width: The width of the RCA display.
    :param int height: The height of the RCA display.
    :param int output_width: The width of the output of the RCA display.
    :param int output_height: The height of the output of the RCA display.
    :param int signal_type: The signal type of the RCA display. NTSC=0, NTSC_J=1, PAL=2, PAL_M=3, PAL_N=4.
    :param int use_psram: The use of psram of the RCA display.
    :param int output_level: The output level of the RCA display.

    UiFlow2 Code Block:

        |init.png|

    MicroPython Code Block:

        .. code-block:: python

            from module import RCAModule
            module_rca = RCAModule(26, width=216, height=144, output_width=0, output_height=0, signal_type=RCAModule.NTSC, use_psram=0, output_level=0)
    """
    NTSC = ...
    NTSC_J = ...
    PAL = ...
    PAL_M = ...
    PAL_N = ...
    def __new__(cls, pin: int = ..., width: int = ..., height: int = ..., output_width: int = ..., output_height: int = ..., signal_type: int = ..., use_psram: int = ..., output_level: int = ...) -> None:
        ...
    


