"""
This type stub file was generated by pyright.
"""

DEV_I2C_ADDR = ...
RELAY_REG = ...
ADC_8BIT_REG = ...
ADC_16BIT_REG = ...
I2C_ADDR_REG = ...
class Relay_Stack:
    def __init__(self, i2c, address) -> None:
        ...
    
    def get_relay_status(self, num):
        """
        get RELAY Status.
        reg: 0x10
        num: select only 1 to 4
        return 0 or 1
        """
        ...
    
    def set_relay_state(self, num, state): # -> None:
        """
        Set RELAY State.
        reg: 0x10
        num: select only 1 to 4
        state: value is 0 or 1
        """
        ...
    
    def set_all_relay_state(self, state): # -> None:
        """
        Set All RELAY State.
        reg: 0x10
        state: value is 0 or 1
        """
        ...
    
    def get_adc_8bit_value(self, volt=...):
        """
        get adc raw/volt 8bit value
        """
        ...
    
    def get_adc_12bit_value(self, volt=...): # -> Any:
        """
        get adc raw/volt 12bit value
        """
        ...
    
    def set_i2c_address(self, addr): # -> None:
        """
        set i2c address.
        addr :  1 to 127
        """
        ...
    


class Relay4Module(Relay_Stack):
    def __init__(self, address: int = ...) -> None:
        ...
    


