"""
This type stub file was generated by pyright.
"""

class Relay2Module:
    """! Relay2 Module controls two relays.

    @en Module Relay2 英文介绍
    @cn Module Relay2 中文介绍

    @color #0FE6D7
    @link https://docs.m5stack.com/en/module/2Relay
    @image https://static-cdn.m5stack.com/resource/docs/products/module/2Relay/img-07c98873-5b75-4c92-ab16-64c890c6166e.webp
    @category module

    """
    _RELAY2_ADDR = ...
    _RELAY2_CONTROL_REG = ...
    _RELAY2_FIRMWARE_VERSION_REG = ...
    _RELAY2_I2C_ADDR_REG = ...
    def __init__(self, address: int | list | tuple = ...) -> None:
        """! Initialize the 2Relay Module with the specified I2C address.

        @param address: I2C address of the Relay2Module.
        """
        ...
    
    def set_relay_state(self, num: int, state: bool) -> None:
        """! Set the state of a specific relay.

        @param num: The relay number (1 or 2).
        @param state: True to turn on, False to turn off.
        """
        ...
    
    def get_relay_status(self, num: int) -> int:
        """! Get the status of a specific relay.

        @param num: The relay number (1 or 2).
        @return: The state of the relay (1 for on, 0 for off).
        """
        ...
    
    def set_all_relay_state(self, state: bool) -> None:
        """! Set the state of both relays simultaneously.

        @param state: True to turn on both relays, False to turn off both relays.
        """
        ...
    
    def get_firmware_version(self) -> int:
        """! Get the firmware version of the Relay2 Module.

        @return: The firmware version number.
        """
        ...
    
    def set_i2c_address(self, addr: int) -> None:
        """! Set a new I2C address for the Relay2 Module.

        @param addr: The new I2C address to set.
        """
        ...
    
    def get_i2c_address(self) -> int:
        """! Get the current I2C address of the Relay2 Module.

        @return: The I2C address as a hex string.
        """
        ...
    


