"""
This type stub file was generated by pyright.
"""

from driver.pca9685 import Servos

class Servo2Module(Servos):
    def __init__(self, address=..., freq=..., min_us=..., max_us=..., degrees=...) -> None:
        ...
    
    def deinit(self): # -> None:
        ...
    


