"""
This type stub file was generated by pyright.
"""

class StepMotorDriverModule:
    """

    note:
        cn: 步进电机驱动模块 13.2 V1.1 是一款适配于 M5 主控的步进电机驱动器，采用 STM32+HR8825 步进电机驱动方案，提供 3 路双极步进电机控制接口。
        en: StepMotor Driver Module 13.2 V1.1 is a stepper motor driver adapted to M5 main control, using STM32+HR8825 stepper motor drive scheme, providing 3-way bipolar stepper motor control interface.

    details:
        color: "#0FE6D7"
        link: https://docs.m5stack.com/en/module/Stepmotor%20Driver%20Module13.2%20v1.1
        image: https://static-cdn.m5stack.com/resource/docs/products/module/Stepmotor%20Driver%20Module13.2%20v1.1/img-c2b8ceac-b6be-4cec-9a15-228fcf8623e7.webp
        category: Module

    example: |
        from module import StepMotorDriverModule
        motor = StepMotorDriverModule(step_pin=(16, 12, 15), dir_pin=(17, 13, 0)) # Core


    """
    MOTOR_X = ...
    MOTOR_Y = ...
    MOTOR_Z = ...
    MOTOR_STATE_ENABLE = ...
    MOTOR_STATE_DISABLE = ...
    INPUT_REG = ...
    OUTPUT_REG = ...
    POLINV_REG = ...
    CONFIG_REG = ...
    FAULT_REG = ...
    RESET_REG = ...
    FIRM_REG = ...
    I2C_REG = ...
    STEP_FULL = ...
    STEP1_2 = ...
    STEP1_4 = ...
    STEP1_8 = ...
    STEP1_16 = ...
    STEP1_32 = ...
    def __init__(self, address: int = ..., step_pin: tuple | list = ..., dir_pin: tuple | list = ...) -> None:
        """
        note:
            en: Initialize the StepMotorDriverModule.
            cn: 初始化步进电机驱动模块。

        params:
            address:
              note: The I2C address of the device.
            step_pin:
              note: The step pin (X, Y, Z) of the motor.
            dir_pin:
              note: The dir pin (X, Y, Z) of the motor.
        """
        ...
    
    def reset_motor(self, motor_id, state: bool = ...): # -> None:
        """
        note:
            en: Reset the motor.
            cn: 重置电机。

        params:
            motor_id:
              note: The motor to reset.
              field: dropdown
              options:
                X: StepMotorDriverModule.MOTOR_X
                Y: StepMotorDriverModule.MOTOR_Y
                Z: StepMotorDriverModule.MOTOR_Z
            state:
              note: The state of the motor.
              field: switch
        """
        ...
    
    def set_motor_state(self, state: bool = ...): # -> None:
        """
        note:
            en: Enable or disable the motor.
            cn: 启用或禁用电机。

        params:
            state:
              note: The state of the motor.
              field: switch
        """
        ...
    
    def set_microstep(self, step): # -> None:
        """
        note:
            en: Set the microstep.
            cn: 设置微步。

        params:
            step:
              note: The microstep value.
              field: dropdown
              options:
                FULL: StepMotorDriverModule.STEP_FULL
                1/2: StepMotorDriverModule.STEP1_2
                1/4: StepMotorDriverModule.STEP1_4
                1/8: StepMotorDriverModule.STEP1_8
                1/16: StepMotorDriverModule.STEP1_16
                1/32: StepMotorDriverModule.STEP1_32
        """
        ...
    
    def set_motor_pwm_freq(self, motor_id, freq: int): # -> None:
        """
        note:
            en: Set the motor pwm freq.
            cn: 设置电机PWM频率。

        params:
            motor_id:
              note: The motor to set the freq.
              field: dropdown
              options:
                X: StepMotorDriverModule.MOTOR_X
                Y: StepMotorDriverModule.MOTOR_Y
                Z: StepMotorDriverModule.MOTOR_Z
            freq:
              note: The freq value.
        """
        ...
    
    def set_motor_direction(self, motor_id, direction: bool): # -> None:
        """
        note:
            en: Set the motor direction.
            cn: 设置电机方向。

        params:
            motor_id:
              note: The motor to set the direction.
              field: dropdown
              options:
                X: StepMotorDriverModule.MOTOR_X
                Y: StepMotorDriverModule.MOTOR_Y
                Z: StepMotorDriverModule.MOTOR_Z
            direction:
              note: The direction value.
              field: dropdown
              options:
                Positive: 1
                Negative: 0
        """
        ...
    
    def get_all_limit_switch_state(self): # -> Any:
        """
        note:
            en: Get all io state.
            cn: 获取所有IO状态。
        """
        ...
    
    def get_limit_switch_state(self, switch_id: int): # -> Any:
        """
        note:
            en: Get the io state.
            cn: 获取IO状态。

        params:
            switch_id:
              note: The io id.
        """
        ...
    
    def get_fault_io_state(self, motor_id: int): # -> Any:
        """
        note:
            en: Get the fault io state.
            cn: 获取故障IO状态。

        params:
            motor_id:
              note: The motor id.
              field: dropdown
              options:
                X: StepMotorDriverModule.MOTOR_X
                Y: StepMotorDriverModule.MOTOR_Y
                Z: StepMotorDriverModule.MOTOR_Z
        """
        ...
    
    def motor_control(self, motor_id, state: bool): # -> None:
        """
        note:
            en: Control the motor to rotate/stop.
            cn: 控制电机旋转/停止。

        params:
            motor_id:
              note: The motor id.
              field: dropdown
              options:
                X: StepMotorDriverModule.MOTOR_X
                Y: StepMotorDriverModule.MOTOR_Y
                Z: StepMotorDriverModule.MOTOR_Z
            state:
              note: The state value.
              field: dropdown
              options:
                Rotate: 1
                Stop: 0
        """
        ...
    
    def get_firmware_version(self): # -> Any:
        """
        note:
            en: Get the firmware version.
            cn: 获取固件版本。
        """
        ...
    
    def set_i2c_address(self, new_address: int): # -> None:
        """
        note:
            en: Set the i2c address.
            cn: 设置I2C地址。

        params:
            new_address:
              note: The new address.
        """
        ...
    


