"""
This type stub file was generated by pyright.
"""

import sys
from unit import ZigbeeUnit
from typing import Literal

if sys.platform != "esp32":
    ...
class ZigbeeModule(ZigbeeUnit):
    def __init__(self, id: Literal[0, 1, 2], tx: int, rx: int, verbose=...) -> None:
        ...
    


