"""
This type stub file was generated by pyright.
"""

import lvgl as lv
import asyncio
import sys
from .lv_utils import event_loop

def fs_register(fs_drv, letter, cache_size=...): # -> None:
    ...

class LVTaskHandler:
    _current_instance = ...
    def __init__(self, freq=..., refresh_cb=..., exception_sink=...) -> None:
        ...
    
    @staticmethod
    def is_running(): # -> bool:
        ...
    
    @staticmethod
    def current_instance(): # -> LVTaskHandler | None:
        ...
    
    async def async_refresh(self):
        ...
    
    async def async_timer(self):
        ...
    
    def deinit(self): # -> None:
        ...
    
    def default_exception_sink(self, e): # -> None:
        ...
    


