"""
This type stub file was generated by pyright.
"""

import urequests as requests
import json

_server = ...
DEBUG = ...
_data_types = ...
class EzData:
    def __init__(self, token, key, public=...) -> None:
        ...
    
    def set(self, value, is_file=...): # -> str | None:
        ...
    
    def get_update_time(self): # -> int:
        ...
    
    def has_new_data(self): # -> bool:
        ...
    
    def get(self): # -> str | Any | None:
        ...
    
    def get_file(self, path): # -> None:
        ...
    
    def history(self) -> list:
        ...
    
    def delete(self): # -> bool | None:
        ...
    


def get_key_list(device_token=...): # -> dict[Any, Any] | None:
    ...

