"""
This type stub file was generated by pyright.
"""

class MultiPartForm:
    def __init__(self) -> None:
        ...
    
    def content_type(self): # -> str:
        ...
    
    def add_field(self, name, value): # -> None:
        ...
    
    def add_file(self, field, filename, mimetype=...): # -> None:
        ...
    
    def content_length(self): # -> int:
        ...
    
    def content(self): # -> bytes:
        ...
    


