"""
This type stub file was generated by pyright.
"""

import m5can
import sys
from typing import Literal

if sys.platform != "esp32":
    ...
class ATOMCANBase(m5can.CAN):
    """Create an ATOMCANBase object

    :param int id: The CAN ID to use, Default is 0.
    :param port: A list or tuple containing the TX and RX pin numbers.
    :type port: list | tuple
    :param int mode: The CAN mode to use(NORMAL, NO_ACKNOWLEDGE, LISTEN_ONLY), Default is NORMAL.
    :param int baudrate: The baudrate to use, Default is 1000000.

    UiFlow2 Code Block:

        |init.png|

    MicroPython Code Block:

        .. code-block:: python

            from base import ATOMCANBase

            base_can = ATOMCANBase(0, (6, 5), ATOMCANBase.NORMAL, baudrate=1000000)
    """
    _timing_table = ...
    def __init__(self, id: Literal[0, 1], port: list | tuple = ..., mode: int = ..., *args, **kwargs) -> None:
        ...
    


