"""
This type stub file was generated by pyright.
"""

import sys
from typing import Literal

"""
@File    :   atom_socket.py
@Time    :   2024/3/29
@Author  :   TONG YIHAN
@E-mail  :   icyqwq@gmail.com
@License :   (C)Copyright 2015-2024, M5STACK
"""
if sys.platform != "esp32":
    ...
class ATOMSocketBase:
    """! ATOM Socket is a smart power socket adapted to ATOM main control.

    @en ATOM Socket is a smart power socket adapted to ATOM main control. Built-in HLW8032 high-precision energy metering IC. It can measure the voltage, current, power, and energy of the load. It can also be used as a smart socket to control the power on and off of the load. It can be used in various scenarios such as smart home, industrial control, and energy management.
    @cn ATOM Socket 是集成了M5 ATOM作为控制器的智能电源插座。内置HLW8032高精度电能表IC，可以测量负载的电压、电流、功率和能量。同时也可以作为智能插座控制负载的开关，可以应用于智能家居、工业控制、能源管理等各种场景。

    @color #0FE6D7
    @link https://docs.m5stack.com/en/atom/atom_socket
    @image https://static-cdn.m5stack.com/resource/docs/products/atom/atom_socket/atom_socket_01.webp
    @category Base

    @init
        from base import ATOMSocketBase
        atomsocket = ATOMSocketBase(1,(22,33),23) # for atom lite
        atomsocket = ATOMSocketBase(1,(5,8),7) # for atom s3

    @test
        atomsocket.get_data() # got (230.4192, 0.02074951, 0.8106091, 0.0)
        atomsocket.set_relay(True)
        atomsocket.set_relay(False)
        atomsocket.get_voltage() # got 230.4192
        atomsocket.get_current() # got 0.02074951
        atomsocket.get_power() # got 0.8106091
        atomsocket.get_pf()
        atomsocket.get_inspecting_power() # got 4.774
        atomsocket.get_power_factor() # got 5.88235
        atomsocket.get_kwh() # got 0.0
        def f(voltage, current, power, kwh): print(voltage, current, power, kwh)
        atomsocket.receive_none_block(f)
        atomsocket.stop_receive_data()

    """
    def __init__(self, _id: Literal[0, 1, 2], port: list | tuple, relay: int = ...) -> None:
        """! Initialize the ATOM Socket.

        @param id serial id, no actual use for this base.
        @param port UART pin number.
        @param relay The relay pin number.
        """
        ...
    
    def set_relay(self, state: bool) -> None:
        """! Set the relay state of the ATOM Socket.

        @param state The state of the relay.
        """
        ...
    
    def get_data(self, timeout=...) -> tuple:
        """! Get the data from the ATOM Socket.

        @param timeout The timeout of the function.

        @return The data of the ATOM Socket: Voltage (V), Current (A), Power (W), Total Energy (KWh). None if the timeout.

        """
        ...
    
    def get_voltage(self) -> float:
        """! Get the voltage of the ATOM Socket."""
        ...
    
    def get_current(self) -> float:
        """! Get the current of the ATOM Socket."""
        ...
    
    def get_power(self) -> float:
        """! Get the power of the ATOM Socket."""
        ...
    
    def get_pf(self) -> int:
        """! Get the power factor of the ATOM Socket."""
        ...
    
    def get_inspecting_power(self) -> float:
        """! Get the inspecting power of the ATOM Socket."""
        ...
    
    def get_power_factor(self) -> float:
        """! Get the power factor of the ATOM Socket."""
        ...
    
    def get_kwh(self) -> float:
        """! Get the KWh of the ATOM Socket."""
        ...
    
    def stop_receive_data(self) -> None:
        """! Stop receiving data from the ATOM Socket."""
        ...
    
    def receive_none_block(self, receive_callback) -> None:
        """! Receive data from the ATOM Socket.  in none block mode."""
        ...
    
    def __enter__(self): # -> Self:
        ...
    
    def __exit__(self, exc_type, exc_val, exc_tb): # -> None:
        """! Stop receiving data from the ATOM Socket."""
        ...
    


