"""
This type stub file was generated by pyright.
"""

import sys
from typing import Literal

if sys.platform != "esp32":
    ...
timTh = ...
class ATOMGPSBase:
    """Create an ATOMGPSBase object.

    :param int id: The UART ID to use (0, 1, or 2). Default is 2.
    :param port: A list or tuple containing the TX and RX pin numbers.
    :type port: list | tuple
    :param bool debug: Whether to enable debug mode. Default is False.

    UiFlow2 Code Block:

        |init.png|

    MicroPython Code Block:

        .. code-block:: python

            from machine import UART
            from base import ATOMGPSBase

            gps = ATOMGPSBase(id=1, port=(16, 17))
    """
    def __init__(self, id: Literal[0, 1, 2] = ..., port: list | tuple = ..., debug=...) -> None:
        ...
    
    def get_antenna_state(self) -> str:
        """Get the state of the antenna.

        :returns: The current antenna state.
        :rtype: str

        UiFlow2 Code Block:

            |get_antenna_state.png|

        MicroPython Code Block:

            .. code-block:: python

                gps.get_antenna_state()
        """
        ...
    
    def get_gps_time(self) -> list[str]:
        """Get the current GPS time.

        :returns: The GPS time as a list of strings [hour, minute, second].
        :rtype: list[str]

        UiFlow2 Code Block:

            |get_gps_time.png|

        MicroPython Code Block:

            .. code-block:: python

                gps.get_gps_time()
        """
        ...
    
    def get_gps_date(self) -> list[str]:
        """Get the current GPS date.

        :returns: The GPS date as a list of strings [day, month, year].
        :rtype: list[str]

        UiFlow2 Code Block:

            |get_gps_date.png|

        MicroPython Code Block:

            .. code-block:: python

                gps.get_gps_date()
        """
        ...
    
    def get_gps_date_time(self) -> list[str]:
        """Get the current GPS date and time combined.

        :returns: The GPS date and time as a list of strings [year, month, day, hour, minute, second].
        :rtype: list[str]

        UiFlow2 Code Block:

            |get_gps_date_time.png|

        MicroPython Code Block:

            .. code-block:: python

                gps.get_gps_date_time()
        """
        ...
    
    def get_timestamp(self) -> int | float:
        """Get the timestamp of the current GPS time.

        :returns: The timestamp representing the current GPS time.
        :rtype: int | float

        UiFlow2 Code Block:

            |get_timestamp.png|

        MicroPython Code Block:

            .. code-block:: python

                gps.get_timestamp()
        """
        ...
    
    def get_latitude(self) -> str:
        """Get the current latitude.

        :returns: The current latitude.
        :rtype: str

        UiFlow2 Code Block:

            |get_latitude.png|

        MicroPython Code Block:

            .. code-block:: python

                gps.get_latitude()
        """
        ...
    
    def get_longitude(self) -> str:
        """Get the current longitude.

        :returns: The current longitude.
        :rtype: str

        UiFlow2 Code Block:

            |get_longitude.png|

        MicroPython Code Block:

            .. code-block:: python

                gps.get_longitude()
        """
        ...
    
    def get_altitude(self) -> str:
        """Get the current altitude.

        :returns: The current altitude.
        :rtype: str

        UiFlow2 Code Block:

            |get_altitude.png|

        MicroPython Code Block:

            .. code-block:: python

                gps.get_altitude()
        """
        ...
    
    def get_satellite_num(self) -> str:
        """Get the number of satellites used for positioning.

        :returns: The number of satellites.
        :rtype: str

        UiFlow2 Code Block:

            |get_satellite_num.png|

        MicroPython Code Block:

            .. code-block:: python

                gps.get_satellite_num()
        """
        ...
    
    def get_pos_quality(self) -> str:
        """Get the quality of the GPS position.

        :returns: The position quality indicator.
        :rtype: str

        UiFlow2 Code Block:

            |get_pos_quality.png|

        MicroPython Code Block:

            .. code-block:: python

                gps.get_pos_quality()
        """
        ...
    
    def get_corse_over_ground(self) -> str:
        """Get the course over ground (COG).

        :returns: The course over ground in degrees.
        :rtype: str

        UiFlow2 Code Block:

            |get_corse_over_ground.png|

        MicroPython Code Block:

            .. code-block:: python

                gps.get_corse_over_ground()
        """
        ...
    
    def get_speed_over_ground(self) -> str:
        """Get the speed over ground (SOG).

        :returns: The speed over ground in knots.
        :rtype: str

        UiFlow2 Code Block:

            |get_speed_over_ground.png|

        MicroPython Code Block:

            .. code-block:: python

                gps.get_speed_over_ground()
        """
        ...
    
    def set_time_zone(self, value: int) -> None:
        """Set the time zone offset for the GPS time.

        :param int value: The time zone offset value to set.

        UiFlow2 Code Block:

            |set_time_zone.png|

        MicroPython Code Block:

            .. code-block:: python

                gps.set_time_zone(8)
        """
        ...
    
    def get_time_zone(self) -> int:
        """Get the current time zone offset.

        :returns: The current time zone offset.
        :rtype: int

        UiFlow2 Code Block:

            |get_time_zone.png|

        MicroPython Code Block:

            .. code-block:: python

                gps.get_time_zone()
        """
        ...
    
    def deinit(self) -> None:
        """Deinitialize the GPS unit, stopping any running tasks and releasing resources.

        UiFlow2 Code Block:

            |deinit.png|

        MicroPython Code Block:

            .. code-block:: python

                gps.deinit()
        """
        ...
    


