"""
This type stub file was generated by pyright.
"""

class AtomicDisplayBase:
    """Initialize the Atomic Display Base.

    :param int width: The logical width of the Atomic Display Base. Default is 1280px.
    :param int height: The logical height of the Atomic Display Base. Default is 720px.
    :param int refresh_rate: The refresh rate of the Atomic Display Base. Default is 60Hz.
    :param int output_width: The width of the output of the Atomic Display Base. Default is 1280px.
    :param int output_height: The height of the output of the Atomic Display Base. Default is 720px.
    :param int scale_w: The scale width of the Atomic Display Base. Default is 1.
    :param int scale_h: The scale height of the Atomic Display Base. Default is 1.
    :param int pixel_clock: The pixel clock of the Atomic Display Base. Default is 74250000.

    UiFlow2 Code Block:

        |init.png|

    MicroPython Code Block:

        .. code-block:: python

            from base import AtomicDisplayBase
            atom_display = AtomicDisplayBase(1280, 720, 60, 1280, 720, 1, 1, 74250000)
    """
    def __new__(cls, width: int = ..., height: int = ..., refresh_rate: int = ..., output_width: int = ..., output_height: int = ..., scale_w: int = ..., scale_h: int = ..., pixel_clock: int = ...) -> None:
        ...
    


