"""
This type stub file was generated by pyright.
"""

import sys
from driver.simcom.sim7020 import SIM7020
from driver.simcom.common import Modem

if sys.platform != "esp32":
    ...
class AtomDTUNBIoT(SIM7020, Modem):
    """Create an AtomDTUNBIoT object

    :param int id: The UART ID to use (0, 1, or 2). Default is 2.
    :param port: A list or tuple containing the TX and RX pin numbers.
    :type port: list | tuple

    UiFlow2 Code Block:

        |init.png|

    MicroPython Code Block:

        .. code-block:: python

            from base import AtomDTUNBIoT

            dtu_nbiot = AtomDTUNBIoT(0, (22, 19))
    """
    def __init__(self, uart, verbose=...) -> None:
        ...
    


