"""
This type stub file was generated by pyright.
"""

import sys
from driver.asr650x import LoRaWAN_470
from typing import Literal

if sys.platform != "esp32":
    ...
class AtomDTULoRaWANBase(LoRaWAN_470):
    """Create an AtomDTULoRaWANBase object

    :param int id: The UART ID to use (0, 1, or 2). Default is 2.
    :param port: A list or tuple containing the TX and RX pin numbers.
    :type port: list | tuple

    UiFlow2 Code Block:

        |init.png|

    MicroPython Code Block:

        .. code-block:: python

            from base import AtomDTULoRaWANBase

            dtu_lorawan = AtomDTULoRaWANBase(0, (6, 5))
    """
    def __init__(self, id: Literal[0, 1, 2] = ..., port: list | tuple = ...) -> None:
        ...
    
    def deinit(self): # -> None:
        ...
    


