"""
This type stub file was generated by pyright.
"""

class AtomicEchoBase:
    """Create an AtomicEchoBase object.

    :param I2C i2c: I2C object
    :param int address: The I2C address of the ES8311. Default is 0x18.
    :param int i2s_port: The I2S port number. Default is 1.
    :param int sample_rate: The sample rate of the audio. Default is 16000.
    :param int i2s_sck: The I2S SCK pin. Default is -1.
    :param int i2s_ws: The I2S WS pin. Default is -1.
    :param int i2s_di: The I2S DI pin. Default is -1.
    :param int i2s_do: The I2S DO pin. Default is -1.

    UIFLOW2:

        |init.png|

    Micropython::

        from hardware import I2C
        from hardware import Pin
        from base import AtomicEchoBase

        # atom echo
        i2c1 = I2C(1, scl=Pin(21), sda=Pin(25), freq=100000)
        base_echo = AtomicEchoBase(i2c1, address=0x18, i2s_port=1, sample_rate=44100, i2s_sck=33, i2s_ws=19, i2s_di=23, i2s_do=22)

        # atom lite
        i2c1 = I2C(1, scl=Pin(21), sda=Pin(25), freq=100000)
        base_echo = AtomicEchoBase(i2c1, address=0x18, i2s_port=1, sample_rate=44100, i2s_sck=33, i2s_ws=19, i2s_di=23, i2s_do=22)

        # atom matrix
        i2c1 = I2C(1, scl=Pin(21), sda=Pin(25), freq=100000)
        base_echo = AtomicEchoBase(i2c1, address=0x18, i2s_port=1, sample_rate=44100, i2s_sck=33, i2s_ws=19, i2s_di=23, i2s_do=22)

        # atoms3 / atoms3 lite
        i2c1 = I2C(1, scl=Pin(39), sda=Pin(38), freq=100000)
        base_echo = AtomicEchoBase(i2c1, address=0x18, i2s_port=1, sample_rate=44100, i2s_sck=8, i2s_ws=6, i2s_di=7, i2s_do=5)

        # atoms3r / atoms3r-cam / atoms3-ext
        i2c1 = I2C(1, scl=Pin(39), sda=Pin(38), freq=100000)
        base_echo = AtomicEchoBase(i2c1, address=0x18, i2s_port=1, sample_rate=44100, i2s_sck=8, i2s_ws=6, i2s_di=7, i2s_do=5)

        base_echo.speaker.tone(2000, 1000)
        base_echo.speaker.playWavFile('res/audio/66.wav')
    """
    _instance = ...
    PI4IOE_REG_CTRL = ...
    PI4IOE_REG_CHIP_RESET = ...
    PI4IOE_REG_IO_DIR = ...
    PI4IOE_REG_IO_OUT = ...
    PI4IOE_REG_IO_PP = ...
    PI4IOE_REG_PULL_EN = ...
    PI4IOE_REG_IO_PULLUP = ...
    MONO = ...
    STEREO = ...
    def __new__(cls, *args, **kwargs): # -> Self:
        ...
    
    def __init__(self, i2c, address: int = ..., i2s_port: int = ..., sample_rate: int = ..., i2s_sck: int = ..., i2s_ws: int = ..., i2s_di: int = ..., i2s_do: int = ...) -> None:
        ...
    
    def pi4ioe_init(self): # -> None:
        ...
    
    def set_mute(self, mute): # -> None:
        ...
    
    def change_sample_rate(self, sample_rate: int) -> None:
        ...
    
    def play_wav_file(self, file: str) -> None:
        """Play a WAV file.

        :param str file: The path of the WAV file to play.
        :return: None

        UiFlow2 Code Block:

            |play_wav_file.png|

        MicroPython Code Block:

            .. code-block:: python

                base_echo.play_wav_file("/flash/res/audio/test.wav")
        """
        ...
    
    def tone(self, freq: int, duration: int) -> None:
        """Play simple tone sound.

        :param int freq: Frequency of the tone in Hz.
        :param int duration: Duration of the tone in milliseconds.
        :return: None

        UiFlow2 Code Block:

            |tone.png|

        MicroPython Code Block:

            .. code-block:: python

                base_echo.tone(2000, 50)
        """
        ...
    
    def play_wav(self, buf: bytes, duration: int = ...) -> None:
        """Play a WAV buffer.

        :param bytes buf: The WAV buffer to play.
        :param int duration: Duration of the WAV buffer in milliseconds. when duration is -1, it will play until stopped. (default is -1).
        :return: None

        UiFlow2 Code Block:

            |play_wav.png|

        MicroPython Code Block:

            .. code-block:: python

                base_echo.play_wav(wav_buffer, duration=1000)
        """
        ...
    
    def play_raw(self, buf: bytes, rate: int = ..., bits: int = ..., channel: int = ..., duration: int = ...) -> None:
        """Play a pcm buffer.

        :param bytes buf: The PCM buffer to play.
        :param int rate: Sample rate (default is 16000).
        :param int bits: Bit depth (default is 16).
        :param int channel: Number of channels (default is 2).
        :param int duration: Duration of the PCM buffer in milliseconds. when duration is -1, it will play until stopped. (default is -1).
        :return: None

        UiFlow2 Code Block:

            |play_raw.png|

        MicroPython Code Block:

            .. code-block:: python

                base_echo.play_raw(pcm_buffer, rate=16000, bits=16, channel=2, duration=1000)
        """
        ...
    
    def pause(self) -> None:
        """Pause the playback.

        UiFlow2 Code Block:

            |pause.png|

        MicroPython Code Block:

            .. code-block:: python

                audio.tone(2000, 100)
                time.sleep(0.05)
                base_echo.pause()
                time.sleep(0.05)
                base_echo.resume()
        """
        ...
    
    def resume(self): # -> None:
        """Resume the playback.

        UiFlow2 Code Block:

            |resume.png|

        MicroPython Code Block:

            .. code-block:: python

                audio.tone(2000, 100)
                time.sleep(0.05)
                base_echo.pause()
                time.sleep(0.05)
                base_echo.resume()
        """
        ...
    
    def stop(self): # -> None:
        """Stop the playback.

        UiFlow2 Code Block:

            |stop.png|

        MicroPython Code Block:

            .. code-block:: python

                audio.tone(2000, 100)
                time.sleep(0.05)
                base_echo.stop()
        """
        ...
    
    def get_volume(self) -> int:
        """Get the speaker volume level.

        :return: The volume level (0-100).

        UiFlow2 Code Block:

            |get_volume.png|

        MicroPython Code Block:

            .. code-block:: python

                base_echo.get_volume()
        """
        ...
    
    def set_volume(self, volume): # -> None:
        """Set the speaker volume level.

        :param int volume: The volume level (0-100).

        UiFlow2 Code Block:

            |set_volume.png|

        MicroPython Code Block:

            .. code-block:: python

                base_echo.set_volume(50)
        """
        ...
    
    def record_wav_file(self, path: str, rate: int = ..., bits: int = ..., channel: int = ..., duration: int = ...): # -> None:
        """Record audio to a WAV file.

        :param str path: The path to save the WAV file.
        :param int rate: Sample rate (default is 16000).
        :param int bits: Bit depth (default is 16).
        :param int channel: Number of channels (default is 2).
        :param int duration: Duration of the recording in milliseconds (default is 3000).

        UiFlow2 Code Block:

            |record_wav_file.png|

        MicroPython Code Block:

            .. code-block:: python

                base_echo.record_wav_file("/flash/res/audio/test.wav", rate=16000, bits=16, channel=2, duration=3000)
        """
        ...
    
    def record(self, rate=..., bits=..., channel=..., duration=...):
        """Record audio to a PCM buffer.

        :param int rate: Sample rate (default is 16000).
        :param int bits: Bit depth (default is 16).
        :param int channel: Number of channels (default is 2).
        :param int duration: Duration of the recording in milliseconds (default is 3000).

        UiFlow2 Code Block:

            |record.png|

        MicroPython Code Block:

            .. code-block:: python

                base_echo.record(rate=16000, bits=16, channel=2, duration=3000)
        """
        ...
    
    @property
    def pcm_buffer(self) -> bytes:
        """Get the PCM buffer.

        :return: The PCM buffer.

        UiFlow2 Code Block:

            |pcm_buffer.png|

        MicroPython Code Block:

            .. code-block:: python

                base_echo.pcm_buffer
        """
        ...
    
    def deinit(self): # -> None:
        ...
    


