"""
This type stub file was generated by pyright.
"""

class AtomicHDriverBase:
    """Create an AtomicHDriverBase object.

    :param int in1: PWM control pin1.
    :param int in2: PWM control pin2.
    :param int fault: driver status.
    :param int vin: driver input voltage detect.
    :param int freq: The PWM frequency.

    UiFlow2 Code Block:

        |init.png|

    MicroPython Code Block:

        .. code-block:: python

            from base import AtomicHDriverBase

            base_hdriver = AtomicHDriverBase(in1 = 6, in2 = 7, fault = 5, vin = 8, freq = 1000)
    """
    def __init__(self, in1: int = ..., in2: int = ..., fault: int = ..., vin: int = ..., freq: int = ...) -> None:
        ...
    
    def set_freq(self, freq: int = ...) -> None:
        """Set PWM frequency.

        :param int freq: The PWM frequency. Default is 1000.

        UiFlow2 Code Block:

            |set_freq.png|

        MicroPython Code Block:

            .. code-block:: python

                base_hdriver.set_freq()
        """
        ...
    
    def get_freq(self) -> int:
        """Get PWM frequency.

        :returns: PWM frequency.
        :rtype: int

        UiFlow2 Code Block:

            |get_freq.png|

        MicroPython Code Block:

            .. code-block:: python

                base_hdriver.get_freq()
        """
        ...
    
    def set_speed(self, speed: float = ...) -> None:
        """Set motor speed.

        :param float speed: The motor speed. Range -100~100. Default is 0.

        UiFlow2 Code Block:

            |set_speed.png|

        MicroPython Code Block:

            .. code-block:: python

                base_hdriver.set_speed()
        """
        ...
    
    def get_status(self) -> bool:
        """Get driver status.

        :returns: The driver status. Returns True if the driver is operating normally, or False if a fault is detected.
        :rtype: bool

        UiFlow2 Code Block:

            |get_status.png|

        MicroPython Code Block:

            .. code-block:: python

                base_hdriver.get_status()
        """
        ...
    
    def get_voltage(self) -> float:
        """Get voltage.

        :returns: The driver input voltage. unit: V
        :rtype: float

        UiFlow2 Code Block:

            |get_voltage.png|

        MicroPython Code Block:

            .. code-block:: python

                base_hdriver.get_voltage()
        """
        ...
    


