"""
This type stub file was generated by pyright.
"""

from machine import I2C

"""
@File    :   motion.py
@Time    :   2024/4/28
@Author  :   TONG YIHAN
@E-mail  :   icyqwq@gmail.com
@License :   (C)Copyright 2015-2024, M5STACK
"""
class Motion:
    """Create an Motion object.

    :param I2C i2c: The I2C port to use.
    :param int address: The device address.  Default is 0x38.

    UiFlow2 Code Block:

        |__init__.png|

    MicroPython Code Block:

        .. code-block:: python

            from base import Motion
            from machine import I2C

            i2c0 = I2C(0, scl=Pin(39), sda=Pin(38), freq=100000)
            motion = Motion(i2c0, 0x38)
    """
    def __init__(self, i2c: I2C, address: int | list | tuple = ...) -> None:
        ...
    
    def get_servo_angle(self, ch: int) -> int:
        """Get the angle of the servo.

        :param int ch: The servo channel. Range: 1~4.
        :returns: Specify the servo angle for the specified channel. Range: 0~180.
        :rtype: int

        UiFlow2 Code Block:

            |get_servo_angle.png|

        MicroPython Code Block:

            .. code-block:: python

                motion.get_servo_angle()
        """
        ...
    
    def set_servo_angle(self, ch, angle) -> None:
        """Set the angle of the servo.

        :param int ch: The servo channel. Range: 1~4.
        :param int angle: The servo angle. Range: 0~180.

        UiFlow2 Code Block:

            |set_servo_angle.png|

        MicroPython Code Block:

            .. code-block:: python

                motion.set_servo_angle()
        """
        ...
    
    def get_servo_pulse(self, ch) -> int:
        """Get the pulse of the servo.

        :param int ch: The servo channel. Range: 1~4.
        :returns: Specify the servo pulse for the specified channel. Range: 500~2500.
        :rtype: int

        UiFlow2 Code Block:

            |get_servo_pulse.png|

        MicroPython Code Block:

            .. code-block:: python

                motion.get_servo_pulse()
        """
        ...
    
    def write_servo_pulse(self, ch, pulse) -> None:
        """Write the pulse of the servo.

        :param int ch: The servo channel. Range: 1~4.
        :param int pulse: The servo pulse. Range: 500~2500.

        UiFlow2 Code Block:

            |write_servo_pulse.png|

        MicroPython Code Block:

            .. code-block:: python

                motion.write_servo_pulse()
        """
        ...
    
    def get_motor_speed(self, ch) -> int:
        """Get the speed of the motor.

        :param int ch: The motor id. Range: 1~2.
        :returns: Specify the speed for the specified channel. Range: -127~127.
        :rtype: int

        UiFlow2 Code Block:

            |get_motor_speed.png|

        MicroPython Code Block:

            .. code-block:: python

                motion.get_motor_speed()
        """
        ...
    
    def set_motor_speed(self, ch, speed) -> None:
        """Set motor speed.

        :param int ch: The motor channel. Range: 1~2.
        :param int speed: The motor speed. Range: -127~127.

        UiFlow2 Code Block:

            |set_motor_speed.png|

        MicroPython Code Block:

            .. code-block:: python

                motion.set_motor_speed()
        """
        ...
    
    def read_voltage(self) -> float:
        """Read voltage (unit: V).

        :returns: The voltage value in volts.
        :rtype: float

        .. note::
            This method is supported only on Motion Base v1.1 and later versions.

        UiFlow2 Code Block:

            |read_voltage.png|

        MicroPython Code Block:

            .. code-block:: python

                motion.read_voltage()
        """
        ...
    
    def read_current(self) -> float:
        """Read current (unit: A).

        :returns: The current value in amperes.
        :rtype: float

        .. note::
            This method is supported only on Motion Base v1.1 and later versions.

        UiFlow2 Code Block:

            |read_current.png|

        MicroPython Code Block:

            .. code-block:: python

                motion.read_current()
        """
        ...
    
    def read_power(self) -> float:
        """Read power (unit: W).

        :returns: The power value in watts.
        :rtype: float

        .. note::
            This method is supported only on Motion Base v1.1 and later versions.

        UiFlow2 Code Block:

            |read_power.png|

        MicroPython Code Block:

            .. code-block:: python

                motion.read_power()
        """
        ...
    


