"""
This type stub file was generated by pyright.
"""

class AtomicQRCodeBase:
    """Create an AtomicQRCodeBase object.

    :param int id: UART id.
    :param int tx: the UART TX pin.
    :param int rx: the UART RX pin.
    :param int trig: the trigger pin.
    :param int done: the receive done pin.

    UiFlow2 Code Block:

        |init.png|

    MicroPython Code Block:

        .. code-block:: python

            from base import AtomicQRCodeBase

            base_qrcode = AtomicQRCodeBase(id = 1, tx = 6, rx = 5, trig = 7, done = 8)
    """
    TRIGGER_MODE_KEY = ...
    TRIGGER_MODE_HOST = ...
    TRIGGER_MODE_AUTO = ...
    TRIGGER_MODE_PULSE = ...
    TRIGGER_MODE_MOTION_SENSING = ...
    FILL_LIGHT_ON_DECODE = ...
    FILL_LIGHT_ON = ...
    FILL_LIGHT_OFF = ...
    POS_LIGHT_ON_DECODE = ...
    POS_LIGHT_ON = ...
    POS_LIGHT_OFF = ...
    cmd_ack = ...
    def __init__(self, id: int = ..., tx: int = ..., rx: int = ..., trig: int = ..., done: int = ...) -> None:
        ...
    
    def set_trig(self, value: int) -> None:
        """Set trigger value.

        :param int value: ``0`` - Low level, ``1`` - High level.

        UiFlow2 Code Block:

            |set_trig.png|

        MicroPython Code Block:

            .. code-block:: python

                base_qrcode.set_trig(value)
        """
        ...
    
    def start_decode(self) -> None:
        """Start decode.

        UiFlow2 Code Block:

            |start_decode.png|

        MicroPython Code Block:

            .. code-block:: python

                base_qrcode.start_decode()
        """
        ...
    
    def stop_decode(self) -> None:
        """Stop decode.

        UiFlow2 Code Block:

            |stop_decode.png|

        MicroPython Code Block:

            .. code-block:: python

                base_qrcode.stop_decode()
        """
        ...
    
    def read(self) -> None | bytes:
        """Read decode data.

        :returns: qrcode data.
        :rtype: None | bytes

        UiFlow2 Code Block:

            |read.png|

        MicroPython Code Block:

            .. code-block:: python

                base_qrcode.read()
        """
        ...
    
    def set_trigger_mode(self, mode: int) -> None:
        """Set trigger mode.

        :param int mode: The trigger mode. Available options:

            - ``TRIGGER_MODE_KEY``: Key Mode, Triggers a single decode; decoding stops after a successful read.
            - ``TRIGGER_MODE_HOST``: Host Mode, The command controls the start/stop of decoding. Once triggered, decoding will stop either upon successful decoding or after a timeout of 5 seconds.
            - ``TRIGGER_MODE_AUTO``: Auto Mode, Performs continuous decoding upon power-up and cannot be stopped.
            - ``TRIGGER_MODE_PULSE``: Pulse Mode, The Trig pin's low-level signal triggers decoding, which stops after a successful read or when the single read time limit is reached.
            - ``TRIGGER_MODE_MOTION_SENSING``: Motion Sensing Mode, Uses image recognition; decoding starts when a scene change is detected.

        UiFlow2 Code Block:

            |set_trigger_mode.png|

        MicroPython Code Block:

            .. code-block:: python

                base_qrcode.set_trigger_mode(mode)
        """
        ...
    
    def set_decode_continuous(self, delay_100ms: int) -> None:
        """Set continuous decode time.

        :param int delay_100ms: Continuous scanning time(unit: 100ms). Range: 099, i.e., 025,500 ms (0 means unlimited).

        UiFlow2 Code Block:

            |set_decode_continuous.png|

        MicroPython Code Block:

            .. code-block:: python

                base_qrcode.set_decode_continuous(delay_100ms)
        """
        ...
    
    def set_decode_interval(self, interval_100ms: int) -> None:
        """Set decode interval.

        :param int interval_100ms: Decode interval time(unit: 100ms). Range: 0~99, i.e., 0~9,900 ms.

        UiFlow2 Code Block:

            |set_decode_interval.png|

        MicroPython Code Block:

            .. code-block:: python

                base_qrcode.set_decode_interval(interval_100ms)
        """
        ...
    
    def set_same_code_interval(self, interval_100ms: int) -> None:
        """Set same code interval.

        :param int interval_100ms: Decode interval for the same code(unit: 100ms). Range: 0~99, i.e., 0~9,900 ms.

        UiFlow2 Code Block:

            |set_same_code_interval.png|

        MicroPython Code Block:

            .. code-block:: python

                base_qrcode.set_same_code_interval(interval_100ms)
        """
        ...
    
    def set_fill_light_mode(self, mode: int) -> None:
        """Set fill light mode.

        :param int mode: The fill light mode. Available options:
            - ``FILL_LIGHT_OFF``: Light off.
            - ``FILL_LIGHT_ON``: Light on.
            - ``FILL_LIGHT_ON_DECODE``: Light on during decoding.

        UiFlow2 Code Block:

            |set_fill_light_mode.png|

        MicroPython Code Block:

            .. code-block:: python

                base_qrcode.set_fill_light_mode(mode)
        """
        ...
    
    def set_pos_light_mode(self, mode: int) -> None:
        """Set positioning light mode.

        :param int mode: The positioning light mode. Available options:
            - ``POS_LIGHT_OFF``: Light off.
            - ``POS_LIGHT_ON``: Light on.
            - ``POS_LIGHT_ON_DECODE``: Light flash during decoding.

        UiFlow2 Code Block:

            |set_pos_light_mode.png|

        MicroPython Code Block:

            .. code-block:: python

                base_qrcode.set_pos_light_mode(mode)
        """
        ...
    
    def set_startup_tone(self, enable: bool) -> None:
        """Set startup tone.

        :param bool enable: True - Enable startup tone, False - Disable startup tone.

        UiFlow2 Code Block:

            |set_startup_tone.png|

        MicroPython Code Block:

            .. code-block:: python

                base_qrcode.set_startup_tone(enable)
        """
        ...
    
    def set_decode_success_tone(self, enable: bool) -> None:
        """Set decode success tone.

        :param bool enable: True - Enable decode success tone, False - Disable decode success tone.

        UiFlow2 Code Block:

            |set_decode_success_tone.png|

        MicroPython Code Block:

            .. code-block:: python

                base_qrcode.set_decode_success_tone(enable)
        """
        ...
    
    def set_config_tone(self, enable: bool) -> None:
        """Set config tone.

        :param bool enable: True - Enable set config tone, False - Disable set config tone.

        UiFlow2 Code Block:

            |set_config_tone.png|

        MicroPython Code Block:

            .. code-block:: python

                base_qrcode.set_config_tone(enable)
        """
        ...
    


