"""
This type stub file was generated by pyright.
"""

class AtomicStepmotorBase:
    """Create an AtomicStepmotorBase object.

    :param int en: Enable pin, used to enable or disable the stepper motor.
    :param int dir: Direction pin, used to control the rotation direction of the motor.
    :param int stp: Step pin, used for step control of the motor.
    :param int flt: Fault pin, used to monitor the motor's fault status.
    :param int rst: Reset pin, used to reset the motor driver.
    :param int pwr_adc: Power ADC monitoring pin, used to measure the input power supply voltage.

    UiFlow2 Code Block:

        |init.png|

    MicroPython Code Block:

        .. code-block:: python

            from base import AtomicStepmotorBase

            base_stepmotor = AtomicStepmotorBase(en=5, dir=7, stp=6, flt=38, rst=39, pwr_adc=8)
    """
    def __init__(self, en: int = ..., dir: int = ..., stp: int = ..., flt: int = ..., rst: int = ..., pwr_adc: int = ...) -> None:
        ...
    
    def enable(self) -> None:
        """Enable the stepper motor driver.

        UiFlow2 Code Block:

            |enable.png|

        MicroPython Code Block:

            .. code-block:: python

                base_stepmotor.enable()
        """
        ...
    
    def disable(self): # -> None:
        """Disable the stepper motor driver.

        UiFlow2 Code Block:

            |disable.png|

        MicroPython Code Block:

            .. code-block:: python

                base_stepmotor.disable()
        """
        ...
    
    def set_direction(self, direction: bool = ...) -> None:
        """Set direction.

        :param bool direction: Rotation direction. True or False.

        UiFlow2 Code Block:

            |set_direction.png|

        MicroPython Code Block:

            .. code-block:: python

                base_stepmotor.set_direction(direction)
        """
        ...
    
    def step(self) -> None:
        """Move the stepper motor one step.

        UiFlow2 Code Block:

            |step.png|

        MicroPython Code Block:

            .. code-block:: python

                base_stepmotor.step()
        """
        ...
    
    def rotate(self, steps: int, delay_ms: int = ..., direction: bool = ...) -> None:
        """Rotate the stepper motor for a specified number of steps.

        :param int steps: Number of steps to rotate.
        :param int delay_ms: Delay between steps (in milliseconds), default is 0ms.
        :param bool direction: Rotation direction (True or False).

        The actual rotation direction (clockwise or counterclockwise) depends on the motor wiring.

        UiFlow2 Code Block:

            |rotate.png|

        MicroPython Code Block:

            .. code-block:: python

                base_stepmotor.rotate(steps, delay_ms, direction)
        """
        ...
    
    def stop(self) -> None:
        """Stop motor.

        UiFlow2 Code Block:

            |stop.png|

        MicroPython Code Block:

            .. code-block:: python

                base_stepmotor.stop()
        """
        ...
    
    def get_status(self) -> bool:
        """Get motor driver status.

        :returns: Returns True if the driver is operating normally, or False if a fault is detected.
        :rtype: bool

        UiFlow2 Code Block:

            |get_status.png|

        MicroPython Code Block:

            .. code-block:: python

                base_stepmotor.get_status()
        """
        ...
    
    def reset(self) -> None:
        """Reset the stepper motor driver.

        UiFlow2 Code Block:

            |reset.png|

        MicroPython Code Block:

            .. code-block:: python

                base_stepmotor.reset()
        """
        ...
    
    def get_voltage(self) -> float:
        """Get voltage.

        :returns: The driver input voltage. unit: V
        :rtype: float

        UiFlow2 Code Block:

            |get_voltage.png|

        MicroPython Code Block:

            .. code-block:: python

                base_stepmotor.get_voltage()
        """
        ...
    


