"""
This type stub file was generated by pyright.
"""

from . import NeoPixel

class SK6812(NeoPixel):
    ORDER = ...
    def __init__(self, io: int, n: int, bpp: int = ..., timing: int = ...) -> None:
        ...
    
    def set_screen(self, color_list: list) -> None:
        ...
    


